// Alabama legislators mapped to legislatorSchema
export default [
  {
    "firstName": "Phillip",
    "lastName": "Pettus",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "Killen",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "phillip.pettus@alhouse.gov",
    "officePhone": "(334)261-0591"
  },
  {
    "firstName": "Ben",
    "lastName": "Harrison",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 2,
    "partyAffiliation": "Republican",
    "residence": "Athens",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ben.harrison@alhouse.gov",
    "officePhone": "(334)261-0476"
  },
  {
    "firstName": "Bubba",
    "lastName": "Underwood",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 3,
    "partyAffiliation": "Republican",
    "residence": "Tuscumbia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "bubba.underwood@alhouse.gov",
    "officePhone": "(334)261-0435"
  },
  {
    "firstName": "Parker",
    "lastName": "Moore",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "Decatur",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "parker.moore@alhouse.gov",
    "officePhone": "(334)261-0579"
  },
  {
    "firstName": "Danny",
    "lastName": "Crawford",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 5,
    "partyAffiliation": "Republican",
    "residence": "Athens",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "danny.crawford@alhouse.gov",
    "officePhone": "(334)261-0516"
  },
  {
    "firstName": "Andy",
    "lastName": "Whitt",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 6,
    "partyAffiliation": "Republican",
    "residence": "Ardmore",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "andy.whitt@alhouse.gov",
    "officePhone": "(334)261-0404"
  },
  {
    "firstName": "Ernie",
    "lastName": "Yarbrough",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "Trinity",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ernie.yarbrough@alhouse.gov",
    "officePhone": "(334)261-0454"
  },
  {
    "firstName": "Terri",
    "lastName": "Collins",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 8,
    "partyAffiliation": "Republican",
    "residence": "Decatur",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "terri.collins@alhouse.gov",
    "officePhone": "(334)261-0472"
  },
  {
    "firstName": "Scott",
    "lastName": "Stadthagen",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 9,
    "partyAffiliation": "Republican",
    "residence": "Hartselle",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "scott.stadthagen@alhouse.gov",
    "officePhone": "(334)261-9506"
  },
  {
    "firstName": "Marilyn",
    "lastName": "Lands",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 10,
    "partyAffiliation": "Democrat",
    "residence": "Huntsville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "marilyn.lands@alhouse.gov",
    "officePhone": "(334)261-0483"
  },
  {
    "firstName": "Vacant",
    "lastName": "Vacant",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 11,
    "partyAffiliation": "Vacant",
    "residence": "Vacant",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "Vacant",
    "lastName": "Vacant",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 12,
    "partyAffiliation": "Vacant",
    "residence": "Vacant",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "Matt",
    "lastName": "Woods",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 13,
    "partyAffiliation": "Republican",
    "residence": "Jasper",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "matt.woods@alhouse.gov",
    "officePhone": "(334)261-0495"
  },
  {
    "firstName": "Tim",
    "lastName": "Wadsworth",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 14,
    "partyAffiliation": "Republican",
    "residence": "Arley",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tim.wadsworth@alhouse.gov",
    "officePhone": "(205)300-4008"
  },
  {
    "firstName": "Leigh",
    "lastName": "Hulsey",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 15,
    "partyAffiliation": "Republican",
    "residence": "Helena",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "leigh.hulsey@alhouse.gov",
    "officePhone": "(334)261-0474"
  },
  {
    "firstName": "Bryan",
    "lastName": "Brinyark",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 16,
    "partyAffiliation": "Republican",
    "residence": "Windham Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "bryan.brinyark@alhouse.gov",
    "officePhone": "(334)261-0482"
  },
  {
    "firstName": "Tracy",
    "lastName": "Estes",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 17,
    "partyAffiliation": "Republican",
    "residence": "Winfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tracy.estes@alhouse.gov",
    "officePhone": "(334)261-0434"
  },
  {
    "firstName": "Jamie",
    "lastName": "Kiel",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 18,
    "partyAffiliation": "Republican",
    "residence": "Russellville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jamie.kiel@alhouse.gov",
    "officePhone": "(334)261-0521"
  },
  {
    "firstName": "Laura",
    "lastName": "Hall",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 19,
    "partyAffiliation": "Dem",
    "residence": "Huntsville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "laura.hall@alhouse.gov",
    "officePhone": "(334)261-0517"
  },
  {
    "firstName": "James",
    "lastName": "Lomax",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 20,
    "partyAffiliation": "Republican",
    "residence": "Huntsville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "james.lomax@alhouse.gov",
    "officePhone": "(334)261-0444"
  },
  {
    "firstName": "Rex",
    "lastName": "Reynolds",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 21,
    "partyAffiliation": "Republican",
    "residence": "Huntsville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rex.reynolds@alhouse.gov",
    "officePhone": "(334)261-0591"
  },
  {
    "firstName": "Ritchie",
    "lastName": "Whorton",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 22,
    "partyAffiliation": "Republican",
    "residence": "Owens Cross Roads",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ritchie.whorton@alhouse.gov",
    "officePhone": "(334)261-0553"
  },
  {
    "firstName": "Mike",
    "lastName": "Kirkland",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 23,
    "partyAffiliation": "Republican",
    "residence": "Scottsboro",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mike.kirkland@alhouse.gov",
    "officePhone": "(334)261-0551"
  },
  {
    "firstName": "Nathaniel",
    "lastName": "Ledbetter",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 24,
    "partyAffiliation": "Republican",
    "residence": "Rainsville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "nathaniel.ledbetter@alhouse.gov",
    "officePhone": "(334)261-0505"
  },
  {
    "firstName": "Phillip",
    "lastName": "Rigsby",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 25,
    "partyAffiliation": "Republican",
    "residence": "Huntsville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "phillip.rigsby@alhouse.gov",
    "officePhone": "(334)261-0514"
  },
  {
    "firstName": "Brock",
    "lastName": "Colvin",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 26,
    "partyAffiliation": "Republican",
    "residence": "Albertville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "brock.colvin@alhouse.gov",
    "officePhone": "(334)261-0438"
  },
  {
    "firstName": "Jeana",
    "lastName": "Ross",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 27,
    "partyAffiliation": "Republican",
    "residence": "Guntersville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jeana.ross@alhouse.gov",
    "officePhone": "(334)261-0539"
  },
  {
    "firstName": "Mack",
    "lastName": "Butler",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 28,
    "partyAffiliation": "Republican",
    "residence": "Rainbow City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mack.butler@alhouse.gov",
    "officePhone": "(334)261-0490"
  },
  {
    "firstName": "Mark",
    "lastName": "Gidley",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 29,
    "partyAffiliation": "Republican",
    "residence": "Gadsden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mark.gidley@alhouse.gov",
    "officePhone": "(334 261-0432"
  },
  {
    "firstName": "Craig",
    "lastName": "Lipscomb",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "Gadsden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "craig.lipscomb@alhouse.gov",
    "officePhone": "(334)261-0546"
  },
  {
    "firstName": "Troy",
    "lastName": "Stubbs",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 31,
    "partyAffiliation": "Republican",
    "residence": "Prattville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "troy.stubbs@alhouse.gov",
    "officePhone": "(334)261-0595"
  },
  {
    "firstName": "Barbara",
    "lastName": "Boyd",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 32,
    "partyAffiliation": "Dem",
    "residence": "Anniston",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "barbara.boyd@alhouse.gov",
    "officePhone": "(334)261-0592"
  },
  {
    "firstName": "Ben",
    "lastName": "Robbins",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 33,
    "partyAffiliation": "Republican",
    "residence": "Montgomery",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ben.robbins@alhouse.gov",
    "officePhone": "(334)261-0477"
  },
  {
    "firstName": "David",
    "lastName": "Standridge",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 34,
    "partyAffiliation": "Republican",
    "residence": "Oneonta",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "david.standridge@alhouse.gov",
    "officePhone": "(334)261-0446"
  },
  {
    "firstName": "Steve",
    "lastName": "Hurst",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 35,
    "partyAffiliation": "Republican",
    "residence": "Munford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "steve.hurst@alhouse.gov",
    "officePhone": "(334)261-0415"
  },
  {
    "firstName": "Randy",
    "lastName": "Wood",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 36,
    "partyAffiliation": "Republican",
    "residence": "Anniston",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "randy.wood@alhouse.gov",
    "officePhone": "(334)261-0552"
  },
  {
    "firstName": "Bob",
    "lastName": "Fincher",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 37,
    "partyAffiliation": "Republican",
    "residence": "Woodland",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "bob.fincher@alhouse.gov",
    "officePhone": "(334)261-0538"
  },
  {
    "firstName": "Debbie",
    "lastName": "Wood",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 38,
    "partyAffiliation": "Republican",
    "residence": "Valley",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "debbie.wood@alhouse.gov",
    "officePhone": "(334)261-0532"
  },
  {
    "firstName": "Ginny",
    "lastName": "Shaver",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 39,
    "partyAffiliation": "Republican",
    "residence": "Leesburg",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ginny.shaver@alhouse.gov",
    "officePhone": "(334)261-0413"
  },
  {
    "firstName": "Chad",
    "lastName": "Robertson",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 40,
    "partyAffiliation": "Republican",
    "residence": "Heflin",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chad.robertson@alhouse.gov",
    "officePhone": "(334)261-0496"
  },
  {
    "firstName": "Corley",
    "lastName": "Ellis",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 41,
    "partyAffiliation": "Republican",
    "residence": "Columbiana",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "corley.ellis@alhouse.gov",
    "officePhone": "(334)261-0560"
  },
  {
    "firstName": "Ivan",
    "lastName": "Smith",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 42,
    "partyAffiliation": "Republican",
    "residence": "Clanton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ivan.smith@alhouse.gov",
    "officePhone": "(334)261-0459"
  },
  {
    "firstName": "Arnold",
    "lastName": "Mooney",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 43,
    "partyAffiliation": "Republican",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "arnold.mooney@alhouse.gov",
    "officePhone": "(334)261-9512"
  },
  {
    "firstName": "Danny",
    "lastName": "Garrett",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 44,
    "partyAffiliation": "Republican",
    "residence": "Trussville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "danny.garrett@alhouse.gov",
    "officePhone": "(334)261-0524"
  },
  {
    "firstName": "Susan",
    "lastName": "DuBose",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 45,
    "partyAffiliation": "Republican",
    "residence": "Hoover",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "susan.dubose@alhouse.gov",
    "officePhone": "(334)261-0527"
  },
  {
    "firstName": "David",
    "lastName": "Faulkner",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 46,
    "partyAffiliation": "Republican",
    "residence": "Homewood",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "david.faulkner@alhouse.gov",
    "officePhone": "(334)261-0442"
  },
  {
    "firstName": "Mike",
    "lastName": "Shaw",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 47,
    "partyAffiliation": "Republican",
    "residence": "Hoover",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mike.shaw@alhouse.gov",
    "officePhone": "(334)261-0439"
  },
  {
    "firstName": "Jim",
    "lastName": "Carns",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 48,
    "partyAffiliation": "Republican",
    "residence": "Vestavia Hills",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jim.carns@alhouse.gov",
    "officePhone": "(334)261-0429"
  },
  {
    "firstName": "Russell",
    "lastName": "Bedsole",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 49,
    "partyAffiliation": "Republican",
    "residence": "Alabaster",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "russell.bedsole@alhouse.gov",
    "officePhone": "(334)261-0491"
  },
  {
    "firstName": "Jim",
    "lastName": "Hill",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 50,
    "partyAffiliation": "Republican",
    "residence": "Odenville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jim.hill@alhouse.gov",
    "officePhone": "(334)261-0494"
  },
  {
    "firstName": "Allen",
    "lastName": "Treadaway",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 51,
    "partyAffiliation": "Republican",
    "residence": "Morris",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "allen.treadaway@alhouse.gov",
    "officePhone": "(334)261-0585"
  },
  {
    "firstName": "Kelvin",
    "lastName": "Datcher",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 52,
    "partyAffiliation": "Democrat",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kelvin.datcher@alhouse.gov",
    "officePhone": "(334)261-0387"
  },
  {
    "firstName": "Anthony",
    "lastName": "Daniels",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 53,
    "partyAffiliation": "Democrat",
    "residence": "Huntsville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "anthony.daniels@alhouse.gov",
    "officePhone": "(334)261-0522"
  },
  {
    "firstName": "Neil",
    "lastName": "Rafferty",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 54,
    "partyAffiliation": "Democrat",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "neil.rafferty@alhouse.gov",
    "officePhone": "(334)261-0543"
  },
  {
    "firstName": "Travis",
    "lastName": "Hendrix",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 55,
    "partyAffiliation": "Democrat",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "travis.hendrix@alhouse.gov",
    "officePhone": "(334)261-0452"
  },
  {
    "firstName": "Ontario",
    "lastName": "Tillman",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 56,
    "partyAffiliation": "Democrat",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ontario.tillman@alhouse.gov",
    "officePhone": "(334)261-0529"
  },
  {
    "firstName": "Patrick",
    "lastName": "Sellers",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 57,
    "partyAffiliation": "Democrat",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "patrick.sellers@alhouse.gov",
    "officePhone": "(334)261-0589"
  },
  {
    "firstName": "Rolanda",
    "lastName": "Hollis",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 58,
    "partyAffiliation": "Democrat",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rolanda.hollis@alhouse.gov",
    "officePhone": "(334)261-9520"
  },
  {
    "firstName": "Mary",
    "lastName": "Moore",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 59,
    "partyAffiliation": "Democrat",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mary.moore@alhouse.gov",
    "officePhone": "(334)261-0508"
  },
  {
    "firstName": "Juandalynn",
    "lastName": "Givan",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 60,
    "partyAffiliation": "Democrat",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "juandalynn.givan@alhouse.gov",
    "officePhone": "(334)261-0584"
  },
  {
    "firstName": "Ron",
    "lastName": "Bolton",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 61,
    "partyAffiliation": "Republican",
    "residence": "Northport",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ron.bolton@alhouse.gov",
    "officePhone": "(334)261-0403"
  },
  {
    "firstName": "Bill",
    "lastName": "Lamb",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 62,
    "partyAffiliation": "Republican",
    "residence": "Tuscaloosa",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "bill.lamb@alhouse.gov",
    "officePhone": "(334)261-0481"
  },
  {
    "firstName": "Cynthia",
    "lastName": "Almond",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 63,
    "partyAffiliation": "Republican",
    "residence": "Tuscaloosa",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "cynthia.almond@alhouse.gov",
    "officePhone": "(334)261-0558"
  },
  {
    "firstName": "Donna",
    "lastName": "Givens",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 64,
    "partyAffiliation": "Republican",
    "residence": "Loxley",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "donna.givens@alhouse.gov",
    "officePhone": "(334)261-0445"
  },
  {
    "firstName": "Brett",
    "lastName": "Easterbrook",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 65,
    "partyAffiliation": "Republican",
    "residence": "Fruitdale",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "brett.easterbrook@alhouse.gov",
    "officePhone": "(334)261-0402"
  },
  {
    "firstName": "Alan",
    "lastName": "Baker",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 66,
    "partyAffiliation": "Republican",
    "residence": "Brewton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "alan.baker@alhouse.gov",
    "officePhone": "(334)261-0420"
  },
  {
    "firstName": "Prince",
    "lastName": "Chestnut",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 67,
    "partyAffiliation": "Democrat",
    "residence": "Selma",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "prince.chestnut@alhouse.gov",
    "officePhone": "(334)261-0598"
  },
  {
    "firstName": "Thomas",
    "lastName": "Jackson",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 68,
    "partyAffiliation": "Democrat",
    "residence": "Thomasville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "thomas.jackson@alhouse.gov",
    "officePhone": "(334)261-0437"
  },
  {
    "firstName": "Kelvin",
    "lastName": "Lawrence",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 69,
    "partyAffiliation": "Democrat",
    "residence": "Hayneville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kelvin.lawrence@alhouse.gov",
    "officePhone": "(334)261-0536"
  },
  {
    "firstName": "Chris",
    "lastName": "England",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 70,
    "partyAffiliation": "Democrat",
    "residence": "Tuscaloosa",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chris.england@alhouse.gov",
    "officePhone": "(334)261-0503"
  },
  {
    "firstName": "A.J.",
    "lastName": "McCampbell",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 71,
    "partyAffiliation": "Democrat",
    "residence": "Demopolis",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "acmc1@bellsouth.net",
    "officePhone": "(334)261-0547"
  },
  {
    "firstName": "Curtis",
    "lastName": "Travis",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 72,
    "partyAffiliation": "Democrat",
    "residence": "Tuscaloosa",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "curtis.travis@alhouse.gov",
    "officePhone": "(334)261-0559"
  },
  {
    "firstName": "Kenneth",
    "lastName": "Paschal",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 73,
    "partyAffiliation": "Republican",
    "residence": "Pelham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kenneth.paschal@alhouse.gov",
    "officePhone": "(334)261-0469"
  },
  {
    "firstName": "Phillip",
    "lastName": "Ensler",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 74,
    "partyAffiliation": "Democrat",
    "residence": "Montgomery",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "phillip.ensler@alhouse.gov",
    "officePhone": "(334)261-0569"
  },
  {
    "firstName": "Reed",
    "lastName": "Ingram",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 75,
    "partyAffiliation": "Republican",
    "residence": "Mathews",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "reed.ingram@alhouse.gov",
    "officePhone": "(334)261-0507"
  },
  {
    "firstName": "Patrice",
    "lastName": "McClammy",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 76,
    "partyAffiliation": "Democrat",
    "residence": "Montgomery",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "patrice.mcclammy@alhouse.gov",
    "officePhone": "(334)261-0580"
  },
  {
    "firstName": "Tashina",
    "lastName": "Morris",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 77,
    "partyAffiliation": "Democrat",
    "residence": "Montgomery",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tashina.morris@alhouse.gov",
    "officePhone": "(334)261-0597"
  },
  {
    "firstName": "Kenyatt\u00e9",
    "lastName": "Hassell",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 78,
    "partyAffiliation": "Democrat",
    "residence": "Montgomery",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kenyatte.hassell@alhouse.gov",
    "officePhone": "(334)261-0506"
  },
  {
    "firstName": "Joe",
    "lastName": "Lovvorn",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 79,
    "partyAffiliation": "Republican",
    "residence": "Auburn",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "joe.lovvorn@alhouse.gov",
    "officePhone": "(334)261-0540"
  },
  {
    "firstName": "Chris",
    "lastName": "Blackshear",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 80,
    "partyAffiliation": "Republican",
    "residence": "Smiths Station",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chris.blackshear@alhouse.gov",
    "officePhone": "(334)261-0428"
  },
  {
    "firstName": "Ed",
    "lastName": "Oliver",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 81,
    "partyAffiliation": "Republican",
    "residence": "Alexander City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ed.oliver@alhouse.gov",
    "officePhone": "(334)261-0471"
  },
  {
    "firstName": "Pebblin",
    "lastName": "Warren",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 82,
    "partyAffiliation": "Democrat",
    "residence": "Tuskegee",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "pebblin.warren@alhouse.gov",
    "officePhone": "(334)261-0541"
  },
  {
    "firstName": "Jeremy",
    "lastName": "Gray",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 83,
    "partyAffiliation": "Democrat",
    "residence": "Opelika",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jeremy.gray@alhouse.gov",
    "officePhone": "(334)261-9505"
  },
  {
    "firstName": "Berry",
    "lastName": "Forte",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 84,
    "partyAffiliation": "Democrat",
    "residence": "Clayton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "berry.forte@alhouse.gov",
    "officePhone": "(334)261-0566"
  },
  {
    "firstName": "Rick",
    "lastName": "Rehm",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 85,
    "partyAffiliation": "Republican",
    "residence": "Dothan",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rick.rehm@alhouse.gov",
    "officePhone": "(334)261-0513"
  },
  {
    "firstName": "Paul",
    "lastName": "Lee",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 86,
    "partyAffiliation": "Republican",
    "residence": "Dothan",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "paul.lee@alhouse.gov",
    "officePhone": "(334)261-0488"
  },
  {
    "firstName": "Jeff",
    "lastName": "Sorrells",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 87,
    "partyAffiliation": "Republican",
    "residence": "Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jeff.sorrells@alhouse.gov",
    "officePhone": "(334)261-0542"
  },
  {
    "firstName": "Jerry",
    "lastName": "Starnes",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 88,
    "partyAffiliation": "Republican",
    "residence": "Prattville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jerry.starnes@alhouse.gov",
    "officePhone": "(334)261-0499"
  },
  {
    "firstName": "Marcus",
    "lastName": "Paramore",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 89,
    "partyAffiliation": "Republican",
    "residence": "Troy",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "marcus.paramore@alhouse.gov",
    "officePhone": "(334)261-0593"
  },
  {
    "firstName": "Chris",
    "lastName": "Sells",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 90,
    "partyAffiliation": "Republican",
    "residence": "Greenville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chris.sells@alhouse.gov",
    "officePhone": "(334)261-0568"
  },
  {
    "firstName": "Rhett",
    "lastName": "Marques",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 91,
    "partyAffiliation": "Republican",
    "residence": "Enterprise",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rhett.marques@alhouse.gov",
    "officePhone": "(334)261-0473"
  },
  {
    "firstName": "Matthew",
    "lastName": "Hammett",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 92,
    "partyAffiliation": "Republican",
    "residence": "Dozier",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "matthew.hammett@alhouse.gov",
    "officePhone": "(334)261-0421"
  },
  {
    "firstName": "Steve",
    "lastName": "Clouse",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 93,
    "partyAffiliation": "Republican",
    "residence": "Ozark",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "steve.clouse@alhouse.gov",
    "officePhone": "(334)261-0488"
  },
  {
    "firstName": "Jennifer",
    "lastName": "Fidler",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 94,
    "partyAffiliation": "Republican",
    "residence": "Fairhope",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jennifer.fidler@alhouse.gov",
    "officePhone": "(334)261-0409"
  },
  {
    "firstName": "Frances",
    "lastName": "Holk-Jones",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 95,
    "partyAffiliation": "Republican",
    "residence": "Foley",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "frances.holk-jones@alhouse.gov",
    "officePhone": "(334)261-0523"
  },
  {
    "firstName": "Matt",
    "lastName": "Simpson",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 96,
    "partyAffiliation": "Republican",
    "residence": "Daphne",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "matt.simpson@alhouse.gov",
    "officePhone": "(334)261-0424"
  },
  {
    "firstName": "Adline",
    "lastName": "Clarke",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 97,
    "partyAffiliation": "Democrat",
    "residence": "Mobile",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "adline.clarke@alhouse.gov",
    "officePhone": "(334)261-0549"
  },
  {
    "firstName": "Napoleon",
    "lastName": "Bracy",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 98,
    "partyAffiliation": "Democrat",
    "residence": "Saraland",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "napoleon.bracy@alhouse.gov",
    "officePhone": "(334)261-0556"
  },
  {
    "firstName": "Sam",
    "lastName": "Jones",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 99,
    "partyAffiliation": "Democrat",
    "residence": "Mobile",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "sam.jones@alhouse.gov",
    "officePhone": "(334)261-0963"
  },
  {
    "firstName": "Mark",
    "lastName": "Shirey",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 100,
    "partyAffiliation": "Republican",
    "residence": "Mobile",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mark.shirey@alhouse.gov",
    "officePhone": "(334)261-0563"
  },
  {
    "firstName": "Chris",
    "lastName": "Pringle",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 101,
    "partyAffiliation": "Republican",
    "residence": "Mobile",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chris.pringle@alhouse.gov",
    "officePhone": "(334)261-0489"
  },
  {
    "firstName": "Shane",
    "lastName": "Stringer",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 102,
    "partyAffiliation": "Republican",
    "residence": "Mobile",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "shane.stringer@alhouse.gov",
    "officePhone": "(334)261-0594"
  },
  {
    "firstName": "Barbara",
    "lastName": "Drummond",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 103,
    "partyAffiliation": "Democrat",
    "residence": "Mobile",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "barbara.drummond@alhouse.gov",
    "officePhone": "(334)261-0564"
  },
  {
    "firstName": "Margie",
    "lastName": "Wilcox",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 104,
    "partyAffiliation": "Republican",
    "residence": "Mobile",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "margie.wilcox@alhouse.gov",
    "officePhone": "(334)261-0577"
  },
  {
    "firstName": "Chip",
    "lastName": "Brown",
    "chamber": "House",
    "homeState": "Alabama",
    "district": 105,
    "partyAffiliation": "Republican",
    "residence": "Mobile",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chip.brown@alhouse.gov",
    "officePhone": "(334)261-0447"
  },
  {
    "firstName": "Tim",
    "lastName": "Melson",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "Florence",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tim.melson@alsenate.gov",
    "officePhone": "(334)261-0888"
  },
  {
    "firstName": "Tom",
    "lastName": "Butler",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 2,
    "partyAffiliation": "Republican",
    "residence": "Madison",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tom.butler@alsenate.gov",
    "officePhone": "(334)261-0884"
  },
  {
    "firstName": "Arthur",
    "lastName": "Orr",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 3,
    "partyAffiliation": "Republican",
    "residence": "Decatur",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "arthur.orr@alsenate.gov",
    "officePhone": "(334)261-0758"
  },
  {
    "firstName": "Garlan",
    "lastName": "Gudger",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "Cullman",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "garlan.gudger@alsenate.gov",
    "officePhone": "(334)261-0855"
  },
  {
    "firstName": "Vacant",
    "lastName": "Vacant",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 5,
    "partyAffiliation": "Vacant",
    "residence": "Vacant",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "Larry",
    "lastName": "Stutts",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 6,
    "partyAffiliation": "Republican",
    "residence": "Tuscumbia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "larry.stutts@alsenate.gov",
    "officePhone": "(334)261-0862"
  },
  {
    "firstName": "Sam",
    "lastName": "Givhan",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "Gurley",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "sam.givhan@alsenate.gov",
    "officePhone": "(334)261-0867"
  },
  {
    "firstName": "Steve",
    "lastName": "Livingston",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 8,
    "partyAffiliation": "Republican",
    "residence": "Scottsboro",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "steve.livingston@alsenate.gov",
    "officePhone": "(334)261-0858"
  },
  {
    "firstName": "Wes",
    "lastName": "Kitchens",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 9,
    "partyAffiliation": "Republican",
    "residence": "Arab",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "wes.kitchens@alsenate.gov",
    "officePhone": "(334)261-0876"
  },
  {
    "firstName": "Andrew",
    "lastName": "Jones",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 10,
    "partyAffiliation": "Republican",
    "residence": "Centre",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "andrew.jones@alsenate.gov",
    "officePhone": "(334)261-0857"
  },
  {
    "firstName": "Lance",
    "lastName": "Bell",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 11,
    "partyAffiliation": "Republican",
    "residence": "Pell City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lance.bell@alsenate.gov",
    "officePhone": "(334)261-0789"
  },
  {
    "firstName": "Keith",
    "lastName": "Kelley",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 12,
    "partyAffiliation": "Republican",
    "residence": "Anniston",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "keith.kelley@alsenate.gov",
    "officePhone": "(334)261-0846"
  },
  {
    "firstName": "Randy",
    "lastName": "Price",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 13,
    "partyAffiliation": "Republican",
    "residence": "Opelika",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "randy.price@alsenate.gov",
    "officePhone": "(334)261-0874"
  },
  {
    "firstName": "April",
    "lastName": "Weaver",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 14,
    "partyAffiliation": "Republican",
    "residence": "Alabaster",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "April.Weaver@alsenate.gov",
    "officePhone": "(334)261-0886"
  },
  {
    "firstName": "Dan",
    "lastName": "Roberts",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 15,
    "partyAffiliation": "Republican",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "dan.roberts@alsenate.gov",
    "officePhone": "(334)261-0851"
  },
  {
    "firstName": "Jabo",
    "lastName": "Waggoner",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 16,
    "partyAffiliation": "Republican",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jabo.waggoner@alsenate.gov",
    "officePhone": "(334)261-0892"
  },
  {
    "firstName": "Shay",
    "lastName": "Shelnutt",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 17,
    "partyAffiliation": "Republican",
    "residence": "Trussville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "shay.shelnutt@alsenate.gov",
    "officePhone": "(334)261-0794"
  },
  {
    "firstName": "Rodger",
    "lastName": "Smitherman",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 18,
    "partyAffiliation": "Democratic",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rodger.smitherman@alsenate.gov",
    "officePhone": "(334)261-0870"
  },
  {
    "firstName": "Merika",
    "lastName": "Coleman",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 19,
    "partyAffiliation": "Democratic",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "merika.coleman@alsenate.gov",
    "officePhone": "(334)261-0793"
  },
  {
    "firstName": "Linda",
    "lastName": "Coleman-Madison",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 20,
    "partyAffiliation": "Democratic",
    "residence": "Birmingham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "linda.coleman-madison@alsenate.gov",
    "officePhone": "(334)261-0864"
  },
  {
    "firstName": "Gerald",
    "lastName": "Allen",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 21,
    "partyAffiliation": "Republican",
    "residence": "Tuscaloosa",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "gerald.allen@alsenate.gov",
    "officePhone": "(334)261-0889"
  },
  {
    "firstName": "Greg",
    "lastName": "Albritton",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 22,
    "partyAffiliation": "Republican",
    "residence": "Range",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "greg.albritton@alsenate.gov",
    "officePhone": "(334)261-0843"
  },
  {
    "firstName": "Robert",
    "lastName": "Stewart",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 23,
    "partyAffiliation": "Democratic",
    "residence": "Selma",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "robert.stewart@alsenate.gov",
    "officePhone": "(334)261-0860"
  },
  {
    "firstName": "Bobby",
    "lastName": "Singleton",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 24,
    "partyAffiliation": "Democratic",
    "residence": "Greensboro",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "bobby.singleton@alsenate.gov",
    "officePhone": "(334)261-0335"
  },
  {
    "firstName": "Will",
    "lastName": "Barfoot",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 25,
    "partyAffiliation": "Republican",
    "residence": "Montgomery",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "will.barfoot@alsenate.gov",
    "officePhone": "(334)261-0895"
  },
  {
    "firstName": "Kirk",
    "lastName": "Hatcher",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 26,
    "partyAffiliation": "Democratic",
    "residence": "Montgomery",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kirk.hatcher@alsenate.gov",
    "officePhone": "(334)261-9001"
  },
  {
    "firstName": "Jay",
    "lastName": "Hovey",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 27,
    "partyAffiliation": "Republican",
    "residence": "Auburn",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jay.hovey@alsenate.gov",
    "officePhone": "(334)261-0865"
  },
  {
    "firstName": "Billy",
    "lastName": "Beasley",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 28,
    "partyAffiliation": "Democratic",
    "residence": "Clayton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "billy.beasley@alsenate.gov",
    "officePhone": "(334)261-0868"
  },
  {
    "firstName": "Donnie",
    "lastName": "Chesteen",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 29,
    "partyAffiliation": "Republican",
    "residence": "Geneva",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "donnie.chesteen@alsenate.gov",
    "officePhone": "(334)261-0879"
  },
  {
    "firstName": "Clyde",
    "lastName": "Chambliss",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "Prattville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "clyde.chambliss@alsenate.gov",
    "officePhone": "(334)261-0872"
  },
  {
    "firstName": "Josh",
    "lastName": "Carnley",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 31,
    "partyAffiliation": "Republican",
    "residence": "Ino",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "josh.carnley@alsenate.gov",
    "officePhone": "(334)261-0845"
  },
  {
    "firstName": "Chris",
    "lastName": "Elliott",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 32,
    "partyAffiliation": "Republican",
    "residence": "Spanish Fort",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chris.elliott@alsenate.gov",
    "officePhone": "(334)261-0897"
  },
  {
    "firstName": "Vivian",
    "lastName": "Figures",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 33,
    "partyAffiliation": "Democratic",
    "residence": "Mobile",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "vivian.figures@alsenate.gov",
    "officePhone": "(334)261-0871"
  },
  {
    "firstName": "Jack",
    "lastName": "Williams",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 34,
    "partyAffiliation": "Republican",
    "residence": "Wilmer",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jack.williams@alsenate.gov",
    "officePhone": "(334)261-0829"
  },
  {
    "firstName": "David",
    "lastName": "Sessions",
    "chamber": "Senate",
    "homeState": "Alabama",
    "district": 35,
    "partyAffiliation": "Republican",
    "residence": "Grand Bay",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "david.sessions@alsenate.gov",
    "officePhone": "(334)261-0882"
  }
];
