// Alaska legislators (complete) mapped to legislatorSchema
export default [
  {
    "firstName": "Bert",
    "lastName": "Stedman",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "Sitka",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Bert.Stedman@akleg.gov",
    "officePhone": "(907)465-3873"
  },
  {
    "firstName": "Jesse",
    "lastName": "Kiehl",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 2,
    "partyAffiliation": "Democrat",
    "residence": "Juneau",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Jesse.Kiehl@akleg.gov",
    "officePhone": "(907)465-4947"
  },
  {
    "firstName": "Gary",
    "lastName": "Stevens",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 3,
    "partyAffiliation": "Republican",
    "residence": "Kodiak",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Gary.Stevens@akleg.gov",
    "officePhone": "(907)465-4925"
  },
  {
    "firstName": "Jesse",
    "lastName": "Bjorkman",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "Nikiski",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Jesse.Bjorkman@akleg.gov",
    "officePhone": "(907)465-2828"
  },
  {
    "firstName": "Cathy",
    "lastName": "Giessel",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 5,
    "partyAffiliation": "Republican",
    "residence": "Anchorage",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(907)465-4843"
  },
  {
    "firstName": "James",
    "lastName": "Kaufman",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 6,
    "partyAffiliation": "Republican",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.James.Kaufman@akleg.gov",
    "officePhone": "(907)465-4949"
  },
  {
    "firstName": "Elvi",
    "lastName": "Gray-Jackson",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 7,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Elvi.Jackson-Gray@akleg.gov",
    "officePhone": "(907)465-4930"
  },
  {
    "firstName": "Matt",
    "lastName": "Claman",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Matt.Claman@akleg.gov",
    "officePhone": "(907)465-4919"
  },
  {
    "firstName": "Loki",
    "lastName": "Tobin",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Loki.Tobin@akleg.gov",
    "officePhone": "(907)465-3704"
  },
  {
    "firstName": "Forrest",
    "lastName": "Dunbar",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 10,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Forrest.Dunbar@akleg.gov",
    "officePhone": "(907)465-6944"
  },
  {
    "firstName": "Bill",
    "lastName": "Wielechowski",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 11,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Bill.Wielechowski@akleg.gov",
    "officePhone": "(907)465-2435"
  },
  {
    "firstName": "Kelly",
    "lastName": "Merrick",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 12,
    "partyAffiliation": "Republican",
    "residence": "Eagle River",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Kelly.Merrick@akleg.gov",
    "officePhone": "(907)465-3777"
  },
  {
    "firstName": "Shelley",
    "lastName": "Highes",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 13,
    "partyAffiliation": "Republican",
    "residence": "Palmer",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Shelley.Hughes@akleg.gov",
    "officePhone": "(907)465-3743"
  },
  {
    "firstName": "Robert",
    "lastName": "Yundt",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 14,
    "partyAffiliation": "Republican",
    "residence": "Wasilla",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Robert.Yundt@akleg.gov",
    "officePhone": "(907)465-3878"
  },
  {
    "firstName": "Mike",
    "lastName": "Shower",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 15,
    "partyAffiliation": "Republican",
    "residence": "Wasilla",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Mike.Shower@akleg.gov",
    "officePhone": "(907)465-6600"
  },
  {
    "firstName": "Scott",
    "lastName": "Kawasaki",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 16,
    "partyAffiliation": "Democrat",
    "residence": "Fairbanks",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Scott.Kawasaki@akleg.gov",
    "officePhone": "(907)465-3466"
  },
  {
    "firstName": "Robert",
    "lastName": "Myers",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 17,
    "partyAffiliation": "Republican",
    "residence": "North Pole",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Robert.Myers@akleg.gov",
    "officePhone": "(907)465-3719"
  },
  {
    "firstName": "Mike",
    "lastName": "Cronk",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 18,
    "partyAffiliation": "Republican",
    "residence": "Tok/Northway",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Mike.Cronk@akleg.gov",
    "officePhone": "(907)465-4527"
  },
  {
    "firstName": "Lyman",
    "lastName": "Hoffman",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 19,
    "partyAffiliation": "Democrat",
    "residence": "Bethel",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Lyman.Hoffman@akleg.gov",
    "officePhone": "(907)465-4453"
  },
  {
    "firstName": "Donny",
    "lastName": "Olson",
    "chamber": "Senate",
    "homeState": "Alaska",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "Golovin",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Donald.Olson@akleg.gov",
    "officePhone": "(907)465-3707"
  },
  {
    "firstName": "Jeremy",
    "lastName": "Bynmum",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "Ketchikan",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Jeremy.Bynum@akleg.gov",
    "officePhone": "(907)465-3824"
  },
  {
    "firstName": "Rebecca",
    "lastName": "Himschoot",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 2,
    "partyAffiliation": "Independent",
    "residence": "Sitka",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Rebecca.Himschoot@akleg.gov",
    "officePhone": ""
  },
  {
    "firstName": "Andi",
    "lastName": "Story",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 3,
    "partyAffiliation": "Democrat",
    "residence": "Juneau",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Andi.Story@akleg.gov",
    "officePhone": "(907)465-3744"
  },
  {
    "firstName": "Sara",
    "lastName": "Hannan",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 4,
    "partyAffiliation": "Democrat",
    "residence": "Juneau",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Sara.Hannan@akleg.gov",
    "officePhone": "(907)465-4766"
  },
  {
    "firstName": "Louise",
    "lastName": "Stutes",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 5,
    "partyAffiliation": "Republican",
    "residence": "Kodiak",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Louise.Stutes@akleg.gov",
    "officePhone": "(907)465-2487"
  },
  {
    "firstName": "Sarah",
    "lastName": "Vance",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 6,
    "partyAffiliation": "Republican",
    "residence": "Homer",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(907)465-2689"
  },
  {
    "firstName": "Justin",
    "lastName": "Ruffridge",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "Soldotna",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(907)465-2693"
  },
  {
    "firstName": "Bill",
    "lastName": "Elam",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 8,
    "partyAffiliation": "Republican",
    "residence": "Nikiski",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(907)465-3779"
  },
  {
    "firstName": "Ky",
    "lastName": "Holland",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 9,
    "partyAffiliation": "Independent",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(907)465-4945"
  },
  {
    "firstName": "Chuck",
    "lastName": "Kopp",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 10,
    "partyAffiliation": "Republican",
    "residence": "Anchorage",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(907)465-3892"
  },
  {
    "firstName": "Julie",
    "lastName": "Coulombe",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 11,
    "partyAffiliation": "Republican",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(907)465-3879"
  },
  {
    "firstName": "Calvin",
    "lastName": "Schrage",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 12,
    "partyAffiliation": "Independent",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(907)465-4931"
  },
  {
    "firstName": "Andy",
    "lastName": "Josephson",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 13,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Andy.Josephson@akleg.gov",
    "officePhone": "(907)465-4939"
  },
  {
    "firstName": "Alyse",
    "lastName": "Galvin",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 14,
    "partyAffiliation": "Independent",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Alyse.Galvin@akleg.gov",
    "officePhone": "(907)465-3875"
  },
  {
    "firstName": "Mia",
    "lastName": "Costello",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 15,
    "partyAffiliation": "Republican",
    "residence": "Anchorage",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Mia.Costello@akleg.gov",
    "officePhone": "(907)465-4993"
  },
  {
    "firstName": "Carolyn",
    "lastName": "Hall",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 16,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Carolyn.Hall@akleg.gov",
    "officePhone": "(907)465-4968"
  },
  {
    "firstName": "Zack",
    "lastName": "Fields",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 17,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Zack.Fields@akleg.gov",
    "officePhone": "((907)465-2647"
  },
  {
    "firstName": "David",
    "lastName": "Nelson",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 18,
    "partyAffiliation": "Republican",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.David.Nelson@akleg.gov",
    "officePhone": "(907)465-4998"
  },
  {
    "firstName": "Genevieve",
    "lastName": "Mina",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 19,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Genevieve.Mina@akleg.gov",
    "officePhone": "(907)465-3424"
  },
  {
    "firstName": "Andrew",
    "lastName": "Gray",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Andrew.Gray@akleg.gov",
    "officePhone": "(907)465-4940"
  },
  {
    "firstName": "Donna",
    "lastName": "Mears",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 21,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Donna.Mears@akleg.gov",
    "officePhone": "(907)465-3438"
  },
  {
    "firstName": "Ted",
    "lastName": "Eischeid",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 22,
    "partyAffiliation": "Democrat",
    "residence": "Anchorage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Ted.Eischeid@akleg.gov",
    "officePhone": "(907)465-2095"
  },
  {
    "firstName": "Jamie",
    "lastName": "Allard",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 23,
    "partyAffiliation": "Republican",
    "residence": "Eagle River",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Jamie.Allard@akleg.gov",
    "officePhone": "(907)465-2995"
  },
  {
    "firstName": "Dan",
    "lastName": "Saddler",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 24,
    "partyAffiliation": "Republican",
    "residence": "Eagle River",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Dan.Saddler@akleg.gov",
    "officePhone": "(907)465-3783"
  },
  {
    "firstName": "Delena",
    "lastName": "Johnson",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 25,
    "partyAffiliation": "Republican",
    "residence": "Palmer",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Delena.Johnson@akleg.gov",
    "officePhone": "(907)465-4958"
  },
  {
    "firstName": "Cathy",
    "lastName": "Tilton",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 26,
    "partyAffiliation": "Republican",
    "residence": "Wasilla",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Cathy.Tilton@akleg.gov",
    "officePhone": "(907)465-2199"
  },
  {
    "firstName": "Jubilee",
    "lastName": "Underwood",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 27,
    "partyAffiliation": "Republican",
    "residence": "Wasilla",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Jubilee.Underwood@akleg.gov",
    "officePhone": "(907)465-2186"
  },
  {
    "firstName": "Elexie",
    "lastName": "Moore",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 28,
    "partyAffiliation": "Republican",
    "residence": "Wasilla",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Elexie.Moore@akleg.gov",
    "officePhone": "(907)465-4833"
  },
  {
    "firstName": "George",
    "lastName": "Rauscher",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 29,
    "partyAffiliation": "Republican",
    "residence": "Sutton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.George.Rauscher@akleg.gov",
    "officePhone": "(907)465-4859"
  },
  {
    "firstName": "Kevin",
    "lastName": "McCabe",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "Big Lake",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Kevin.McCabe@akleg.gov",
    "officePhone": "(907)465-2679"
  },
  {
    "firstName": "Maxine",
    "lastName": "Dibert",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 31,
    "partyAffiliation": "Democrat",
    "residence": "Fairbanks",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Maxine.Dibert@akleg.gov",
    "officePhone": "(907)465-2138"
  },
  {
    "firstName": "Will",
    "lastName": "Stapp",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 32,
    "partyAffiliation": "Republican",
    "residence": "Fairbanks",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Will.Stapp@akleg.gov",
    "officePhone": "(907)465-3004"
  },
  {
    "firstName": "Mike",
    "lastName": "Prax",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 33,
    "partyAffiliation": "Republican",
    "residence": "North Pole",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Mike.Prax@akleg.gov",
    "officePhone": "(907)465-4797"
  },
  {
    "firstName": "Frank",
    "lastName": "Tomaszewski",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 34,
    "partyAffiliation": "Republican",
    "residence": "Fairbanks",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Frank.Tomaszewski@akleg.gov",
    "officePhone": "(907)465-4457"
  },
  {
    "firstName": "Ashley",
    "lastName": "Carrick",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 35,
    "partyAffiliation": "Democrat",
    "residence": "Fairbanks",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Ashley.Carrick@akleg.gov",
    "officePhone": "(907)465-4976"
  },
  {
    "firstName": "Rebecca",
    "lastName": "Schwanke",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 36,
    "partyAffiliation": "Republican",
    "residence": "Glennallen",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Rebecca.Schwanke@akleg.gov",
    "officePhone": "(907)465-2327"
  },
  {
    "firstName": "Bryce",
    "lastName": "Edgmon",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 37,
    "partyAffiliation": "Independent",
    "residence": "Dillingham",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Bryce.Edgmon@akleg.gov",
    "officePhone": "(907)465-4451"
  },
  {
    "firstName": "Nellie",
    "lastName": "Unangiq Jimmie",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 38,
    "partyAffiliation": "Democrat",
    "residence": "Toksook Bay",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Nellie.Jimmie@akleg.gov",
    "officePhone": "(907)465-4942"
  },
  {
    "firstName": "Neal",
    "lastName": "Foster",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 39,
    "partyAffiliation": "Democrat",
    "residence": "Nome",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Neal.Foster@akleg.gov",
    "officePhone": "(907)465-3789"
  },
  {
    "firstName": "Robyn",
    "lastName": "Niayuq Burke",
    "chamber": "House",
    "homeState": "Alaska",
    "district": 40,
    "partyAffiliation": "Democrat",
    "residence": "Utqiagvik",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Representative.Robyn.Burke@akleg.gov",
    "officePhone": "(907)465-3473"
  }
];
