// Arizona legislators mapped to legislatorSchema
export default [
  {
    "firstName": "Selina",
    "lastName": "Bliss",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "SBliss@AZLeg.gov",
    "officePhone": "(602)926-4018"
  },
  {
    "firstName": "Quang",
    "lastName": "Nguyen",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "QNguyen@AZLeg.gov",
    "officePhone": "(602)926-3258"
  },
  {
    "firstName": "Stephanie",
    "lastName": "Simacek",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 2,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "SSimacek@AZLeg.gov",
    "officePhone": "(602)926-3083"
  },
  {
    "firstName": "Justin",
    "lastName": "Wilmeth",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 2,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JWilmeth@AZLeg.gov",
    "officePhone": "(602) 926-5044"
  },
  {
    "firstName": "Joseph",
    "lastName": "Chaplik",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 3,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JChaplik@AZLeg.gov",
    "officePhone": "(602) 926-3436"
  },
  {
    "firstName": "Alexander",
    "lastName": "Kolodin",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 3,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "AKolodin@AZLeg.gov",
    "officePhone": "(602) 926-3560"
  },
  {
    "firstName": "Pamela",
    "lastName": "Carter",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "PCarter@AZLeg.gov",
    "officePhone": "(602) 926-3153"
  },
  {
    "firstName": "Matt",
    "lastName": "Gress",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "MGress@AZLeg.gov",
    "officePhone": "(602) 926-4105"
  },
  {
    "firstName": "Sarah",
    "lastName": "Liguori",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 5,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "SLiguori@AZLeg.gov",
    "officePhone": "(602) 926-3264"
  },
  {
    "firstName": "Aaron",
    "lastName": "M\u00e1rquez",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 5,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "AM\u00e1rquez@AZLeg.gov",
    "officePhone": "(602) 926-3179"
  },
  {
    "firstName": "Mae",
    "lastName": "Peshlakai",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 6,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "MPeshlakai@AZLeg.gov",
    "officePhone": "(602) 926-3708"
  },
  {
    "firstName": "Myron",
    "lastName": "Tsosie",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 6,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "MTsosie@AZLeg.gov",
    "officePhone": "(602) 926-3157"
  },
  {
    "firstName": "Walt",
    "lastName": "Blackman",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "WBlackman@AZLeg.gov",
    "officePhone": "(602) 926-3244"
  },
  {
    "firstName": "David",
    "lastName": "Marshall,",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "DMarshall,@AZLeg.gov",
    "officePhone": "(602) 926-3579"
  },
  {
    "firstName": "Janeen",
    "lastName": "Connolly",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JConnolly@AZLeg.gov",
    "officePhone": "(602) 926-3300"
  },
  {
    "firstName": "Brian",
    "lastName": "Garcia",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "BGarcia@AZLeg.gov",
    "officePhone": "(602) 926-3329"
  },
  {
    "firstName": "Lorena",
    "lastName": "Austin",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "LAustin@AZLeg.gov",
    "officePhone": "(602) 926-3968"
  },
  {
    "firstName": "Seth",
    "lastName": "Blattman",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "SBlattman@AZLeg.gov",
    "officePhone": "(602) 926-3996"
  },
  {
    "firstName": "Ralph",
    "lastName": "Heap",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 10,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "RHeap@AZLeg.gov",
    "officePhone": "(602) 926-3381"
  },
  {
    "firstName": "Justin",
    "lastName": "Olson",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 10,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JOlson@AZLeg.gov",
    "officePhone": "(602) 926-3376"
  },
  {
    "firstName": "Junelle",
    "lastName": "Cavero",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 11,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JCavero@AZLeg.gov",
    "officePhone": "(602) 926-3285"
  },
  {
    "firstName": "Oscar",
    "lastName": "De Los Santos",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 11,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ODe Los Santos@AZLeg.gov",
    "officePhone": "(602) 926-4098"
  },
  {
    "firstName": "Patty",
    "lastName": "Contreras",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 12,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "PContreras@AZLeg.gov",
    "officePhone": "(602) 926-4057"
  },
  {
    "firstName": "Stacey",
    "lastName": "Travers",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 12,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "STravers@AZLeg.gov",
    "officePhone": "(602) 926-3917"
  },
  {
    "firstName": "Jeff",
    "lastName": "Weninger",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 13,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JWeninger@AZLeg.gov",
    "officePhone": "(602) 926-3392"
  },
  {
    "firstName": "Julie",
    "lastName": "Willoughby",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 13,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JWilloughby@AZLeg.gov",
    "officePhone": "(602) 926-4153"
  },
  {
    "firstName": "Laurin",
    "lastName": "Hendrix",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 14,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "LHendrix@AZLeg.gov",
    "officePhone": "(602) 926-4209"
  },
  {
    "firstName": "Khyl",
    "lastName": "Powell",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 14,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "KPowell@AZLeg.gov",
    "officePhone": "(602) 926-3415"
  },
  {
    "firstName": "Neal",
    "lastName": "Carter",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 15,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "NCarter@AZLeg.gov",
    "officePhone": "(602) 926-5761"
  },
  {
    "firstName": "Michael",
    "lastName": "Way",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 15,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "MWay@AZLeg.gov",
    "officePhone": "(602) 926-3433"
  },
  {
    "firstName": "Chris",
    "lastName": "Lopez",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 16,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "CLopez@AZLeg.gov",
    "officePhone": "(602) 926-3445"
  },
  {
    "firstName": "Teresa",
    "lastName": "Martinez",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 16,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "TMartinez@AZLeg.gov",
    "officePhone": "(602) 926-3158"
  },
  {
    "firstName": "Rachel",
    "lastName": "Keshel",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 17,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "RKeshel@AZLeg.gov",
    "officePhone": "(602) 926-3558"
  },
  {
    "firstName": "Kevin",
    "lastName": "Volk",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 17,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "KVolk@AZLeg.gov",
    "officePhone": "(602) 926-3498"
  },
  {
    "firstName": "Nancy",
    "lastName": "Gutierrez",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 18,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "NGutierrez@AZLeg.gov",
    "officePhone": "(602) 926-4134"
  },
  {
    "firstName": "Christopher",
    "lastName": "Mathis",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 18,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "CMathis@AZLeg.gov",
    "officePhone": "(602) 926-3138"
  },
  {
    "firstName": "Lupe",
    "lastName": "Diaz",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 19,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "LDiaz@AZLeg.gov",
    "officePhone": "(602) 926-4852"
  },
  {
    "firstName": "Gail",
    "lastName": "Griffin",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 19,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "GGriffin@AZLeg.gov",
    "officePhone": "(602) 926-5895"
  },
  {
    "firstName": "Alma",
    "lastName": "Hernandez",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "AHernandez@AZLeg.gov",
    "officePhone": "(602) 926-3136"
  },
  {
    "firstName": "Betty",
    "lastName": "Villegas",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "BVillegas@AZLeg.gov",
    "officePhone": "(602) 926-3027"
  },
  {
    "firstName": "Stephanie",
    "lastName": "Hamilton",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 21,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "SHamilton@AZLeg.gov",
    "officePhone": "(602) 926-3279"
  },
  {
    "firstName": "Consuelo",
    "lastName": "Hernandez",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 21,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "CHernandez@AZLeg.gov",
    "officePhone": "(602) 926-3523"
  },
  {
    "firstName": "Lupe",
    "lastName": "Contreras",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 22,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "LContreras@AZLeg.gov",
    "officePhone": "(602) 926-5284"
  },
  {
    "firstName": "Elda",
    "lastName": "Luna-N\u00e1jera",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 22,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ELuna-N\u00e1jera@AZLeg.gov",
    "officePhone": "(602) 926-3881"
  },
  {
    "firstName": "Michele",
    "lastName": "Pe\u00f1a",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 23,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "MPe\u00f1a@AZLeg.gov",
    "officePhone": "(602) 926-3696"
  },
  {
    "firstName": "Mariana",
    "lastName": "Sandoval",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 23,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "MSandoval@AZLeg.gov",
    "officePhone": "(602) 926-3740"
  },
  {
    "firstName": "Anna",
    "lastName": "Abeytia",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 24,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "AAbeytia@AZLeg.gov",
    "officePhone": "(602) 926-3501"
  },
  {
    "firstName": "Lydia",
    "lastName": "Hernandez",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 24,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "LHernandez@AZLeg.gov",
    "officePhone": "(602) 926-3553"
  },
  {
    "firstName": "Michael",
    "lastName": "Carbone",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 25,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "MCarbone@AZLeg.gov",
    "officePhone": "(602) 926-4038"
  },
  {
    "firstName": "Nick",
    "lastName": "Kupper",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 25,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "NKupper@AZLeg.gov",
    "officePhone": "(602) 926-3512"
  },
  {
    "firstName": "Cesar",
    "lastName": "Aguilar",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 26,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "CAguilar@AZLeg.gov",
    "officePhone": "(602) 926-3953"
  },
  {
    "firstName": "Quant\u00e1",
    "lastName": "Crews",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 26,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "QCrews@AZLeg.gov",
    "officePhone": "(602) 926-3256"
  },
  {
    "firstName": "Lisa",
    "lastName": "Fink",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 27,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "LFink@AZLeg.gov",
    "officePhone": "(602) 926-3516"
  },
  {
    "firstName": "Tony",
    "lastName": "Rivero",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 27,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "TRivero@AZLeg.gov",
    "officePhone": "(602) 926-3528"
  },
  {
    "firstName": "David",
    "lastName": "Livingston",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 28,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "DLivingston@AZLeg.gov",
    "officePhone": "(602) 926-4178"
  },
  {
    "firstName": "Beverly",
    "lastName": "Pingerelli",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 28,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "BPingerelli@AZLeg.gov",
    "officePhone": "(602) 926-3396"
  },
  {
    "firstName": "Steve",
    "lastName": "Montenegro",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 29,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "SMontenegro@AZLeg.gov",
    "officePhone": "(602) 926-3635"
  },
  {
    "firstName": "James",
    "lastName": "Taylor",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 29,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JTaylor@AZLeg.gov",
    "officePhone": "(602) 926-3564"
  },
  {
    "firstName": "Leo",
    "lastName": "Biasiucci",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "LBiasiucci@AZLeg.gov",
    "officePhone": "(602) 926-3018"
  },
  {
    "firstName": "John",
    "lastName": "Gillette",
    "chamber": "House",
    "homeState": "Arizona",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JGillette@AZLeg.gov",
    "officePhone": "(602) 926-4100"
  },
  {
    "firstName": "Mark",
    "lastName": "Finchem",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "MFinchem@AZLeg.gov",
    "officePhone": "(602) 926-3631"
  },
  {
    "firstName": "Shawnna",
    "lastName": "Bolick",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 2,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "SBolick@AZLeg.gov",
    "officePhone": "(602) 926-3314"
  },
  {
    "firstName": "John",
    "lastName": "Kavanagh",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 3,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JKavanagh@AZLeg.gov",
    "officePhone": "(602) 926-5170"
  },
  {
    "firstName": "Carine",
    "lastName": "Werner",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "CWerner@AZLeg.gov",
    "officePhone": "(602) 926-3673"
  },
  {
    "firstName": "Lela",
    "lastName": "Alston",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 5,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "LAlston@AZLeg.gov",
    "officePhone": "(602) 926-5829"
  },
  {
    "firstName": "Theresa",
    "lastName": "Hatathlie",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 6,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "THatathlie@AZLeg.gov",
    "officePhone": "(602) 926-5160"
  },
  {
    "firstName": "Wendy",
    "lastName": "Rogers",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "WRogers@AZLeg.gov",
    "officePhone": "(602) 926-3042"
  },
  {
    "firstName": "Lauren",
    "lastName": "Kuby",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "LKuby@AZLeg.gov",
    "officePhone": "(602) 926-4124"
  },
  {
    "firstName": "Eva",
    "lastName": "Burch",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "EBurch@AZLeg.gov",
    "officePhone": ""
  },
  {
    "firstName": "Kiana",
    "lastName": "Sears",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "KSears@AZLeg.gov",
    "officePhone": "(602) 926-3374"
  },
  {
    "firstName": "David",
    "lastName": "Farnsworth",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 10,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "DFarnsworth@AZLeg.gov",
    "officePhone": "(602) 926-3387"
  },
  {
    "firstName": "Catherine",
    "lastName": "Miranda",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 11,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "CMiranda@AZLeg.gov",
    "officePhone": "(602) 926-3413"
  },
  {
    "firstName": "Mitzi",
    "lastName": "Epstein",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 12,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "MEpstein@AZLeg.gov",
    "officePhone": "(602) 926-4870"
  },
  {
    "firstName": "J.D.",
    "lastName": "Mesnard",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 13,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JMesnard@AZLeg.gov",
    "officePhone": "(602) 926-4481"
  },
  {
    "firstName": "Warren",
    "lastName": "Petersen",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 14,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "WPetersen@AZLeg.gov",
    "officePhone": "(602) 926-4136"
  },
  {
    "firstName": "Jake",
    "lastName": "Hoffman",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 15,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JHoffman@AZLeg.gov",
    "officePhone": "(602) 926-3292"
  },
  {
    "firstName": "T.J.",
    "lastName": "Shope",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 16,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "TShope@AZLeg.gov",
    "officePhone": "(602) 926-3012"
  },
  {
    "firstName": "Vince",
    "lastName": "Leach",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 17,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "VLeach@AZLeg.gov",
    "officePhone": "(602) 926-3694"
  },
  {
    "firstName": "Priya",
    "lastName": "Sundareshan",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 18,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "PSundareshan@AZLeg.gov",
    "officePhone": "(602) 926-3437"
  },
  {
    "firstName": "David",
    "lastName": "Gowan",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 19,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "DGowan@AZLeg.gov",
    "officePhone": "(602) 926-5154"
  },
  {
    "firstName": "Sally Ann",
    "lastName": "Gonzales",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "SGonzales@AZLeg.gov",
    "officePhone": "(602) 926-3278"
  },
  {
    "firstName": "Rosanna",
    "lastName": "Gabald\u00f3n",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 21,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "RGabald\u00f3n@AZLeg.gov",
    "officePhone": "(602) 926-3424"
  },
  {
    "firstName": "Eva",
    "lastName": "Diaz",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 22,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "EDiaz@AZLeg.gov",
    "officePhone": "(602) 926-3473"
  },
  {
    "firstName": "Brian",
    "lastName": "Fernandez",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 23,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "BFernandez@AZLeg.gov",
    "officePhone": "(602) 926-3098"
  },
  {
    "firstName": "Analise",
    "lastName": "Ortiz",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 24,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "AOrtiz@AZLeg.gov",
    "officePhone": "(602) 926-3633"
  },
  {
    "firstName": "Tim",
    "lastName": "Dunn",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 25,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "TDunn@AZLeg.gov",
    "officePhone": "(602) 926-4139"
  },
  {
    "firstName": "Flavio",
    "lastName": "Bravo",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 26,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "FBravo@AZLeg.gov",
    "officePhone": "(602) 926-4033"
  },
  {
    "firstName": "Kevin",
    "lastName": "Payne",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 27,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "KPayne@AZLeg.gov",
    "officePhone": "(602) 926-4854"
  },
  {
    "firstName": "Frank",
    "lastName": "Carroll",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 28,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "FCarroll@AZLeg.gov",
    "officePhone": "(602) 926-3249"
  },
  {
    "firstName": "Janae",
    "lastName": "Shamp",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 29,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "JShamp@AZLeg.gov",
    "officePhone": "(602) 926-3499"
  },
  {
    "firstName": "Hildy",
    "lastName": "Angius",
    "chamber": "Senate",
    "homeState": "Arizona",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "HAngius@AZLeg.gov",
    "officePhone": "(602) 926-5051"
  }
];
