// Arkansas legislators mapped to legislatorSchema
export default [
  {
    "firstName": "Ben",
    "lastName": "Gilmore",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "Crossett",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ben.gilmore@senate.ar.gov",
    "officePhone": "(501)467-5952"
  },
  {
    "firstName": "Matt",
    "lastName": "Stone",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 2,
    "partyAffiliation": "Republican",
    "residence": "Camden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "matt.stone@senate.ar.gov",
    "officePhone": "(870)818-0750"
  },
  {
    "firstName": "Steve",
    "lastName": "Crowell",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 3,
    "partyAffiliation": "Republican",
    "residence": "Magnolia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "steve.crowell@senate.ar.gov",
    "officePhone": "(870)557-3440"
  },
  {
    "firstName": "Jimmy",
    "lastName": "Hickey",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "Taxarkana",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jimmy.hickey@senate.ar.gov",
    "officePhone": "(870)772-4444"
  },
  {
    "firstName": "Terry",
    "lastName": "Rice",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 5,
    "partyAffiliation": "Republican",
    "residence": "Waldron",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Terry.Rice@senate.ar.gov",
    "officePhone": "(479)637-3100"
  },
  {
    "firstName": "Matt",
    "lastName": "McKee",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 6,
    "partyAffiliation": "Republican",
    "residence": "Pearcy",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Matt.mckee@senate.ar.gov",
    "officePhone": "(501)622-0860"
  },
  {
    "firstName": "Alan",
    "lastName": "Clark",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "Lonsdale",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "alan.clark@senate.ar.gov",
    "officePhone": "(501)844-6800"
  },
  {
    "firstName": "Stephanie",
    "lastName": "Flowers",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "Pine Bluff",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Stephanie.Flowers@senate.ar.gov",
    "officePhone": "(501)682-7664"
  },
  {
    "firstName": "Reginald",
    "lastName": "Murdock",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "Marianna",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rkm_72360@yahoo.com",
    "officePhone": "(501)940-5157"
  },
  {
    "firstName": "Ronald",
    "lastName": "Caldwell",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 10,
    "partyAffiliation": "Republican",
    "residence": "Wynne",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ronald.caldwell@Senate.ar.gov",
    "officePhone": "(501)682-6107"
  },
  {
    "firstName": "Ricky",
    "lastName": "Hill",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 11,
    "partyAffiliation": "Republican",
    "residence": "Cabot",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Ricky.Hill@Senate.ar.gov",
    "officePhone": "(501)286-2285"
  },
  {
    "firstName": "Jamie",
    "lastName": "Scott",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 12,
    "partyAffiliation": "Democrat",
    "residence": "North Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jamie.scott@senate.ar.gov",
    "officePhone": "(501)398-2961"
  },
  {
    "firstName": "Jane",
    "lastName": "English",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 13,
    "partyAffiliation": "Republican",
    "residence": "North Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jane.english@senate.ar.gov",
    "officePhone": "(501)257-7670"
  },
  {
    "firstName": "Clarke",
    "lastName": "Tucker",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 14,
    "partyAffiliation": "Democrat",
    "residence": "Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "clarke.tucker@senate.ar.gov",
    "officePhone": "(501)246-4933"
  },
  {
    "firstName": "Fredrick",
    "lastName": "Love",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 15,
    "partyAffiliation": "Democrat",
    "residence": "Mabelvale",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "fred.love@senate.ar.gov",
    "officePhone": "(501)612-3939"
  },
  {
    "firstName": "Kim",
    "lastName": "Hammer",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 16,
    "partyAffiliation": "Republican",
    "residence": "Benton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kim.hammer@senate.ar.gov",
    "officePhone": "(501)840-3841"
  },
  {
    "firstName": "Mark",
    "lastName": "Johnson",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 17,
    "partyAffiliation": "Republican",
    "residence": "Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mark.johnson@senate.ar.gov",
    "officePhone": "(501)682-2920"
  },
  {
    "firstName": "Jonathan",
    "lastName": "Dismang",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 18,
    "partyAffiliation": "Republican",
    "residence": "Beebe",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jonathan.dismang@senate.ar.gov",
    "officePhone": "(501)682-6107"
  },
  {
    "firstName": "Dave",
    "lastName": "Wallace",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 19,
    "partyAffiliation": "Republican",
    "residence": "Leachville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "dave.wallace@senate.ar.gov",
    "officePhone": "(870)919-8046"
  },
  {
    "firstName": "Dan",
    "lastName": "Sullivan",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 20,
    "partyAffiliation": "Republican",
    "residence": "Jonesboro",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "dan.sullivan@senate.ar.gov",
    "officePhone": "(870)275-2929"
  },
  {
    "firstName": "Blake",
    "lastName": "Johnson",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 21,
    "partyAffiliation": "Republican",
    "residence": "Corning",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Blake.Johnson@senate.ar.gov",
    "officePhone": "870-323-1766"
  },
  {
    "firstName": "John",
    "lastName": "Payton",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 22,
    "partyAffiliation": "Republican",
    "residence": "Wilburn",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "john.payton@senate.ar.gov",
    "officePhone": "(501)362-5815"
  },
  {
    "firstName": "Scott",
    "lastName": "Flippo",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 23,
    "partyAffiliation": "Republican",
    "residence": "Mountain Home",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Scott.Flippo@senate.ar.gov",
    "officePhone": "870-421-3420"
  },
  {
    "firstName": "Missy",
    "lastName": "Irvin",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 24,
    "partyAffiliation": "Republican",
    "residence": "Mountain View",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Missy.Irvin@senate.ar.gov",
    "officePhone": "(870)269-2703"
  },
  {
    "firstName": "Breanne",
    "lastName": "Davis",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 25,
    "partyAffiliation": "Republican",
    "residence": "Russellville",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "gary.stubblefield@senate.ar.gov",
    "officePhone": "(870)269-2703"
  },
  {
    "firstName": "Gary",
    "lastName": "Stubblefield",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 26,
    "partyAffiliation": "Republican",
    "residence": "Branch",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "gary.stubblefield@senate.ar.gov",
    "officePhone": "(479)635-4314"
  },
  {
    "firstName": "Justin",
    "lastName": "Boyd",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 27,
    "partyAffiliation": "Republican",
    "residence": "Fort Smith",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "justin.boyd@senate.ar.gov",
    "officePhone": "(479)262-2156"
  },
  {
    "firstName": "Bryan",
    "lastName": "King",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 28,
    "partyAffiliation": "Republican",
    "residence": "Green Forest",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "bryan.king@senate.ar.gov",
    "officePhone": "(501)682-5452"
  },
  {
    "firstName": "Jim",
    "lastName": "Petty",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 29,
    "partyAffiliation": "Republican",
    "residence": "Van Buren",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jim.petty@senate.ar.gov",
    "officePhone": "(479)459-6362"
  },
  {
    "firstName": "Greg",
    "lastName": "Leding",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 30,
    "partyAffiliation": "Democrat",
    "residence": "Fayetteville",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "greg.leding@senate.ar.gov",
    "officePhone": "(479)422-8099"
  },
  {
    "firstName": "Clint",
    "lastName": "Penzo",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 31,
    "partyAffiliation": "Republican",
    "residence": "Springdale",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "clint.penzo@senate.ar.gov",
    "officePhone": "(479)466-6681"
  },
  {
    "firstName": "Joshua",
    "lastName": "Bryant",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 32,
    "partyAffiliation": "Republican",
    "residence": "Rogers",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "joshua.bryant@senate.ar.gov",
    "officePhone": "(501)500-2206"
  },
  {
    "firstName": "Bart",
    "lastName": "Hester",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 33,
    "partyAffiliation": "Republican",
    "residence": "Cave Springs",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "bart.hester@senate.ar.gov",
    "officePhone": "(479)531-4176"
  },
  {
    "firstName": "Jim",
    "lastName": "Dotson",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 34,
    "partyAffiliation": "Republican",
    "residence": "Bentonville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jim.dotson@senate.ar.gov",
    "officePhone": "(479)222-1234"
  },
  {
    "firstName": "Tyler",
    "lastName": "Dees",
    "chamber": "Senate",
    "homeState": "Arkansas",
    "district": 35,
    "partyAffiliation": "Republican",
    "residence": "Siloam Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tyler.dees@senate.ar.gov",
    "officePhone": "(501)682-6107"
  },
  {
    "firstName": "Jeremy",
    "lastName": "Wooldridge",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "Marmaduke",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jeremy.wooldridge@arkansashouse.org",
    "officePhone": "(870)565-7784"
  },
  {
    "firstName": "Trey",
    "lastName": "Steimel",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 2,
    "partyAffiliation": "Republican",
    "residence": "Pocahontas",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "trey.steimel@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Stetson",
    "lastName": "Painter",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 3,
    "partyAffiliation": "Republican",
    "residence": "Mountain Home",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "stetson.painter@arkansashouse.org",
    "officePhone": "(501)733-3203"
  },
  {
    "firstName": "Jason",
    "lastName": "Nazarenko",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "Cotter",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jason.nazarenko@arkansashouse.org",
    "officePhone": "(931)627-5056"
  },
  {
    "firstName": "Ron",
    "lastName": "McNair",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 5,
    "partyAffiliation": "Republican",
    "residence": "Harrison",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ron.mcnair@arkansashouse.org",
    "officePhone": "(870)754-7962"
  },
  {
    "firstName": "Harlan",
    "lastName": "Breaux",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 6,
    "partyAffiliation": "Republican",
    "residence": "Holiday Island",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "harlan.breaux@arkansashouse.org",
    "officePhone": "(479)981-3170"
  },
  {
    "firstName": "Brit",
    "lastName": "McKenzie",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "Rogers",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "brit.mckenzie@arkansashouse.org",
    "officePhone": "(479)644-9001"
  },
  {
    "firstName": "Austin",
    "lastName": "McCollum",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 8,
    "partyAffiliation": "Republican",
    "residence": "Bentonville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "austin.mccollum@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Diana",
    "lastName": "Gonzales Worthen",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "Springdale",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "diana.gonzalesworthen@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Mindy",
    "lastName": "McAlindon",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 10,
    "partyAffiliation": "Republican",
    "residence": "Centerton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mindy.mcalindon@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Rebecca",
    "lastName": "Burkes",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 11,
    "partyAffiliation": "Republican",
    "residence": "Lowell",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rebecca.burkes@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Hope",
    "lastName": "Duke",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 12,
    "partyAffiliation": "Republican",
    "residence": "Gravette",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "hope.duke@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "R. Scott",
    "lastName": "Richardson",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 13,
    "partyAffiliation": "Republican",
    "residence": "Bentonville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "scott.richardson@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Nick",
    "lastName": "Burkes",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 14,
    "partyAffiliation": "Republican",
    "residence": "Bentonville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "nick.burkes@arkansashouse.org",
    "officePhone": "(479)966-9533"
  },
  {
    "firstName": "John",
    "lastName": "Carr",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 15,
    "partyAffiliation": "Republican",
    "residence": "Rogers",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "john.carr@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Kendon",
    "lastName": "Underwood",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 16,
    "partyAffiliation": "Republican",
    "residence": "Cave Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kendon.underwood@arkansashouse.org",
    "officePhone": "(479)644-8461"
  },
  {
    "firstName": "Randy",
    "lastName": "Torres",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 17,
    "partyAffiliation": "Republican",
    "residence": "Siloam Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "randy.torres@arkansashouse.org",
    "officePhone": "(479)549-7560"
  },
  {
    "firstName": "Robin",
    "lastName": "Lundstrum",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 18,
    "partyAffiliation": "Republican",
    "residence": "Elm Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "robin.lundstrum@arkansashouse.org",
    "officePhone": "(479)957-1959"
  },
  {
    "firstName": "Steve",
    "lastName": "Unger",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 19,
    "partyAffiliation": "Republican",
    "residence": "Springdale",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "steve.unger@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Denise",
    "lastName": "Garner",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "Fayetteville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "denise.garner@arkansashouse.org",
    "officePhone": "(479)283-5050"
  },
  {
    "firstName": "Nicole",
    "lastName": "Clowney",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 21,
    "partyAffiliation": "Democrat",
    "residence": "Fayetteville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "nicole.clowney@arkansashouse.org",
    "officePhone": "(479)445-5337"
  },
  {
    "firstName": "David",
    "lastName": "Whitaker",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 22,
    "partyAffiliation": "Democrat",
    "residence": "Fayetteville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "david.whitaker@arkansashouse.org",
    "officePhone": "(479)236-8313"
  },
  {
    "firstName": "Kendra",
    "lastName": "Moore",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 23,
    "partyAffiliation": "Republican",
    "residence": "Lincoln",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kendra.moore@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Brad",
    "lastName": "Hall",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 24,
    "partyAffiliation": "Republican",
    "residence": "Van Buren",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "brad.hall@arkansashouse.org",
    "officePhone": "(479)670-0545"
  },
  {
    "firstName": "Chad",
    "lastName": "Puryear",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 25,
    "partyAffiliation": "Republican",
    "residence": "Hindsville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chad.puryear@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "James",
    "lastName": "Eaton",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 26,
    "partyAffiliation": "Republican",
    "residence": "Hindsville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "james.eaton@arkansashouse.org",
    "officePhone": "(479)790-0364"
  },
  {
    "firstName": "Steven",
    "lastName": "Walker",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 27,
    "partyAffiliation": "Republican",
    "residence": "Horseshoe Bend",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "steven.walker@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Ben",
    "lastName": "Schulz",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 28,
    "partyAffiliation": "Republican",
    "residence": "Cave City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ben.schulz@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Rick",
    "lastName": "McClure",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 29,
    "partyAffiliation": "Republican",
    "residence": "Malvern",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rick.mcclure@arkansashouse.org",
    "officePhone": "(501)786-4186"
  },
  {
    "firstName": "Frances",
    "lastName": "Cavenaugh",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "Walnut Ridge",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "frances.cavanaugh@arkansashouse.org",
    "officePhone": "(870)886-4000"
  },
  {
    "firstName": "Jimmy",
    "lastName": "Gazaway",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 31,
    "partyAffiliation": "Republican",
    "residence": "Paragould",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jimmy.gazaway@arkansashouse.org",
    "officePhone": "(870)215-1243"
  },
  {
    "firstName": "Jack",
    "lastName": "Ladyman",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 32,
    "partyAffiliation": "Republican",
    "residence": "Jonesboro",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jack.ladyman@arkansashouse.org",
    "officePhone": "(870)340-7499"
  },
  {
    "firstName": "Jon",
    "lastName": "Milligan",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 33,
    "partyAffiliation": "Republican",
    "residence": "Lake City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jon.milligan@arkansashouse.org",
    "officePhone": "(870)219-1261"
  },
  {
    "firstName": "Joey",
    "lastName": "Carr",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 34,
    "partyAffiliation": "Republican",
    "residence": "Blytheville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "joey.carr@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Jessie",
    "lastName": "McGruder",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 35,
    "partyAffiliation": "Democrat",
    "residence": "Marion",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jessie.mcgruder@arkansashouse.org",
    "officePhone": "(870)817-2112"
  },
  {
    "firstName": "Johnny",
    "lastName": "Rye",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 36,
    "partyAffiliation": "Republican",
    "residence": "Trumann",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "johnny.rye@arkansashouse.org",
    "officePhone": "(870)919-3690"
  },
  {
    "firstName": "Steve",
    "lastName": "Hollowell",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 37,
    "partyAffiliation": "Republican",
    "residence": "Forrest City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "steve.hollowell@arkansashouse.org",
    "officePhone": "(870)270-3831"
  },
  {
    "firstName": "Dwight",
    "lastName": "Tosh",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 38,
    "partyAffiliation": "Republican",
    "residence": "Jonesboro",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "dwight.tosh@arkansashouse.org",
    "officePhone": "(870)926-0423"
  },
  {
    "firstName": "Wayne",
    "lastName": "Long",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 39,
    "partyAffiliation": "Republican",
    "residence": "Bradford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "wayne.long@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Shad",
    "lastName": "Pearce",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 40,
    "partyAffiliation": "Republican",
    "residence": "Batesville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "shad.pearce@arkansashouse.org",
    "officePhone": "(870)307-2361"
  },
  {
    "firstName": "Alyssa",
    "lastName": "Brown",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 41,
    "partyAffiliation": "Republican",
    "residence": "Heber Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "alyssa.brown@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Stephen",
    "lastName": "Meeks",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 42,
    "partyAffiliation": "Republican",
    "residence": "Greenbrier",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "stephen.meeks@arkansashouse.org",
    "officePhone": "(501)314-9250"
  },
  {
    "firstName": "Rick",
    "lastName": "Beck",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 43,
    "partyAffiliation": "Republican",
    "residence": "Center Ridge",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rick.beck@arkansashouse.org",
    "officePhone": "(501)912-1441"
  },
  {
    "firstName": "Stan",
    "lastName": "Berry",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 44,
    "partyAffiliation": "Republican",
    "residence": "Dover",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "stan.berry@arkansashouse.org",
    "officePhone": "(479)970-7982"
  },
  {
    "firstName": "Aaron",
    "lastName": "Pilkington",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 45,
    "partyAffiliation": "Republican",
    "residence": "Knoxville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "aaron.pilkington@arkansashouse.org",
    "officePhone": "(479)308-8384"
  },
  {
    "firstName": "Jon",
    "lastName": "Eubanks",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 46,
    "partyAffiliation": "Republican",
    "residence": "Subiaco",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jon.eubanks@arkansashouse.org",
    "officePhone": "(479)438-0533"
  },
  {
    "firstName": "Lee",
    "lastName": "Johnson",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 47,
    "partyAffiliation": "Republican",
    "residence": "Greenwood",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lee.johnson@arkansashouse.org",
    "officePhone": "(479)883-6393"
  },
  {
    "firstName": "Ryan",
    "lastName": "Rose",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 48,
    "partyAffiliation": "Republican",
    "residence": "Van Buren",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ryan.rose@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Jay",
    "lastName": "Richardson",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 49,
    "partyAffiliation": "Democrat",
    "residence": "Fort Smith",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jay.richardson@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Zack",
    "lastName": "Gramlich",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 50,
    "partyAffiliation": "Republican",
    "residence": "Fort Smith",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "zack.gramlich@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Cindy",
    "lastName": "Crawford",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 51,
    "partyAffiliation": "Republican",
    "residence": "Fort Smith",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "cindy.crawford@arkansashouse.org",
    "officePhone": "(479)883-1667"
  },
  {
    "firstName": "Marcus",
    "lastName": "Richmond",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 52,
    "partyAffiliation": "Republican",
    "residence": "Harvey",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "marcus.richmond@arkansashouse.org",
    "officePhone": "(479)299-4416"
  },
  {
    "firstName": "Matt",
    "lastName": "Duffield",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 53,
    "partyAffiliation": "Republican",
    "residence": "Russellville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "matt.duffield@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Mary",
    "lastName": "Bentley",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 54,
    "partyAffiliation": "Republican",
    "residence": "Perryville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mary.bentley@arkansashouse.org",
    "officePhone": "(501)889-3556"
  },
  {
    "firstName": "Matt",
    "lastName": "Brown",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 55,
    "partyAffiliation": "Republican",
    "residence": "Conway",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "matt.brown@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Stephen",
    "lastName": "Magie",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 56,
    "partyAffiliation": "Democrat",
    "residence": "Conway",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "stephen.magie@arkansashouse.org",
    "officePhone": "(501)327-4444"
  },
  {
    "firstName": "Cameron",
    "lastName": "Cooper",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 57,
    "partyAffiliation": "Republican",
    "residence": "Romance",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "cameron.cooper@arkansashouse.org",
    "officePhone": "(501)230-5635"
  },
  {
    "firstName": "Les",
    "lastName": "Eaves",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 58,
    "partyAffiliation": "Republican",
    "residence": "Searcy",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "les.eaves@arkansashouse.org",
    "officePhone": "(501)827-1344"
  },
  {
    "firstName": "Jim",
    "lastName": "Wooten",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 59,
    "partyAffiliation": "Republican",
    "residence": "Beebe",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jim.wooten@arkansashouse.org",
    "officePhone": "(501)858-7403"
  },
  {
    "firstName": "Roger",
    "lastName": "Lynch",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 60,
    "partyAffiliation": "Republican",
    "residence": "Lonoke",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "roger.lynch@arkansashouse.org",
    "officePhone": "(501)412-8959"
  },
  {
    "firstName": "Jeremiah",
    "lastName": "Moore",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 61,
    "partyAffiliation": "Republican",
    "residence": "Clarendon",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jeremiah.moore@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Mark",
    "lastName": "McElroy",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 62,
    "partyAffiliation": "Republican",
    "residence": "Tillar",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mark.mcelroy@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Lincoln",
    "lastName": "Barnett",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 63,
    "partyAffiliation": "Democrat",
    "residence": "Forrest City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lincoln.barnett@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Kenneth",
    "lastName": "Ferguson",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 64,
    "partyAffiliation": "Democrat",
    "residence": "Pine Bluff",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kenneth.ferguson@arkansashouse.org",
    "officePhone": "(870)413-8942"
  },
  {
    "firstName": "Glenn",
    "lastName": "Barnes",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 65,
    "partyAffiliation": "Democrat",
    "residence": "Pine Bluff",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "glenn.barnes@arkansashouse.org",
    "officePhone": "(870)329-7957"
  },
  {
    "firstName": "Mark",
    "lastName": "Perry",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 66,
    "partyAffiliation": "Democrat",
    "residence": "Jacksonville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mark.perry@arkansashouse.org",
    "officePhone": "(501)982-4561"
  },
  {
    "firstName": "Karilyn",
    "lastName": "Brown",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 67,
    "partyAffiliation": "Republican",
    "residence": "Sherwood",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "karilyn.brown@arkansashouse.org",
    "officePhone": "(501)580-9000"
  },
  {
    "firstName": "Brian",
    "lastName": "Evans",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 68,
    "partyAffiliation": "Republican",
    "residence": "Cabot",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Brian.evans@arkansashouse.org",
    "officePhone": "(501)941-4002"
  },
  {
    "firstName": "David",
    "lastName": "Ray",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 69,
    "partyAffiliation": "Republican",
    "residence": "Maumelle",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "david.ray@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Carlton",
    "lastName": "Wing",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 70,
    "partyAffiliation": "Republican",
    "residence": "North Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "carlton.wing@arkansashouse.org",
    "officePhone": "(501)944-9464"
  },
  {
    "firstName": "Brandon",
    "lastName": "Achor",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 71,
    "partyAffiliation": "Republican",
    "residence": "Maumelle",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "brandon.achor@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Tracy",
    "lastName": "Steele",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 72,
    "partyAffiliation": "Democrat",
    "residence": "North Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tracy.steele@arkansashouse.org",
    "officePhone": "(501)580-9514"
  },
  {
    "firstName": "Andrew",
    "lastName": "Collins",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 73,
    "partyAffiliation": "Democrat",
    "residence": "Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "andrew.collins@arkansashouse.org",
    "officePhone": "(501)650-2233"
  },
  {
    "firstName": "Tippi",
    "lastName": "McCullough",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 74,
    "partyAffiliation": "Democrat",
    "residence": "Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tippi.mccullough@arkansashouse.org",
    "officePhone": "(501)766-3177"
  },
  {
    "firstName": "Ashley",
    "lastName": "Hudson",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 75,
    "partyAffiliation": "Democrat",
    "residence": "Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ashley.hudson@arkansashouse.org",
    "officePhone": "(501)658-4096"
  },
  {
    "firstName": "Joy",
    "lastName": "Springer",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 76,
    "partyAffiliation": "Democrat",
    "residence": "Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "joy.springer@arkansashouse.org",
    "officePhone": "(501)374-3758"
  },
  {
    "firstName": "Fred",
    "lastName": "Allen",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 77,
    "partyAffiliation": "Democrat",
    "residence": "Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "fred.allen@arkansashouse.org",
    "officePhone": "(501)804-7844"
  },
  {
    "firstName": "Keith",
    "lastName": "Brooks",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 78,
    "partyAffiliation": "Republican",
    "residence": "Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "keith.brooks@arkansashouse.org",
    "officePhone": "(501)744-6080"
  },
  {
    "firstName": "Tara",
    "lastName": "Shephard",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 79,
    "partyAffiliation": "Democrat",
    "residence": "Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tara.shephard@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Denise",
    "lastName": "Jones Ennett",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 80,
    "partyAffiliation": "Democrat",
    "residence": "Little Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "denise.ennett@arkansashouse.org",
    "officePhone": "(501)690-4211"
  },
  {
    "firstName": "RJ",
    "lastName": "Hawk",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 81,
    "partyAffiliation": "Republican",
    "residence": "Bryant",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "RJ.Hawk@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Tony",
    "lastName": "Furman",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 82,
    "partyAffiliation": "Republican",
    "residence": "Benton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tony.furman@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Paul",
    "lastName": "Childress",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 83,
    "partyAffiliation": "Republican",
    "residence": "Benton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "paul.childress@arkansashouse.org",
    "officePhone": "(501)860-3424"
  },
  {
    "firstName": "Les",
    "lastName": "Warren",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 84,
    "partyAffiliation": "Republican",
    "residence": "Hot Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "les.warren@arkansashouse.org",
    "officePhone": "(501)623-4405"
  },
  {
    "firstName": "Richard",
    "lastName": "McGrew",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 85,
    "partyAffiliation": "Republican",
    "residence": "Hot Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "richard.mcgrew@arkansashouse.org",
    "officePhone": "(501)623-2481"
  },
  {
    "firstName": "John",
    "lastName": "Maddox",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 86,
    "partyAffiliation": "Republican",
    "residence": "Mena",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "John.Maddox@arkansashouse.org",
    "officePhone": "(479)394-6060"
  },
  {
    "firstName": "DeAnn",
    "lastName": "Vaught",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 87,
    "partyAffiliation": "Republican",
    "residence": "Horatio",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "deann.vaught@arkansashouse.org",
    "officePhone": "(870)832-2638"
  },
  {
    "firstName": "Dolly",
    "lastName": "Henley",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 88,
    "partyAffiliation": "Republican",
    "residence": "Washington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "dolly.henley@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Justin",
    "lastName": "Gonzales",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 89,
    "partyAffiliation": "Republican",
    "residence": "Okolona",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "justin.gonzales@arkansashouse.org",
    "officePhone": "(870)245-6365"
  },
  {
    "firstName": "Richard",
    "lastName": "Womack",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 90,
    "partyAffiliation": "Republican",
    "residence": "Arkadelphia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "richard.womack@arkansashouse.org",
    "officePhone": "(870)403-6287"
  },
  {
    "firstName": "Bruce",
    "lastName": "Cozart",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 91,
    "partyAffiliation": "Republican",
    "residence": "Hot Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "bruce.cozart@arkansashouse.org",
    "officePhone": "(501)627-3232"
  },
  {
    "firstName": "Julie",
    "lastName": "Mayberry",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 92,
    "partyAffiliation": "Republican",
    "residence": "Hensley",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "julie.mayberry@arkansashouse.org",
    "officePhone": "(501)888-3522"
  },
  {
    "firstName": "Mike",
    "lastName": "Holcomb",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 93,
    "partyAffiliation": "Republican",
    "residence": "Pine Bluff",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mike.holcomb@arkansashouse.org",
    "officePhone": "(870)489-7177"
  },
  {
    "firstName": "Jeff",
    "lastName": "Wardlaw",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 94,
    "partyAffiliation": "Republican",
    "residence": "Hermitage",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jeff.wardlaw@arkansashouse.org",
    "officePhone": "(870)226-9501"
  },
  {
    "firstName": "Howard",
    "lastName": "Beaty",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 95,
    "partyAffiliation": "Republican",
    "residence": "Crossett",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "howard.beaty@arkansashouse.org",
    "officePhone": ""
  },
  {
    "firstName": "Sonia",
    "lastName": "Eubanks Barker",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 96,
    "partyAffiliation": "Republican",
    "residence": "Smackover",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "sonia.barker@arkansashouse.org",
    "officePhone": "(870)814-7605"
  },
  {
    "firstName": "Matthew",
    "lastName": "Shepherd",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 97,
    "partyAffiliation": "Republican",
    "residence": "El Dorado",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "matthew.shepherd@arkansashouse.org",
    "officePhone": "(870)862-2087"
  },
  {
    "firstName": "Wade",
    "lastName": "Andrews",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 98,
    "partyAffiliation": "Republican",
    "residence": "Camden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "wade.andrews@arkansashouse.org",
    "officePhone": "(870)818-7067"
  },
  {
    "firstName": "Lane",
    "lastName": "Jean",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 99,
    "partyAffiliation": "Republican",
    "residence": "Magnolia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lane.jean@arkansashouse.org",
    "officePhone": "(870)904-1856"
  },
  {
    "firstName": "Carol",
    "lastName": "Dalby",
    "chamber": "House",
    "homeState": "Arkansas",
    "district": 100,
    "partyAffiliation": "Republican",
    "residence": "Texarkana",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "carol.dalby@arkansashouse.org",
    "officePhone": "(870)772-1255"
  }
];
