// California legislators mapped to legislatorSchema
export default [
  {
    "firstName": "Megan",
    "lastName": "Dahle",
    "chamber": "Senate",
    "homeState": "California",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "Bieber",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.dahle@senate.ca.gov",
    "officePhone": "(916)651-4001"
  },
  {
    "firstName": "Mike",
    "lastName": "McGuire",
    "chamber": "Senate",
    "homeState": "California",
    "district": 2,
    "partyAffiliation": "Democrat",
    "residence": "Healdsburg",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.mcguire@senate.ca.gov",
    "officePhone": "(916)651-4002"
  },
  {
    "firstName": "Christopher",
    "lastName": "Cabaldon",
    "chamber": "Senate",
    "homeState": "California",
    "district": 3,
    "partyAffiliation": "Democrat",
    "residence": "West Sacramento",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.cabaldon@senate.ca.gov",
    "officePhone": "(916)651-4003"
  },
  {
    "firstName": "Marie",
    "lastName": "Alvarado-Gil",
    "chamber": "Senate",
    "homeState": "California",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "Jackson",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Alvarado-gil@senate.ca.gov",
    "officePhone": "(916)651-4004"
  },
  {
    "firstName": "Jerry",
    "lastName": "McNerney",
    "chamber": "Senate",
    "homeState": "California",
    "district": 5,
    "partyAffiliation": "Democrat",
    "residence": "Pleasanton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.mcnerney@senate.ca.gov",
    "officePhone": "(916)651-4005"
  },
  {
    "firstName": "Roger",
    "lastName": "Niello",
    "chamber": "Senate",
    "homeState": "California",
    "district": 6,
    "partyAffiliation": "Republican",
    "residence": "Fair Oaks",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.niello@senate.ca.gov",
    "officePhone": "(916)651-4006"
  },
  {
    "firstName": "Jesse",
    "lastName": "Arreguin",
    "chamber": "Senate",
    "homeState": "California",
    "district": 7,
    "partyAffiliation": "Democrat",
    "residence": "Berkeley",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.arreguin@senate.ca.gov",
    "officePhone": "(916)651-4007"
  },
  {
    "firstName": "Angelique",
    "lastName": "Ashby",
    "chamber": "Senate",
    "homeState": "California",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "Natomas",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.ashby@senate.ca.gov",
    "officePhone": "(916)651-4008"
  },
  {
    "firstName": "Tim",
    "lastName": "Grayson",
    "chamber": "Senate",
    "homeState": "California",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "Concord",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.grayson@senate.ca.gov",
    "officePhone": "(916)651-4009"
  },
  {
    "firstName": "Aisha",
    "lastName": "Wahab",
    "chamber": "Senate",
    "homeState": "California",
    "district": 10,
    "partyAffiliation": "Democrat",
    "residence": "Hayward",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.wahab@senate.ca.gov",
    "officePhone": "(916)651-4010"
  },
  {
    "firstName": "Scott",
    "lastName": "Wiener",
    "chamber": "Senate",
    "homeState": "California",
    "district": 11,
    "partyAffiliation": "Democrat",
    "residence": "San Francisco",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.wiener@senate.ca.gov",
    "officePhone": "(916)651-4011"
  },
  {
    "firstName": "Shannon",
    "lastName": "Grove",
    "chamber": "Senate",
    "homeState": "California",
    "district": 12,
    "partyAffiliation": "Republican",
    "residence": "Bakersfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.grove@senate.ca.gov",
    "officePhone": "(916)651-4012"
  },
  {
    "firstName": "Josh",
    "lastName": "Becker",
    "chamber": "Senate",
    "homeState": "California",
    "district": 13,
    "partyAffiliation": "Democrat",
    "residence": "Menlo Park",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.becker@senate.ca.gov",
    "officePhone": "(916)651-4013"
  },
  {
    "firstName": "Anna",
    "lastName": "Caballero",
    "chamber": "Senate",
    "homeState": "California",
    "district": 14,
    "partyAffiliation": "Democrat",
    "residence": "Merced",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.caballero@senate.ca.gov",
    "officePhone": "(916)651-4014"
  },
  {
    "firstName": "Dave",
    "lastName": "Cortese",
    "chamber": "Senate",
    "homeState": "California",
    "district": 15,
    "partyAffiliation": "Democrat",
    "residence": "San Jose",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.cortese@senate.ca.gov",
    "officePhone": "(916)651-4015"
  },
  {
    "firstName": "Melissa",
    "lastName": "Hurtado",
    "chamber": "Senate",
    "homeState": "California",
    "district": 16,
    "partyAffiliation": "Democrat",
    "residence": "Bakersfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.hurtado@senate.ca.gov",
    "officePhone": "(916)651-4016"
  },
  {
    "firstName": "John",
    "lastName": "Laird",
    "chamber": "Senate",
    "homeState": "California",
    "district": 17,
    "partyAffiliation": "Democrat",
    "residence": "Santa Cruz",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.laird@senate.ca.gov",
    "officePhone": "(916)651-4017"
  },
  {
    "firstName": "Steve",
    "lastName": "Padilla",
    "chamber": "Senate",
    "homeState": "California",
    "district": 18,
    "partyAffiliation": "Democrat",
    "residence": "Chula Vista",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.padilla@senate.ca.gov",
    "officePhone": "(916)651-4018"
  },
  {
    "firstName": "Rosilicie",
    "lastName": "Ochoa Bogh",
    "chamber": "Senate",
    "homeState": "California",
    "district": 19,
    "partyAffiliation": "Republican",
    "residence": "Yucaipa",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.ochoa-bogh@senate.ca.gov",
    "officePhone": "(916)651-4019"
  },
  {
    "firstName": "Caroline",
    "lastName": "Menjivar",
    "chamber": "Senate",
    "homeState": "California",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "San Fernando",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.menjivar@senate.ca.gov",
    "officePhone": "(916)651-4020"
  },
  {
    "firstName": "Monique",
    "lastName": "Limon",
    "chamber": "Senate",
    "homeState": "California",
    "district": 21,
    "partyAffiliation": "Democrat",
    "residence": "Santa Barbara",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.limon@senate.ca.gov",
    "officePhone": "(916)651-4021"
  },
  {
    "firstName": "Susan",
    "lastName": "Rubio",
    "chamber": "Senate",
    "homeState": "California",
    "district": 22,
    "partyAffiliation": "Democrat",
    "residence": "Baldwin Park",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.rubio@senate.ca.gov",
    "officePhone": "(916)651-4022"
  },
  {
    "firstName": "Suzette",
    "lastName": "Martinez Valladares",
    "chamber": "Senate",
    "homeState": "California",
    "district": 23,
    "partyAffiliation": "Republican",
    "residence": "Santa Clarita",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.martinez-valladares@senate.ca.gov",
    "officePhone": "(916)651-4023"
  },
  {
    "firstName": "Benjamin",
    "lastName": "Allen",
    "chamber": "Senate",
    "homeState": "California",
    "district": 24,
    "partyAffiliation": "Democrat",
    "residence": "Santa Monica",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.allen@senate.ca.gov",
    "officePhone": "(916)651-4024"
  },
  {
    "firstName": "Sasha",
    "lastName": "Perez",
    "chamber": "Senate",
    "homeState": "California",
    "district": 25,
    "partyAffiliation": "Democrat",
    "residence": "Alhambra",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.perez@senate.ca.gov",
    "officePhone": "(916)651-4025"
  },
  {
    "firstName": "Maria",
    "lastName": "Durazo",
    "chamber": "Senate",
    "homeState": "California",
    "district": 26,
    "partyAffiliation": "Democrat",
    "residence": "Los Angeles",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.durazo@senate.ca.gov",
    "officePhone": "(916)651-4026"
  },
  {
    "firstName": "Henry",
    "lastName": "Stern",
    "chamber": "Senate",
    "homeState": "California",
    "district": 27,
    "partyAffiliation": "Democrat",
    "residence": "Malibu",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.stern@senate.ca.gov",
    "officePhone": "(916)651-4027"
  },
  {
    "firstName": "Lola",
    "lastName": "Smallwood-Cuevas",
    "chamber": "Senate",
    "homeState": "California",
    "district": 28,
    "partyAffiliation": "Democrat",
    "residence": "Los Angeles",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.smallwood-cuevas@senate.ca.gov",
    "officePhone": "(916)651-4028"
  },
  {
    "firstName": "Eloise",
    "lastName": "Gomez Reyes",
    "chamber": "Senate",
    "homeState": "California",
    "district": 29,
    "partyAffiliation": "Democrat",
    "residence": "Colton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.gomez-reyez@senate.ca.gov",
    "officePhone": "(916)651-4029"
  },
  {
    "firstName": "Bob",
    "lastName": "Archuleta",
    "chamber": "Senate",
    "homeState": "California",
    "district": 30,
    "partyAffiliation": "Democrat",
    "residence": "Pico Rivera",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.archuleta@senate.ca.gov",
    "officePhone": "(916)651-4030"
  },
  {
    "firstName": "Sabrina",
    "lastName": "Cervantes",
    "chamber": "Senate",
    "homeState": "California",
    "district": 31,
    "partyAffiliation": "Democrat",
    "residence": "Riverside",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.cervantes@senate.ca.gov",
    "officePhone": "(916)651-4031"
  },
  {
    "firstName": "Kelly",
    "lastName": "Seyarto",
    "chamber": "Senate",
    "homeState": "California",
    "district": 32,
    "partyAffiliation": "Republican",
    "residence": "Murrieta",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.seyarto@senate.ca.gov",
    "officePhone": "(916)651-4032"
  },
  {
    "firstName": "Lena",
    "lastName": "Gonzalez",
    "chamber": "Senate",
    "homeState": "California",
    "district": 33,
    "partyAffiliation": "Democrat",
    "residence": "Long Beach",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.gonzalez@senate.ca.gov",
    "officePhone": "(916)651-4033"
  },
  {
    "firstName": "Thomas",
    "lastName": "Umberg",
    "chamber": "Senate",
    "homeState": "California",
    "district": 34,
    "partyAffiliation": "Democrat",
    "residence": "Santa Ana",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.umberg@senalte.ca.gov",
    "officePhone": "(916)651-4034"
  },
  {
    "firstName": "Laura",
    "lastName": "Richardson",
    "chamber": "Senate",
    "homeState": "California",
    "district": 35,
    "partyAffiliation": "Democrat",
    "residence": "San Pedro",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.richardson@senate.ca.gov",
    "officePhone": "(916)651-4035"
  },
  {
    "firstName": "Tony",
    "lastName": "Strickland",
    "chamber": "Senate",
    "homeState": "California",
    "district": 36,
    "partyAffiliation": "Republican",
    "residence": "Huntington Beach",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.strickland@senate.ca.gov",
    "officePhone": "(916)651-4036"
  },
  {
    "firstName": "Steven",
    "lastName": "Choi",
    "chamber": "Senate",
    "homeState": "California",
    "district": 37,
    "partyAffiliation": "Republican",
    "residence": "Irvine",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Senator.Choi@senate.ca.gov",
    "officePhone": "(916)651-4037"
  },
  {
    "firstName": "Catherine",
    "lastName": "Blakespear",
    "chamber": "Senate",
    "homeState": "California",
    "district": 38,
    "partyAffiliation": "Democrat",
    "residence": "Encinitas",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.blakespear@senate.ca.gov",
    "officePhone": "(916)651-4038"
  },
  {
    "firstName": "Akilah",
    "lastName": "Weber Pierson",
    "chamber": "Senate",
    "homeState": "California",
    "district": 39,
    "partyAffiliation": "Democrat",
    "residence": "San Diego",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.weber@senate.ca.gov",
    "officePhone": "(916)651-4039"
  },
  {
    "firstName": "Brian",
    "lastName": "Jones",
    "chamber": "Senate",
    "homeState": "California",
    "district": 40,
    "partyAffiliation": "Republican",
    "residence": "Santee",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "senator.jones@senate.ca.gov",
    "officePhone": "(916)651-4040"
  },
  {
    "firstName": "Heather",
    "lastName": "Hadwick",
    "chamber": "House",
    "homeState": "California",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "Altura",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Hadwick@assembly.ca.gov",
    "officePhone": "(916)319-2001"
  },
  {
    "firstName": "Chris",
    "lastName": "Rogers",
    "chamber": "House",
    "homeState": "California",
    "district": 2,
    "partyAffiliation": "Democrat",
    "residence": "Santa Rosa",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Rogers@assembly.ca.gov",
    "officePhone": "(916)319-2002"
  },
  {
    "firstName": "James",
    "lastName": "Gallagher",
    "chamber": "House",
    "homeState": "California",
    "district": 3,
    "partyAffiliation": "Republican",
    "residence": "Nicolaus",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Gallagher@assembly.ca.gov",
    "officePhone": "(916)319-2003"
  },
  {
    "firstName": "Cecilia",
    "lastName": "Aguiar-Curry",
    "chamber": "House",
    "homeState": "California",
    "district": 4,
    "partyAffiliation": "Democrat",
    "residence": "Winters",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Aguiar-Curry@assembly.ca.gov",
    "officePhone": "(916)319-2004"
  },
  {
    "firstName": "Joe",
    "lastName": "Patterson",
    "chamber": "House",
    "homeState": "California",
    "district": 5,
    "partyAffiliation": "Republican",
    "residence": "Rocklin",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Patterson@assembly.ca.gov",
    "officePhone": "(916)319-2005"
  },
  {
    "firstName": "Maggy",
    "lastName": "Krell",
    "chamber": "House",
    "homeState": "California",
    "district": 6,
    "partyAffiliation": "Democrat",
    "residence": "Sacramento",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Krell@assembly.ca.gov",
    "officePhone": "(916)319-2006"
  },
  {
    "firstName": "Josh",
    "lastName": "Hoover",
    "chamber": "House",
    "homeState": "California",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "Folsom",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.hoover@assembly.ca.gov",
    "officePhone": "(916)319-2007"
  },
  {
    "firstName": "David",
    "lastName": "Tangipa",
    "chamber": "House",
    "homeState": "California",
    "district": 8,
    "partyAffiliation": "Republican",
    "residence": "Clovis",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.tangipa@assembly.ca.gov",
    "officePhone": "(916)319-2008"
  },
  {
    "firstName": "Heath",
    "lastName": "Flora",
    "chamber": "House",
    "homeState": "California",
    "district": 9,
    "partyAffiliation": "Republican",
    "residence": "Lodi",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.flora@assembly.ca.gov",
    "officePhone": "(916)319-2009"
  },
  {
    "firstName": "Stephanie",
    "lastName": "Nguyen",
    "chamber": "House",
    "homeState": "California",
    "district": 10,
    "partyAffiliation": "Democrat",
    "residence": "Elk Grove",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.nguyen@assembly.ca.gov",
    "officePhone": "(916)319-2010"
  },
  {
    "firstName": "Lori",
    "lastName": "Wilson",
    "chamber": "House",
    "homeState": "California",
    "district": 11,
    "partyAffiliation": "Democrat",
    "residence": "Suisun City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.wilson@assembly.ca.gov",
    "officePhone": "(916)319-2011"
  },
  {
    "firstName": "Damon",
    "lastName": "Connolly",
    "chamber": "House",
    "homeState": "California",
    "district": 12,
    "partyAffiliation": "Democrat",
    "residence": "San Rafael",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.connolly@assembly.ca.gov",
    "officePhone": "(916)319-2012"
  },
  {
    "firstName": "Rhodesia",
    "lastName": "Ransom",
    "chamber": "House",
    "homeState": "California",
    "district": 13,
    "partyAffiliation": "Democrat",
    "residence": "Tracy",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.ransom@assembly.ca.gov",
    "officePhone": "(916)319-2013"
  },
  {
    "firstName": "Buffy",
    "lastName": "Wicks",
    "chamber": "House",
    "homeState": "California",
    "district": 14,
    "partyAffiliation": "Democrat",
    "residence": "Oakland",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.wicks@assembly.ca.gov",
    "officePhone": "(916)319-2014"
  },
  {
    "firstName": "Anamarie",
    "lastName": "Avila Farias",
    "chamber": "House",
    "homeState": "California",
    "district": 15,
    "partyAffiliation": "Democrat",
    "residence": "Martinez",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.avila-farias@assembly.ca.gov",
    "officePhone": "(916)319-2015"
  },
  {
    "firstName": "Rebecca",
    "lastName": "Bauer-Kahan",
    "chamber": "House",
    "homeState": "California",
    "district": 16,
    "partyAffiliation": "Democrat",
    "residence": "Orinda",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.bauer-kahan@assembly.ca.gov",
    "officePhone": "(916)319-2016"
  },
  {
    "firstName": "Matt",
    "lastName": "Haney",
    "chamber": "House",
    "homeState": "California",
    "district": 17,
    "partyAffiliation": "Democrat",
    "residence": "San Francisco",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.haney@assembly.ca.gov",
    "officePhone": "(916)319-2017"
  },
  {
    "firstName": "Mia",
    "lastName": "Bonta",
    "chamber": "House",
    "homeState": "California",
    "district": 18,
    "partyAffiliation": "Democrat",
    "residence": "Alameda",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.bonta@assembly.ca.gov",
    "officePhone": "(916)319-2018"
  },
  {
    "firstName": "Catherine",
    "lastName": "Stefani",
    "chamber": "House",
    "homeState": "California",
    "district": 19,
    "partyAffiliation": "Democrat",
    "residence": "San Francisco",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.stefani@assembly.ca.gov",
    "officePhone": "(916)319-2019"
  },
  {
    "firstName": "Liz",
    "lastName": "Ortega",
    "chamber": "House",
    "homeState": "California",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "San Leandro",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.ortega@assembly.ca.gov",
    "officePhone": "(916)319-2020"
  },
  {
    "firstName": "Diane",
    "lastName": "Papan",
    "chamber": "House",
    "homeState": "California",
    "district": 21,
    "partyAffiliation": "Democrat",
    "residence": "San Mateo",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.papan@assembly.ca.gov",
    "officePhone": "(916)319-2021"
  },
  {
    "firstName": "Juan",
    "lastName": "Alanis",
    "chamber": "House",
    "homeState": "California",
    "district": 22,
    "partyAffiliation": "Republican",
    "residence": "Modesto",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.alanis@assembly.ca.gov",
    "officePhone": "(916)319-2022"
  },
  {
    "firstName": "Mare",
    "lastName": "Berman",
    "chamber": "House",
    "homeState": "California",
    "district": 23,
    "partyAffiliation": "Democrat",
    "residence": "Menlo Park",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.berman@assembly.ca.gov",
    "officePhone": "(916)319-2023"
  },
  {
    "firstName": "Alex",
    "lastName": "Lee",
    "chamber": "House",
    "homeState": "California",
    "district": 24,
    "partyAffiliation": "Democrat",
    "residence": "San Jose",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.lee@assembly.ca.gov",
    "officePhone": "(916)319-2024"
  },
  {
    "firstName": "Ash",
    "lastName": "Kalra",
    "chamber": "House",
    "homeState": "California",
    "district": 25,
    "partyAffiliation": "Democrat",
    "residence": "San Jose",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.kalra@assembly.ca.gov",
    "officePhone": "(916)319-2025"
  },
  {
    "firstName": "Patrick",
    "lastName": "Ahrens",
    "chamber": "House",
    "homeState": "California",
    "district": 26,
    "partyAffiliation": "Democrat",
    "residence": "Sunnyvale",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.ahrens@assembly.ca.gov",
    "officePhone": "(916)319-2026"
  },
  {
    "firstName": "Esmeralda",
    "lastName": "Soria",
    "chamber": "House",
    "homeState": "California",
    "district": 27,
    "partyAffiliation": "Democrat",
    "residence": "Fresno",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.soria@assembly.ca.gov",
    "officePhone": "(916)319-2027"
  },
  {
    "firstName": "Gail",
    "lastName": "Pellerin",
    "chamber": "House",
    "homeState": "California",
    "district": 28,
    "partyAffiliation": "Democrat",
    "residence": "Santa Cruz",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.pellerin@assembly.ca.gov",
    "officePhone": "(916)319-2028"
  },
  {
    "firstName": "Robert",
    "lastName": "Rivas",
    "chamber": "House",
    "homeState": "California",
    "district": 29,
    "partyAffiliation": "Democrat",
    "residence": "Hollister",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.rivas@assembly.ca.gov",
    "officePhone": "(916)319-2029"
  },
  {
    "firstName": "Dawn",
    "lastName": "Addis",
    "chamber": "House",
    "homeState": "California",
    "district": 30,
    "partyAffiliation": "Democrat",
    "residence": "Morro Bay",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.addis@assembly.ca.gov",
    "officePhone": "(916)319-2030"
  },
  {
    "firstName": "Joaquin",
    "lastName": "Arambula",
    "chamber": "House",
    "homeState": "California",
    "district": 31,
    "partyAffiliation": "Democrat",
    "residence": "Fresno",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.arambula@assembly.ca.gov",
    "officePhone": "(916)319-2031"
  },
  {
    "firstName": "Stan",
    "lastName": "Ellis",
    "chamber": "House",
    "homeState": "California",
    "district": 32,
    "partyAffiliation": "Republican",
    "residence": "Bakersfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.ellis@assembly.ca.gov",
    "officePhone": "(916)319-2032"
  },
  {
    "firstName": "Alexandra",
    "lastName": "Macedo",
    "chamber": "House",
    "homeState": "California",
    "district": 33,
    "partyAffiliation": "Republican",
    "residence": "Tulare",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.macedo@assembly.ca.gov",
    "officePhone": "(916)319-2033"
  },
  {
    "firstName": "Tom",
    "lastName": "Lackey",
    "chamber": "House",
    "homeState": "California",
    "district": 34,
    "partyAffiliation": "Republican",
    "residence": "Palmdale",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.lackey@assembly.ca.gov",
    "officePhone": "(916)319-2034"
  },
  {
    "firstName": "Jasmeet",
    "lastName": "Kaur Bains",
    "chamber": "House",
    "homeState": "California",
    "district": 35,
    "partyAffiliation": "Democrat",
    "residence": "Bakersfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.kaur-bains@assembly.ca.gov",
    "officePhone": "(916)319-2035"
  },
  {
    "firstName": "Jeff",
    "lastName": "Gonzalez",
    "chamber": "House",
    "homeState": "California",
    "district": 36,
    "partyAffiliation": "Republican",
    "residence": "Indio",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.gonzalez@assembly.ca.gov",
    "officePhone": "(916)319-2036"
  },
  {
    "firstName": "Gregg",
    "lastName": "Hart",
    "chamber": "House",
    "homeState": "California",
    "district": 37,
    "partyAffiliation": "Democrat",
    "residence": "Santa Barbara",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.hart@assembly.ca.gov",
    "officePhone": "(916)319-2037"
  },
  {
    "firstName": "Steve",
    "lastName": "Bennett",
    "chamber": "House",
    "homeState": "California",
    "district": 38,
    "partyAffiliation": "Democrat",
    "residence": "Ventura",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.bennett@assembly.ca.gov",
    "officePhone": "(916)319-2038"
  },
  {
    "firstName": "Juan",
    "lastName": "Carrillo",
    "chamber": "House",
    "homeState": "California",
    "district": 39,
    "partyAffiliation": "Democrat",
    "residence": "Palmdale",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.carrillo@assembly.ca.gov",
    "officePhone": "(916)319-2039"
  },
  {
    "firstName": "Pilar",
    "lastName": "Schiavo",
    "chamber": "House",
    "homeState": "California",
    "district": 40,
    "partyAffiliation": "Democrat",
    "residence": "Santa Clarita",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.schiavo@assembly.ca.gov",
    "officePhone": "(916)319-2040"
  },
  {
    "firstName": "John",
    "lastName": "Harabedian",
    "chamber": "House",
    "homeState": "California",
    "district": 41,
    "partyAffiliation": "Democrat",
    "residence": "Pasadena",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.harabedian@assembly.ca.gov",
    "officePhone": "(916)319-2041"
  },
  {
    "firstName": "Jacqui",
    "lastName": "Irwin",
    "chamber": "House",
    "homeState": "California",
    "district": 42,
    "partyAffiliation": "Democrat",
    "residence": "Thousand Oaks",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.irwin@assembly.ca.gov",
    "officePhone": "(916)319-2042"
  },
  {
    "firstName": "Celeste",
    "lastName": "Rodriguez",
    "chamber": "House",
    "homeState": "California",
    "district": 43,
    "partyAffiliation": "Democrat",
    "residence": "San Fernando",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.rodriguez@assembly.ca.gov",
    "officePhone": "(916)319-2043"
  },
  {
    "firstName": "Nick",
    "lastName": "Schultz",
    "chamber": "House",
    "homeState": "California",
    "district": 44,
    "partyAffiliation": "Democrat",
    "residence": "Burbank",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.schultz@assembly.ca.gov",
    "officePhone": "(916)319-2044"
  },
  {
    "firstName": "James",
    "lastName": "Ramos",
    "chamber": "House",
    "homeState": "California",
    "district": 45,
    "partyAffiliation": "Democrat",
    "residence": "Highland",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.ramos@assembly.ca.gov",
    "officePhone": "(916)319-2045"
  },
  {
    "firstName": "Jesse",
    "lastName": "Gabriel",
    "chamber": "House",
    "homeState": "California",
    "district": 46,
    "partyAffiliation": "Democrat",
    "residence": "Encino",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.gabriel@assembly.ca.gov",
    "officePhone": "(916)319-2046"
  },
  {
    "firstName": "Greg",
    "lastName": "Wallis",
    "chamber": "House",
    "homeState": "California",
    "district": 47,
    "partyAffiliation": "Republican",
    "residence": "Bermuda Dunes",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.wallis@assembly.ca.gov",
    "officePhone": "(916)319-2047"
  },
  {
    "firstName": "Blanca",
    "lastName": "Rubio",
    "chamber": "House",
    "homeState": "California",
    "district": 48,
    "partyAffiliation": "Democrat",
    "residence": "Baldwin Park",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.rubio@assembly.ca.gov",
    "officePhone": "(916)319-2048"
  },
  {
    "firstName": "Mike",
    "lastName": "Fong",
    "chamber": "House",
    "homeState": "California",
    "district": 49,
    "partyAffiliation": "Democrat",
    "residence": "Alhambra",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.fong@assembly.ca.gov",
    "officePhone": "(916)319-2049"
  },
  {
    "firstName": "Robert",
    "lastName": "Garcia",
    "chamber": "House",
    "homeState": "California",
    "district": 50,
    "partyAffiliation": "Democrat",
    "residence": "Rancho Cucamonga",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.garcia@assembly.ca.gov",
    "officePhone": "(916)319-2050"
  },
  {
    "firstName": "Rick",
    "lastName": "Chavez Zbur",
    "chamber": "House",
    "homeState": "California",
    "district": 51,
    "partyAffiliation": "Democrat",
    "residence": "Los Angeles",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.chavez-zbur@assembly.ca.gov",
    "officePhone": "(916)319-2051"
  },
  {
    "firstName": "Jessica",
    "lastName": "Caloza",
    "chamber": "House",
    "homeState": "California",
    "district": 52,
    "partyAffiliation": "Democrat",
    "residence": "Los Angeles",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.caloza@assembly.ca.gov",
    "officePhone": "(916)319-2052"
  },
  {
    "firstName": "Michelle",
    "lastName": "Rodriguez",
    "chamber": "House",
    "homeState": "California",
    "district": 53,
    "partyAffiliation": "Democrat",
    "residence": "Pomona",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.rodriguez@assembly.ca.gov",
    "officePhone": "(916)319-2053"
  },
  {
    "firstName": "Mark",
    "lastName": "Gonzalez",
    "chamber": "House",
    "homeState": "California",
    "district": 54,
    "partyAffiliation": "Democrat",
    "residence": "Los Angeles",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.gonzalez@assembly.ca.gov",
    "officePhone": "(916)319-2054"
  },
  {
    "firstName": "Isaac",
    "lastName": "Bryan",
    "chamber": "House",
    "homeState": "California",
    "district": 55,
    "partyAffiliation": "Democrat",
    "residence": "Jefferson Park",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.bryan@assembly.ca.gov",
    "officePhone": "(916)319-2055"
  },
  {
    "firstName": "Lisa",
    "lastName": "Calderon",
    "chamber": "House",
    "homeState": "California",
    "district": 56,
    "partyAffiliation": "Democrat",
    "residence": "Whittier",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.calderon@assembly.ca.gov",
    "officePhone": "(916)319-2056"
  },
  {
    "firstName": "Sade",
    "lastName": "Elhawary",
    "chamber": "House",
    "homeState": "California",
    "district": 57,
    "partyAffiliation": "Democrat",
    "residence": "Los Angeles",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.elhawary@assembly.ca.gov",
    "officePhone": "(916)319-2057"
  },
  {
    "firstName": "Leticia",
    "lastName": "Castillo",
    "chamber": "House",
    "homeState": "California",
    "district": 58,
    "partyAffiliation": "Republican",
    "residence": "Home Gardens",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.castillo@assembly.ca.gov",
    "officePhone": "(916)319-2058"
  },
  {
    "firstName": "Phillip",
    "lastName": "Chen",
    "chamber": "House",
    "homeState": "California",
    "district": 59,
    "partyAffiliation": "Republican",
    "residence": "Yorba Linda",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.chen@assembly.ca.gov",
    "officePhone": "(916)319-2059"
  },
  {
    "firstName": "Corey",
    "lastName": "Jackson",
    "chamber": "House",
    "homeState": "California",
    "district": 60,
    "partyAffiliation": "Democrat",
    "residence": "Perris",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.jackson@assembly.ca.gov",
    "officePhone": "(916)319-2060"
  },
  {
    "firstName": "Tina",
    "lastName": "McKinnor",
    "chamber": "House",
    "homeState": "California",
    "district": 61,
    "partyAffiliation": "Democrat",
    "residence": "Hawthorne",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.McKinnor@assembly.ca.gov",
    "officePhone": "(916)319-2061"
  },
  {
    "firstName": "Jose Luis",
    "lastName": "Solache",
    "chamber": "House",
    "homeState": "California",
    "district": 62,
    "partyAffiliation": "Democrat",
    "residence": "Lynwood",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.solache@assembly.ca.gov",
    "officePhone": "(916)319-2062"
  },
  {
    "firstName": "Vacant",
    "lastName": "Vacant",
    "chamber": "House",
    "homeState": "California",
    "district": 63,
    "partyAffiliation": "Vacant",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(916)319-2063"
  },
  {
    "firstName": "Blanca",
    "lastName": "Pacheco",
    "chamber": "House",
    "homeState": "California",
    "district": 64,
    "partyAffiliation": "Democrat",
    "residence": "Downey",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.pacheco@assembly.ca.gov",
    "officePhone": "(916)319-2064"
  },
  {
    "firstName": "Mike",
    "lastName": "Gipson",
    "chamber": "House",
    "homeState": "California",
    "district": 65,
    "partyAffiliation": "Democrat",
    "residence": "Carson",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.gipson@assembly.ca.gov",
    "officePhone": "(916)319-2065"
  },
  {
    "firstName": "Al",
    "lastName": "Muratsuchi",
    "chamber": "House",
    "homeState": "California",
    "district": 66,
    "partyAffiliation": "Democrat",
    "residence": "Rolling Hills Estates",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.muratsuchi@assembly.ca.gov",
    "officePhone": "(916)319-2066"
  },
  {
    "firstName": "Sharon",
    "lastName": "Quirk-Silva",
    "chamber": "House",
    "homeState": "California",
    "district": 67,
    "partyAffiliation": "Democrat",
    "residence": "Fullerton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.quirk-silva@assembly.ca.gov",
    "officePhone": "(916)319-2067"
  },
  {
    "firstName": "Avelino",
    "lastName": "Valencia",
    "chamber": "House",
    "homeState": "California",
    "district": 68,
    "partyAffiliation": "Democrat",
    "residence": "Anaheim",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.valencia@assembly.ca.gov",
    "officePhone": "(916)319-2068"
  },
  {
    "firstName": "Josh",
    "lastName": "Lowenthal",
    "chamber": "House",
    "homeState": "California",
    "district": 69,
    "partyAffiliation": "Democrat",
    "residence": "Long Beach",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.lowenthal@assembly.ca.gov",
    "officePhone": "(916)319-2069"
  },
  {
    "firstName": "Tri",
    "lastName": "Ta",
    "chamber": "House",
    "homeState": "California",
    "district": 70,
    "partyAffiliation": "Republican",
    "residence": "Westminster",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.ta@assembly.ca.gov",
    "officePhone": "(916)319-2070"
  },
  {
    "firstName": "Kate",
    "lastName": "Sanchez",
    "chamber": "House",
    "homeState": "California",
    "district": 71,
    "partyAffiliation": "Republican",
    "residence": "Rancho Santa Margarita",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Sanchez@assembly.ca.gov",
    "officePhone": "(916)319-2071"
  },
  {
    "firstName": "Diane",
    "lastName": "Dixon",
    "chamber": "House",
    "homeState": "California",
    "district": 72,
    "partyAffiliation": "Republican",
    "residence": "Newport Beach",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.dixon@assembly.ca.gov",
    "officePhone": "(916)319-2072"
  },
  {
    "firstName": "Cottie",
    "lastName": "Petrie-Norris",
    "chamber": "House",
    "homeState": "California",
    "district": 73,
    "partyAffiliation": "Democrat",
    "residence": "Irvine",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Petrie-Norris@assembly.ca.gov",
    "officePhone": "(916)319-2073"
  },
  {
    "firstName": "Laurie",
    "lastName": "Davies",
    "chamber": "House",
    "homeState": "California",
    "district": 74,
    "partyAffiliation": "Republican",
    "residence": "Laguna Niguel",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.davies@assembly.ca.gov",
    "officePhone": "(916)319-2074"
  },
  {
    "firstName": "Carl",
    "lastName": "DeMaio",
    "chamber": "House",
    "homeState": "California",
    "district": 75,
    "partyAffiliation": "Republican",
    "residence": "Escondido",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.DeMaio@assembly.ca.gov",
    "officePhone": "(916)319-2075"
  },
  {
    "firstName": "Darshana",
    "lastName": "Patel",
    "chamber": "House",
    "homeState": "California",
    "district": 76,
    "partyAffiliation": "Democrat",
    "residence": "San Diego",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Patel@assembly.ca.gov",
    "officePhone": "(916)319-2076"
  },
  {
    "firstName": "Tasha",
    "lastName": "Boerner",
    "chamber": "House",
    "homeState": "California",
    "district": 77,
    "partyAffiliation": "Democrat",
    "residence": "Encinitas",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Boerner@assembly.ca.gov",
    "officePhone": "(916)319-2077"
  },
  {
    "firstName": "Christopher",
    "lastName": "Ward",
    "chamber": "House",
    "homeState": "California",
    "district": 78,
    "partyAffiliation": "Democrat",
    "residence": "San Diego",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Ward@assembly.ca.gov",
    "officePhone": "(916)319-2078"
  },
  {
    "firstName": "LaShae",
    "lastName": "Sharp-Collins",
    "chamber": "House",
    "homeState": "California",
    "district": 79,
    "partyAffiliation": "Democrat",
    "residence": "San Diego",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Sharp-Collins@assembly.ca.gov",
    "officePhone": "(916)319-2079"
  },
  {
    "firstName": "David",
    "lastName": "Alvarez",
    "chamber": "House",
    "homeState": "California",
    "district": 80,
    "partyAffiliation": "Democrat",
    "residence": "San Diego",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Assemblymember.Alvarez@assembly.ca.gov",
    "officePhone": "(916)319-2080"
  }
];
