// Colorado legislators mapped to legislatorSchema
export default [
  {
    "firstName": "Javier",
    "lastName": "Mabrey",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 1,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "javier.mabrey.house@coleg.gov",
    "officePhone": "303-866-2966"
  },
  {
    "firstName": "Steven",
    "lastName": "Woodrow",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 2,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "steven.woodrow.house@coleg.gov",
    "officePhone": "303-866-2967"
  },
  {
    "firstName": "Meg",
    "lastName": "Froelich",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 3,
    "partyAffiliation": "Democrat",
    "residence": "Greenwood Village",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "meg.froelich.house@coleg.gov",
    "officePhone": "303-866-2921"
  },
  {
    "firstName": "Cecelia",
    "lastName": "Espenoza",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 4,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "cecelia.espenoza.house@coleg.gov",
    "officePhone": "303-866-2954"
  },
  {
    "firstName": "Alex",
    "lastName": "Valdez",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 5,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "alex.valdez.house@coleg.gov",
    "officePhone": "303-866-2925"
  },
  {
    "firstName": "Sean",
    "lastName": "Camacho",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 6,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "sean.camacho.house@coleg.gov",
    "officePhone": "303-866-2911"
  },
  {
    "firstName": "Jennifer",
    "lastName": "Bacon",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 7,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jennifer.bacon.house@coleg.gov",
    "officePhone": "303-866-2909"
  },
  {
    "firstName": "Lindsey",
    "lastName": "Gilchrist",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lindsay.gilchrist.house@coleg.gov",
    "officePhone": "303-866-2959"
  },
  {
    "firstName": "Emily",
    "lastName": "Sirota",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "emily.sirota.house@coleg.gov",
    "officePhone": "303-866-2910"
  },
  {
    "firstName": "Junie",
    "lastName": "Joseph",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 10,
    "partyAffiliation": "Democrat",
    "residence": "Boulder",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "junie.joseph.house@coleg.gov",
    "officePhone": "303-866-2915"
  },
  {
    "firstName": "Karen",
    "lastName": "McCormick",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 11,
    "partyAffiliation": "Democrat",
    "residence": "Hygiene",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "karen.mccormick.house@coleg.gov",
    "officePhone": "303-866-2780"
  },
  {
    "firstName": "Kyle",
    "lastName": "Brown",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 12,
    "partyAffiliation": "Democrat",
    "residence": "Louisville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kyle.brown.house@coleg.gov",
    "officePhone": "303-866-2920"
  },
  {
    "firstName": "Julie",
    "lastName": "McCluskie",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 13,
    "partyAffiliation": "Democrat",
    "residence": "Colorado Springs",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Julie.Mccluskie.house@coleg.gov",
    "officePhone": "303-866-2952"
  },
  {
    "firstName": "Rose",
    "lastName": "Pugliese",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 14,
    "partyAffiliation": "Republican",
    "residence": "Colorado Springs",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rose.pugliese.house@coleg.gov",
    "officePhone": "303-866-2965"
  },
  {
    "firstName": "Scott",
    "lastName": "Bottoms",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 15,
    "partyAffiliation": "Republican",
    "residence": "Colorado Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "scott.bottoms.house@coleg.gov",
    "officePhone": "303-866-5525"
  },
  {
    "firstName": "Rebecca",
    "lastName": "Keltie",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 16,
    "partyAffiliation": "Republican",
    "residence": "Colorado Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rebecca.keltie.house@coleg.gov",
    "officePhone": "303-866-2937"
  },
  {
    "firstName": "Regina",
    "lastName": "English",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 17,
    "partyAffiliation": "Democrat",
    "residence": "Colorado Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "regina.english.house@coleg.gov",
    "officePhone": "303-866-3069"
  },
  {
    "firstName": "Amy",
    "lastName": "Paschal",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 18,
    "partyAffiliation": "Democrat",
    "residence": "Colorado Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "amy.paschal.house@coleg.gov",
    "officePhone": "303-866-2932"
  },
  {
    "firstName": "Dan",
    "lastName": "Woog",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 19,
    "partyAffiliation": "Republican",
    "residence": "Frederick",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "dan.woog.house@coleg.gov",
    "officePhone": "303-866-2924"
  },
  {
    "firstName": "Jarvis",
    "lastName": "Caldwell",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 20,
    "partyAffiliation": "Republican",
    "residence": "El Paso County",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jarvis.caldwell.house@coleg.gov",
    "officePhone": "303-866-2191"
  },
  {
    "firstName": "Mary",
    "lastName": "Bradfield",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 21,
    "partyAffiliation": "Republican",
    "residence": "Colorado Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mary.bradfield.house@coleg.gov",
    "officePhone": "303-866-2946"
  },
  {
    "firstName": "Ken",
    "lastName": "DeGraaf",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 22,
    "partyAffiliation": "Republican",
    "residence": "Colorado Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ken.degraaf.house@coleg.gov",
    "officePhone": "303-866-2927"
  },
  {
    "firstName": "Monica",
    "lastName": "Duran",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 23,
    "partyAffiliation": "Democrat",
    "residence": "Wheat Ridge",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "monica.duran.house@coleg.gov",
    "officePhone": "303-866-5522"
  },
  {
    "firstName": "Lisa",
    "lastName": "Feret",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 24,
    "partyAffiliation": "Democrat",
    "residence": "Arvada",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lisa.feret.house@coleg.gov",
    "officePhone": "303-866-2950"
  },
  {
    "firstName": "Tammy",
    "lastName": "Story",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 25,
    "partyAffiliation": "Democrat",
    "residence": "Evergreen",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tammy.story.house@coleg.gov",
    "officePhone": "303-866-2582"
  },
  {
    "firstName": "Meghan",
    "lastName": "Lukens",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 26,
    "partyAffiliation": "Democrat",
    "residence": "Eagle",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "meghan.lukens.house@coleg.gov",
    "officePhone": "303-866-2923"
  },
  {
    "firstName": "Brianna",
    "lastName": "Titone",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 27,
    "partyAffiliation": "Democrat",
    "residence": "Golden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "brianna.titone.house@coleg.gov",
    "officePhone": "303-866-2962"
  },
  {
    "firstName": "Sheila",
    "lastName": "Lieder",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 28,
    "partyAffiliation": "Democrat",
    "residence": "Littleton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "sheila.lieder.house@coleg.gov",
    "officePhone": "303-866-2939"
  },
  {
    "firstName": "Shannon",
    "lastName": "Bird",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 29,
    "partyAffiliation": "Democrat",
    "residence": "Northglenn",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "shannon.bird.house@coleg.gov",
    "officePhone": "303-866-2843"
  },
  {
    "firstName": "Rebekah",
    "lastName": "Stewart",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 30,
    "partyAffiliation": "Democrat",
    "residence": "Lakewood",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rebekah.stewart.house@coleg.gov",
    "officePhone": "303-866-2951"
  },
  {
    "firstName": "Jacqueline",
    "lastName": "Phillips",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 31,
    "partyAffiliation": "Democrat",
    "residence": "Thornton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jacque.phillips.house@coleg.gov",
    "officePhone": "303-866-2918"
  },
  {
    "firstName": "Manny",
    "lastName": "Rutinel",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 32,
    "partyAffiliation": "Democrat",
    "residence": "Commerce City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "manny.rutinel.house@coleg.gov",
    "officePhone": "303-866-2945"
  },
  {
    "firstName": "William",
    "lastName": "Lindstedt",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 33,
    "partyAffiliation": "Democrat",
    "residence": "Broomfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "william.lindstedt.house@coleg.gov",
    "officePhone": "303-866-4667"
  },
  {
    "firstName": "Jenny",
    "lastName": "Willford",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 34,
    "partyAffiliation": "Democrat",
    "residence": "Northglenn",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jenny.willford.house@coleg.gov",
    "officePhone": "303-866-2931"
  },
  {
    "firstName": "Lorena",
    "lastName": "Garcia",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 35,
    "partyAffiliation": "Democrat",
    "residence": "Westminster",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lorena.garcia.house@coleg.gov",
    "officePhone": "303-866-2964"
  },
  {
    "firstName": "Michael",
    "lastName": "Carter",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 36,
    "partyAffiliation": "Democrat",
    "residence": "Aurora",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "michael.carter.house@coleg.gov",
    "officePhone": "303-866-2942"
  },
  {
    "firstName": "Chad",
    "lastName": "Clifford",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 37,
    "partyAffiliation": "Democrat",
    "residence": "Centennial",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chad.clifford.house@coleg.gov",
    "officePhone": "303-866-5510"
  },
  {
    "firstName": "Gretchen",
    "lastName": "Rydin",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 38,
    "partyAffiliation": "Democrat",
    "residence": "Littleton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "gretchen.rydin.house@coleg.gov",
    "officePhone": "303-866-2953"
  },
  {
    "firstName": "Brandi",
    "lastName": "Bradley",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 39,
    "partyAffiliation": "Republican",
    "residence": "Larkspur",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "brandi.bradley.house@coleg.gov",
    "officePhone": "303-866-2935"
  },
  {
    "firstName": "Naquetta",
    "lastName": "Ricks",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 40,
    "partyAffiliation": "Democrat",
    "residence": "Aurora",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Naquetta.Ricks.house@coleg.gov",
    "officePhone": "303-866-2944"
  },
  {
    "firstName": "Jamie",
    "lastName": "Jackson",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 41,
    "partyAffiliation": "Democrat",
    "residence": "AuroraAurora",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jamie.jackson.house@coleg.gov",
    "officePhone": "303-866-2919"
  },
  {
    "firstName": "Mandy",
    "lastName": "Lindsay",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 42,
    "partyAffiliation": "Democrat",
    "residence": "",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mandy.lindsay.house@coleg.gov",
    "officePhone": "303-866-3911"
  },
  {
    "firstName": "Bob",
    "lastName": "Marshall",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 43,
    "partyAffiliation": "Democrat",
    "residence": "Highlands Ranch",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "bob.marshall.house@coleg.gov",
    "officePhone": "303-866-2936"
  },
  {
    "firstName": "Anthony",
    "lastName": "Hartsook",
    "chamber": "Columbia",
    "homeState": "Colorado",
    "district": 44,
    "partyAffiliation": "Republican",
    "residence": "Parker",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "anthony.hartsook.house@coleg.gov",
    "officePhone": "303-866-2933"
  },
  {
    "firstName": "Max",
    "lastName": "Brooks",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 45,
    "partyAffiliation": "Republican",
    "residence": "Castle Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "max.brooks.house@coleg.gov",
    "officePhone": "303-866-2948"
  },
  {
    "firstName": "Tisha",
    "lastName": "Mauro",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 46,
    "partyAffiliation": "Democrat",
    "residence": "Pueblo",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tisha.mauro.house@coleg.gov",
    "officePhone": "303-866-2968"
  },
  {
    "firstName": "Ty",
    "lastName": "Winter",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 47,
    "partyAffiliation": "Republican",
    "residence": "Trinidad",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ty.winter.house@coleg.gov",
    "officePhone": "303-866-2747"
  },
  {
    "firstName": "Carlos",
    "lastName": "Barron",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 48,
    "partyAffiliation": "Republican",
    "residence": "Fort Lupton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "carlos.barron.house@coleg.gov",
    "officePhone": "303-866-2943"
  },
  {
    "firstName": "Lesley",
    "lastName": "Smith",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 49,
    "partyAffiliation": "Democrat",
    "residence": "Boulder",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lesley.smith.house@coleg.gov",
    "officePhone": "303-866-2578"
  },
  {
    "firstName": "Ryan",
    "lastName": "Gonzalez",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 50,
    "partyAffiliation": "Republican",
    "residence": "Greeley",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ryan.gonzalez.house@coleg.gov",
    "officePhone": "303-866-2929"
  },
  {
    "firstName": "Ron",
    "lastName": "Weinberg",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 51,
    "partyAffiliation": "Republican",
    "residence": "Loveland",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ron.weinberg.house@coleg.gov",
    "officePhone": "303-866-2947"
  },
  {
    "firstName": "Yara",
    "lastName": "Zokaie",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 52,
    "partyAffiliation": "Democrat",
    "residence": "Windsor",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "yara.zokaie.house@coleg.gov",
    "officePhone": "303-866-4569"
  },
  {
    "firstName": "Andrew",
    "lastName": "Boesenecker",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 53,
    "partyAffiliation": "Democrat",
    "residence": "Fort Collins",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "andrew.boesenecker.house@coleg.gov",
    "officePhone": "303-866-2917"
  },
  {
    "firstName": "Matt",
    "lastName": "Soper",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 54,
    "partyAffiliation": "Republican",
    "residence": "Delta",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "matthew.soper.house@coleg.gov",
    "officePhone": "303-866-2583"
  },
  {
    "firstName": "Rick",
    "lastName": "Taggart",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 55,
    "partyAffiliation": "Republican",
    "residence": "Grand Junction",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rick.taggart.house@coleg.gov",
    "officePhone": "303-866-3068"
  },
  {
    "firstName": "Chris",
    "lastName": "Richardson",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 56,
    "partyAffiliation": "Republican",
    "residence": "Elbert County",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chris.richardson.house@coleg.gov",
    "officePhone": "303-866-2912"
  },
  {
    "firstName": "Elizabeth",
    "lastName": "Velasco",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 57,
    "partyAffiliation": "Democrat",
    "residence": "Glenwood Springs",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "elizabeth.velasco.house@coleg.gov",
    "officePhone": "303-866-2949"
  },
  {
    "firstName": "Larry Don",
    "lastName": "Suckla",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 58,
    "partyAffiliation": "Republican",
    "residence": "Montezuma County",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "larry.suckla.house@coleg.gov",
    "officePhone": "303-866-2955"
  },
  {
    "firstName": "Katie",
    "lastName": "Stewart K.",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 59,
    "partyAffiliation": "Democrat",
    "residence": "Durango",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "katie.stewart.house@coleg.gov",
    "officePhone": "303-866-2914"
  },
  {
    "firstName": "Stephanie",
    "lastName": "Luck",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 60,
    "partyAffiliation": "Republican",
    "residence": "Penrose",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "stephanie.luck.house@coleg.gov",
    "officePhone": "303-866-2905"
  },
  {
    "firstName": "Eliza",
    "lastName": "Hamrick",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 61,
    "partyAffiliation": "Democrat",
    "residence": "Centennial",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "eliza.hamrick.house@coleg.gov",
    "officePhone": "303-866-3706"
  },
  {
    "firstName": "Matthew",
    "lastName": "Martinez",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 62,
    "partyAffiliation": "Democrat",
    "residence": "Alamosa",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "matthew.martinez.house@coleg.gov",
    "officePhone": "3303-866-2916"
  },
  {
    "firstName": "Dusty",
    "lastName": "Johnson",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 63,
    "partyAffiliation": "Republican",
    "residence": "Fort Morgan",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "dustyforcolorado@gmail.com",
    "officePhone": "303-866-2398"
  },
  {
    "firstName": "Ryan",
    "lastName": "Armagost",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 64,
    "partyAffiliation": "Republican",
    "residence": "Berthoud",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ryan.armagost.house@coleg.gov",
    "officePhone": "303-866-2906"
  },
  {
    "firstName": "Lori",
    "lastName": "Garcia Sander",
    "chamber": "House",
    "homeState": "Colorado",
    "district": 65,
    "partyAffiliation": "Republican",
    "residence": "Eaton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lori.garciasander.house@coleg.gov",
    "officePhone": "303-866-2907"
  },
  {
    "firstName": "Byron",
    "lastName": "Pelton",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "Sterling",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "byron.pelton.senate@coleg.gov",
    "officePhone": "303-866-6360"
  },
  {
    "firstName": "Lisa",
    "lastName": "Frizell",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 2,
    "partyAffiliation": "Republican",
    "residence": "Castle Rock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lisa.frizell.senate@coleg.gov",
    "officePhone": "303-866-4869"
  },
  {
    "firstName": "Nick",
    "lastName": "Hinrichsen",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 3,
    "partyAffiliation": "Democrat",
    "residence": "Pueblo",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "nick.hinrichsen.senate@coleg.gov",
    "officePhone": "303-866-4878"
  },
  {
    "firstName": "Mark",
    "lastName": "Baisley",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "Sedalia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mark.baisley@senate.co.com",
    "officePhone": "303-866-4877"
  },
  {
    "firstName": "Marc",
    "lastName": "Catlin",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 5,
    "partyAffiliation": "Republican",
    "residence": "Montrose",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "marc.catlin.senate@coleg.gov",
    "officePhone": "303-866-5292"
  },
  {
    "firstName": "Cleave",
    "lastName": "Simpson",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 6,
    "partyAffiliation": "Republican",
    "residence": "Alamosa",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "cleave.simpson.senate@coleg.gov",
    "officePhone": "303-866-4875"
  },
  {
    "firstName": "Janice",
    "lastName": "Rich",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "Grand Junction",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "janicerichsd7@gmail.com",
    "officePhone": "303-866-3077"
  },
  {
    "firstName": "Dylan",
    "lastName": "Roberts",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "Eagle",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "dylan.roberts.senate@coleg.gov",
    "officePhone": "303-866-4871"
  },
  {
    "firstName": "Paul",
    "lastName": "Lundeen",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 9,
    "partyAffiliation": "Republican",
    "residence": "Colorado Springs",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "paul.lundeen.senate@coleg.gov",
    "officePhone": "303-866-4835"
  },
  {
    "firstName": "Larry",
    "lastName": "Liston",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 10,
    "partyAffiliation": "Republican",
    "residence": "Colorado Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "larry.liston.senate@coleg.gov",
    "officePhone": "303-866-2737"
  },
  {
    "firstName": "Tony",
    "lastName": "Exum",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 11,
    "partyAffiliation": "Democrat",
    "residence": "Colorado Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tony.exum.senate@coleg.gov",
    "officePhone": "303-866-6364"
  },
  {
    "firstName": "Marc",
    "lastName": "Snyder",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 12,
    "partyAffiliation": "Democrat",
    "residence": "Colorado Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "marc.snyder.senate@coleg.gov",
    "officePhone": "303-866-4880"
  },
  {
    "firstName": "Scott",
    "lastName": "Bright",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 13,
    "partyAffiliation": "Republican",
    "residence": "Platteville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "scott.bright.senate@coleg.gov",
    "officePhone": "303-866-4855"
  },
  {
    "firstName": "Cathy",
    "lastName": "Kipp",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 14,
    "partyAffiliation": "Democrat",
    "residence": "Fort Collins",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "cathy.kipp.senate@coleg.gov",
    "officePhone": "303-866-4841"
  },
  {
    "firstName": "Janice",
    "lastName": "Marchman",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 15,
    "partyAffiliation": "Democrat",
    "residence": "Loveland",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "janice.marchman.senate@coleg.gov",
    "officePhone": "303-866-4853"
  },
  {
    "firstName": "Chris",
    "lastName": "Kolker",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 16,
    "partyAffiliation": "Democrat",
    "residence": "Centennial",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chris.kolker.senate@coleg.gov",
    "officePhone": "303-866-4883"
  },
  {
    "firstName": "Katie",
    "lastName": "Wallace",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 17,
    "partyAffiliation": "Democrat",
    "residence": "Longmont",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "katie.wallace.senate@coleg.gov",
    "officePhone": "303-866-5291"
  },
  {
    "firstName": "Judy",
    "lastName": "Amabile",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 18,
    "partyAffiliation": "Democrat",
    "residence": "Boulder",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "judy.amabile.senate@coleg.gov",
    "officePhone": "303-866-4872"
  },
  {
    "firstName": "Lindsey",
    "lastName": "Daugherty",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 19,
    "partyAffiliation": "Democrat",
    "residence": "Arvada",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lindsey.daugherty.senate@coleg.gov",
    "officePhone": "303-866-4840"
  },
  {
    "firstName": "Lisa",
    "lastName": "Cutter",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "Evergreen",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lisa.cutter.senate@coleg.gov",
    "officePhone": "303-866-4859"
  },
  {
    "firstName": "Dafna",
    "lastName": "Michaelson Jenet",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 21,
    "partyAffiliation": "Democrat",
    "residence": "Commerce City",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "dafna.michaelson.jenet.senate@coleg.gov",
    "officePhone": "303-866-4857"
  },
  {
    "firstName": "Jessie",
    "lastName": "Danielson",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 22,
    "partyAffiliation": "Democrat",
    "residence": "Wheat Ridge",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jessie.danielson.senate@coleg.gov",
    "officePhone": "303-866-4856"
  },
  {
    "firstName": "Barbara",
    "lastName": "Kirkmeyer",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 23,
    "partyAffiliation": "Republican",
    "residence": "Brighton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "barbara.kirkmeyer.senate@coleg.gov",
    "officePhone": "303-866-4876"
  },
  {
    "firstName": "Kyle",
    "lastName": "Mullica",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 24,
    "partyAffiliation": "Democrat",
    "residence": "Northglenn",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kyle.mullica.senate@coleg.gov",
    "officePhone": "303-866-4451"
  },
  {
    "firstName": "Faith",
    "lastName": "Winter",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 25,
    "partyAffiliation": "Democrat",
    "residence": "Thornton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "faith.winter.senate@coleg.gov",
    "officePhone": "303-866-4863"
  },
  {
    "firstName": "Jeff",
    "lastName": "Bridges",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 26,
    "partyAffiliation": "Democrat",
    "residence": "Greenwood Village",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jeff.bridges.senate@coleg.gov",
    "officePhone": "303-866-4846"
  },
  {
    "firstName": "Tom",
    "lastName": "Sullivan",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 27,
    "partyAffiliation": "Democrat",
    "residence": "Centennial",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tom.sullivan.senate@coleg.gov",
    "officePhone": "303-866-4873"
  },
  {
    "firstName": "Mike",
    "lastName": "Weissman",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 28,
    "partyAffiliation": "Democrat",
    "residence": "Aurora",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mike.weissman.senate@coleg.gov",
    "officePhone": "303-866-4879"
  },
  {
    "firstName": "Iman",
    "lastName": "Jodeh",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 29,
    "partyAffiliation": "Democrat",
    "residence": "Aurora",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "iman.jodeh.senate@coleg.gov",
    "officePhone": "303-866-3432"
  },
  {
    "firstName": "John",
    "lastName": "Carson",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "Highlands Ranch",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "john.carson.senate@coleg.gov",
    "officePhone": "303-866-4881"
  },
  {
    "firstName": "Matt",
    "lastName": "Ball",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 31,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "matt.ball.senate@coleg.gov",
    "officePhone": "303-866-4861"
  },
  {
    "firstName": "Robert",
    "lastName": "Rodriguez",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 32,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "robert.rodriguez.senate@coleg.gov",
    "officePhone": "303-866-4852"
  },
  {
    "firstName": "James",
    "lastName": "Coleman",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 33,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "james.coleman.senate@coleg.gov",
    "officePhone": "303-866-4864"
  },
  {
    "firstName": "Julie",
    "lastName": "Gonzales J.",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 34,
    "partyAffiliation": "Democrat",
    "residence": "Denver",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "julie.gonzales.senate@coleg.gov",
    "officePhone": "303-866-4862"
  },
  {
    "firstName": "Rod",
    "lastName": "Pelton",
    "chamber": "Senate",
    "homeState": "Colorado",
    "district": 35,
    "partyAffiliation": "Republican",
    "residence": "Cheyenne Wells",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rod.pelton.senate@coleg.gov",
    "officePhone": "303-866-4884"
  }
];
