// Connecticut legislators mapped to legislatorSchema
export default [
  {
    "firstName": "John",
    "lastName": "Fonfara",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 1,
    "partyAffiliation": "Democrat",
    "residence": "Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "fonfara@senatedems.ct.gov",
    "officePhone": "(860)240-0043"
  },
  {
    "firstName": "Douglas",
    "lastName": "McCrory",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 2,
    "partyAffiliation": "Democrat",
    "residence": "Bloomfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mccrory@senatedems.ct.gov",
    "officePhone": "(860)240-1453"
  },
  {
    "firstName": "Saud",
    "lastName": "Anwar",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 3,
    "partyAffiliation": "Democrat",
    "residence": "South Windsor",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "anwar@senatedems.ct.gov",
    "officePhone": "(860)240-0347"
  },
  {
    "firstName": "MD",
    "lastName": "Rahman",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 4,
    "partyAffiliation": "Democrat",
    "residence": "Manchester",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rahman@senatedems.ct.gov",
    "officePhone": "(860)240-5302"
  },
  {
    "firstName": "Derek",
    "lastName": "Slap",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 5,
    "partyAffiliation": "Democrat",
    "residence": "West Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "slap@senatedems.ct.gov",
    "officePhone": "(860)240-1436"
  },
  {
    "firstName": "Rick",
    "lastName": "Slopes",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 6,
    "partyAffiliation": "Democrat",
    "residence": "New Britain",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lopes@senatedems.ct.gov",
    "officePhone": "(860)240-0099"
  },
  {
    "firstName": "John",
    "lastName": "Kissel",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "Enfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "john.a.kissel@cga.ct.gov",
    "officePhone": "(860)240-0531"
  },
  {
    "firstName": "Paul",
    "lastName": "Honig",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "Harwinton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "honig@senatedems.ct.gov",
    "officePhone": "(860)240-0598"
  },
  {
    "firstName": "Matthew",
    "lastName": "Lesser",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "Middletown",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lesser@senatedems.ct.gov",
    "officePhone": "(860)240-0511"
  },
  {
    "firstName": "Gary",
    "lastName": "Winfield",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 10,
    "partyAffiliation": "Democrat",
    "residence": "New Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "winfield@senatedems.ct.gov",
    "officePhone": "(860)240-0475"
  },
  {
    "firstName": "Martin",
    "lastName": "Looney",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 11,
    "partyAffiliation": "Democrat",
    "residence": "New Haven",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "looney@senatedems.ct.gov",
    "officePhone": "(860)240-0375"
  },
  {
    "firstName": "Christine",
    "lastName": "Cohen",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 12,
    "partyAffiliation": "Democrat",
    "residence": "Guilford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "cohen@senatedems.ct.gov",
    "officePhone": "(860)240-0455"
  },
  {
    "firstName": "Jan",
    "lastName": "Hochadel",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 13,
    "partyAffiliation": "Democrat",
    "residence": "Meriden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "hochadel@senatedems.ct.gov",
    "officePhone": "(860)240-0584"
  },
  {
    "firstName": "James",
    "lastName": "Maroney",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 14,
    "partyAffiliation": "Democrat",
    "residence": "Milford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "maroney@senatedems.ct.gov",
    "officePhone": "(860)240-0381"
  },
  {
    "firstName": "Joan",
    "lastName": "Hartley",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 15,
    "partyAffiliation": "Democrat",
    "residence": "Waterbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "hartley@senatedems.ct.gov",
    "officePhone": "(860)240-0006"
  },
  {
    "firstName": "Rob",
    "lastName": "Sampson",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 16,
    "partyAffiliation": "Republican",
    "residence": "Wolcott",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rob.sampson@cga.ct.gov",
    "officePhone": "(860)240-8843"
  },
  {
    "firstName": "Jorge",
    "lastName": "Cabrera",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 17,
    "partyAffiliation": "Democrat",
    "residence": "Hamden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "cabrera@senatedems.ct.gov",
    "officePhone": "(860)240-0050"
  },
  {
    "firstName": "Heather",
    "lastName": "Somers",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 18,
    "partyAffiliation": "Republican",
    "residence": "Groton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "heather.somers@cga.ct.gov",
    "officePhone": "(860)240-8800"
  },
  {
    "firstName": "Catherine",
    "lastName": "Osten",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 19,
    "partyAffiliation": "Democrat",
    "residence": "Sprague",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "osten@senatedems.ct.gov",
    "officePhone": "(860)240-0579"
  },
  {
    "firstName": "Martha",
    "lastName": "Marx",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "New London",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "marx@senatedems.ct.gov",
    "officePhone": "(860)240-0436"
  },
  {
    "firstName": "Jason",
    "lastName": "Perillo",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 21,
    "partyAffiliation": "Republican",
    "residence": "Shelton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jason.perillo@cga.ct.gov",
    "officePhone": "(860)240-8800"
  },
  {
    "firstName": "Sujata",
    "lastName": "Gadkar-Wilcox",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 22,
    "partyAffiliation": "Democrat",
    "residence": "Trumbull",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "sujata.gadkarwilcox@cga.ct.gov",
    "officePhone": "(860)240-0425"
  },
  {
    "firstName": "Herron",
    "lastName": "Gaston",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 23,
    "partyAffiliation": "Democrat",
    "residence": "Bridgeport",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "gaston@senatedems.ct.gov",
    "officePhone": "(860)240-0591"
  },
  {
    "firstName": "Julie",
    "lastName": "Kushner",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 24,
    "partyAffiliation": "Democrat",
    "residence": "Danbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kushner@senatedems.ct.gov",
    "officePhone": "(860)240-0509"
  },
  {
    "firstName": "Bob",
    "lastName": "Duff",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 25,
    "partyAffiliation": "Democrat",
    "residence": "Norwalk",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "duff@senatedems.ct.gov",
    "officePhone": "(860)240-0414"
  },
  {
    "firstName": "Ceci",
    "lastName": "Maher",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 26,
    "partyAffiliation": "Democrat",
    "residence": "Wilton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "maher@senatedems.ct.gov",
    "officePhone": "(860)240-0068"
  },
  {
    "firstName": "Patricia",
    "lastName": "Miller",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 27,
    "partyAffiliation": "Democrat",
    "residence": "Stamford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "miller@senatedems.ct.gov",
    "officePhone": "(860)240-0589"
  },
  {
    "firstName": "Tony",
    "lastName": "Hwang",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 28,
    "partyAffiliation": "Republican",
    "residence": "Fairfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tony.hwang@cga.ct.gov",
    "officePhone": "(860)240-8800"
  },
  {
    "firstName": "Mae",
    "lastName": "Flexer",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 29,
    "partyAffiliation": "Democrat",
    "residence": "Windham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "flexer@senatedems.ct.gov",
    "officePhone": "(860)240-8634"
  },
  {
    "firstName": "Stephen",
    "lastName": "Harding",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "Brookfield",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "stephen.harding@cga.ct.gov",
    "officePhone": "(860)240-8800"
  },
  {
    "firstName": "Henri",
    "lastName": "Martin",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 31,
    "partyAffiliation": "Republican",
    "residence": "Bristol",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "henri.martin@cga.ct.gov",
    "officePhone": "(860)240-0529"
  },
  {
    "firstName": "Eric",
    "lastName": "Berthel",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 32,
    "partyAffiliation": "Republican",
    "residence": "Watertown",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Eric.Berthel@cga.ct.gov",
    "officePhone": ""
  },
  {
    "firstName": "Norman",
    "lastName": "Needleman",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 33,
    "partyAffiliation": "Democrat",
    "residence": "Essex",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "needleman@senatedems.ct.gov",
    "officePhone": ""
  },
  {
    "firstName": "Paul",
    "lastName": "Cicarella",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 34,
    "partyAffiliation": "Republican",
    "residence": "North Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "paul.cicarella@cga.ct.gov",
    "officePhone": "(860)240-0558"
  },
  {
    "firstName": "Jeff",
    "lastName": "Gordon",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 35,
    "partyAffiliation": "Republican",
    "residence": "Woodstock",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jeff.gordon@cga.ct.gov",
    "officePhone": "(860)240-8800"
  },
  {
    "firstName": "Ryan",
    "lastName": "Fazio",
    "chamber": "Senate",
    "homeState": "Connecticut",
    "district": 36,
    "partyAffiliation": "Republican",
    "residence": "Greenwich",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ryan.fazio@cga.ct.gov",
    "officePhone": "(860)240-0567"
  },
  {
    "firstName": "Matthew",
    "lastName": "Ritter",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 1,
    "partyAffiliation": "Democrat",
    "residence": "Hartford",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Matthew.Ritter@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Raghib",
    "lastName": "Allie-Brennan",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 2,
    "partyAffiliation": "Democrat",
    "residence": "Bethel",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Raghib.Allie-Brennan@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Minnie",
    "lastName": "Gonzalez",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 3,
    "partyAffiliation": "Democrat",
    "residence": "Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Minnie.Gonzalez@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Julio",
    "lastName": "Concepcion",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 4,
    "partyAffiliation": "Democrat",
    "residence": "Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Julio.Concepcion@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Maryam",
    "lastName": "Khan",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 5,
    "partyAffiliation": "Democrat",
    "residence": "Windsor",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Maryam.Khan@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "James",
    "lastName": "Sanchez",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 6,
    "partyAffiliation": "Democrat",
    "residence": "Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "James.Sanchez@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Joshua",
    "lastName": "Hall",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 7,
    "partyAffiliation": "Democrat",
    "residence": "Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Joshua.Hall@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Tim",
    "lastName": "Ackert",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 8,
    "partyAffiliation": "Republican",
    "residence": "Coventry",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Tim.Ackert@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Jason",
    "lastName": "Rojas",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "East Hartford",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jason.Rojas@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Henry",
    "lastName": "Genga",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 10,
    "partyAffiliation": "Democrat",
    "residence": "East Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Henry.Genga@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Patrick",
    "lastName": "Biggins",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 11,
    "partyAffiliation": "Democrat",
    "residence": "East Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Patrick.Biggins@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Geoff",
    "lastName": "Luxenberg",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 12,
    "partyAffiliation": "Democrat",
    "residence": "Manchester",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Geoff.Luxenberg@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Jason",
    "lastName": "Doucette",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 13,
    "partyAffiliation": "Democrat",
    "residence": "Manchester",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jason.Doucette@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Tom",
    "lastName": "Delnicki",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 14,
    "partyAffiliation": "Republican",
    "residence": "South Windsor",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Tom.Delnicki@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Bobby",
    "lastName": "Gibson",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 15,
    "partyAffiliation": "Democrat",
    "residence": "Bloomfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Bobby.Gibson@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Melissa",
    "lastName": "Osborne",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 16,
    "partyAffiliation": "Democrat",
    "residence": "Simsbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Melissa.Osborne@cga.ct.gov  ",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Eleni",
    "lastName": "Kavros-DeGraw",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 17,
    "partyAffiliation": "Democrat",
    "residence": "Avon",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Eleni.Kavros-DeGraw@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Jillian",
    "lastName": "Gilchrest",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 18,
    "partyAffiliation": "Democrat",
    "residence": "West Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jillian.Gilchrest@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Tammy",
    "lastName": "Exum",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 19,
    "partyAffiliation": "Democrat",
    "residence": "West Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Tammy.Exum@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Kate",
    "lastName": "Farrar",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "West Hartford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kate.Farrar@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Mike",
    "lastName": "Demicco",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 21,
    "partyAffiliation": "Democrat",
    "residence": "Farmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Mike.Demicco@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Rebecca",
    "lastName": "Martinez",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 22,
    "partyAffiliation": "Democrat",
    "residence": "Plainville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Rebecca.Martinez@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Devin",
    "lastName": "Carney",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 23,
    "partyAffiliation": "Republican",
    "residence": "Old Lyme",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Devin.Carney@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Emmanuel",
    "lastName": "Sanchez",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 24,
    "partyAffiliation": "Democrat",
    "residence": "New Britain",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Emmanuel.Sanchez@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Robert",
    "lastName": "Sanchez",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 25,
    "partyAffiliation": "Democrat",
    "residence": "New Britain",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Robert.Sanchez@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "David",
    "lastName": "DeFronzo",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 26,
    "partyAffiliation": "Democrat",
    "residence": "New Britain",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "David.DeFronzo@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Gary",
    "lastName": "Turco",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 27,
    "partyAffiliation": "Democrat",
    "residence": "Newington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Gary.Turco@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Amy",
    "lastName": "Morrin Bello",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 28,
    "partyAffiliation": "Democrat",
    "residence": "Wethersfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Amy.MorrinBello@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Kerry",
    "lastName": "Wood",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 29,
    "partyAffiliation": "Democrat",
    "residence": "Rocky Hill",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kerry.Wood@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Donna",
    "lastName": "Veach",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "Berlin",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Donna.Veach@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Jill",
    "lastName": "Barry",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 31,
    "partyAffiliation": "Democrat",
    "residence": "Glastonbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jill.Barry@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Christie",
    "lastName": "Carpino",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 32,
    "partyAffiliation": "Republican",
    "residence": "Cromwell",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Christie.Carpino@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Brandon",
    "lastName": "Chafee",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 33,
    "partyAffiliation": "Democrat",
    "residence": "Middletown",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Brandon.Chafee@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Irene",
    "lastName": "Haines",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 34,
    "partyAffiliation": "Republican",
    "residence": "East Haddam",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Irene.Haines@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Chris",
    "lastName": "Aniskovich",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 35,
    "partyAffiliation": "Republican",
    "residence": "Clinton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Chris.Aniskovich@cga.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Renee",
    "lastName": "LaMark Muir",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 36,
    "partyAffiliation": "Democrat",
    "residence": "Deep River",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Renee.LaMarkMuir@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Nick",
    "lastName": "Menapace",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 37,
    "partyAffiliation": "Democrat",
    "residence": "East Lyme",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Nick.Menapace@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Nick",
    "lastName": "Gauthier",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 38,
    "partyAffiliation": "Democrat",
    "residence": "Waterford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Nick.Gauthier@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Anthony",
    "lastName": "Nolan",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 39,
    "partyAffiliation": "Democrat",
    "residence": "New London",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Anthony.Nolan@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Dan",
    "lastName": "Gaiewski",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 40,
    "partyAffiliation": "Democrat",
    "residence": "Groton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Dan.Gaiewski@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Aundre",
    "lastName": "Bumgardner",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 41,
    "partyAffiliation": "Democrat",
    "residence": "Groton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Aundre.Bumgardner@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Savet",
    "lastName": "Constantine",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 42,
    "partyAffiliation": "Democrat",
    "residence": "Wilton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Savet.Constantine@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Greg",
    "lastName": "Howard",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 43,
    "partyAffiliation": "Republican",
    "residence": "Stonington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Greg.Howard@cga.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Anne",
    "lastName": "Dauphinais",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 44,
    "partyAffiliation": "Republican",
    "residence": "Killingly",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Anne.Dauphinais@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Brian",
    "lastName": "Lanoue",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 45,
    "partyAffiliation": "Rebpublican",
    "residence": "Griswold",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Brian.Lanoue@cga.ct.gov",
    "officePhone": ""
  },
  {
    "firstName": "Derell",
    "lastName": "Wilson",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 46,
    "partyAffiliation": "Democrat",
    "residence": "Norwich",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Derell.Wilson@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Doug",
    "lastName": "Dubitsky",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 47,
    "partyAffiliation": "Republican",
    "residence": "Chaplin",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Doug.Dubitsky@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Mark",
    "lastName": "DeCaprio",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 48,
    "partyAffiliation": "Republican",
    "residence": "Colchester",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Mark.DeCaprio@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Susan",
    "lastName": "Johnson",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 49,
    "partyAffiliation": "Democrat",
    "residence": "Windham",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Susan.Johnson@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Patrick",
    "lastName": "Boyd",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 50,
    "partyAffiliation": "Democrat",
    "residence": "Pomfret",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Patrick.Boyd@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Chris",
    "lastName": "Stewart",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 51,
    "partyAffiliation": "Republican",
    "residence": "Putnam",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Chris.Stewart@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Kurt",
    "lastName": "Vail",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 52,
    "partyAffiliation": "Republican",
    "residence": "Stafford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kurt.Vail@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Tammy",
    "lastName": "Nuccio",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 53,
    "partyAffiliation": "Republican",
    "residence": "Tolland",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Tammy.Nuccio@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Gregory",
    "lastName": "Haddad",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 54,
    "partyAffiliation": "Democrat",
    "residence": "Mansfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Gregory.Haddad@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Steve",
    "lastName": "Weir",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 55,
    "partyAffiliation": "Republican",
    "residence": "Hebron",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Steve.Weir@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Kevin",
    "lastName": "Brown",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 56,
    "partyAffiliation": "Democrat",
    "residence": "Vernon",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kevin.Brown@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Jamie",
    "lastName": "Foster",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 57,
    "partyAffiliation": "Democrat",
    "residence": "East Windsor",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jamie.Foster@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "John",
    "lastName": "Santanella",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 58,
    "partyAffiliation": "Democrat",
    "residence": "Enfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "John.Santanella@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Carol",
    "lastName": "Hall",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 59,
    "partyAffiliation": "Republican",
    "residence": "Enfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Carol.Hall@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Jane",
    "lastName": "Garibay",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 60,
    "partyAffiliation": "Democrat",
    "residence": "Windsor",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jane.Garibay@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Tami",
    "lastName": "Zawistowski",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 61,
    "partyAffiliation": "Republican",
    "residence": "Suffield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Tami.Zawistowski@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Mark",
    "lastName": "Anderson",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 62,
    "partyAffiliation": "Republican",
    "residence": "Granby",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Mark.Anderson@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Jay",
    "lastName": "Case",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 63,
    "partyAffiliation": "Republican",
    "residence": "Winchester",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jay.Case@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Maria",
    "lastName": "Horn",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 64,
    "partyAffiliation": "Democrat",
    "residence": "Salisbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Maria.Horn@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Joe",
    "lastName": "Canino",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 65,
    "partyAffiliation": "Republican",
    "residence": "Torrington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Joe.Canino@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Karen",
    "lastName": "Reddington-Hughes",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 66,
    "partyAffiliation": "Republican",
    "residence": "Woodbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Karen.Reddington-Hughes@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Bill",
    "lastName": "Buckbee",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 67,
    "partyAffiliation": "Republican",
    "residence": "New Milford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Bill.Buckbee@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Joe",
    "lastName": "Polletta",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 68,
    "partyAffiliation": "Republican",
    "residence": "Waterton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Joe.Polletta@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Jason",
    "lastName": "Buchsbaum",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 69,
    "partyAffiliation": "Republican",
    "residence": "Southbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jason.Buchsbaum@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Seth",
    "lastName": "Bronko",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 70,
    "partyAffiliation": "Republican",
    "residence": "Naugatuck",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Seth.Bronko@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "William",
    "lastName": "Pizzuto",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 71,
    "partyAffiliation": "Republican",
    "residence": "Middlebury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "William.Pizzuto@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Larry",
    "lastName": "Butler",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 72,
    "partyAffiliation": "Democrat",
    "residence": "Waterbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Larry.Butler@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Ronald",
    "lastName": "Napoli",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 73,
    "partyAffiliation": "Democrat",
    "residence": "Waterbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Ronald.Napoli@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Michael",
    "lastName": "DiGiovancarlo",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 74,
    "partyAffiliation": "Democrat",
    "residence": "Waterbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Michael.DiGiovancarlo@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Geraldo",
    "lastName": "Reyes",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 75,
    "partyAffiliation": "Democrat",
    "residence": "Waterbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Geraldo.Reyes@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "John",
    "lastName": "Piscopo",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 76,
    "partyAffiliation": "Republican",
    "residence": "Thomaston",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "John.Piscopo@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Cara",
    "lastName": "Pavalock-D'Amato",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 77,
    "partyAffiliation": "Republican",
    "residence": "Bristol",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Cara.Pavalock-D'Amato@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Joe",
    "lastName": "Hoxha",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 78,
    "partyAffiliation": "Republican",
    "residence": "Bristol",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Joe.Hoxha@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Mary",
    "lastName": "Fortier",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 79,
    "partyAffiliation": "Democrat",
    "residence": "Bristol",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Mary.Fortier@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Gale",
    "lastName": "Mastrofrancesco",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 80,
    "partyAffiliation": "Republican",
    "residence": "Wolcott",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Gale.Mastrofrancesco@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Christopher",
    "lastName": "Poulos",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 81,
    "partyAffiliation": "Democrat",
    "residence": "Southington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Christopher.Poulos@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Michael",
    "lastName": "Quinn",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 82,
    "partyAffiliation": "Democrat",
    "residence": "Meriden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Michael.Quinn@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Jonathan",
    "lastName": "Fazzino",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 83,
    "partyAffiliation": "Democrat",
    "residence": "Berlin",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jonathan.Fazzino@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Hilda",
    "lastName": "Santiago",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 84,
    "partyAffiliation": "Democrat",
    "residence": "Meriden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Hilda.Santiago@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Mary",
    "lastName": "Mushinsky",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 85,
    "partyAffiliation": "Democrat",
    "residence": "Wallingford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Mary.Mushinsky@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Vincent",
    "lastName": "Candelora",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 86,
    "partyAffiliation": "Republican",
    "residence": "North Branford",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Vincent.Candelora@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Dave",
    "lastName": "Yaccarino",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 87,
    "partyAffiliation": "Republican",
    "residence": "North Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Dave.Yaccarino@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Josh",
    "lastName": "Elliott",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 88,
    "partyAffiliation": "Democrat",
    "residence": "Hamden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Josh.Elliott@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Lezlye",
    "lastName": "Zupkus",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 89,
    "partyAffiliation": "Republican",
    "residence": "Prospect",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Lezlye.Zupkus@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Craig",
    "lastName": "Fishbein",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 90,
    "partyAffiliation": "Republican",
    "residence": "Wallingford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Craig.Fishbein@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Laurie",
    "lastName": "Sweet",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 91,
    "partyAffiliation": "Democrat",
    "residence": "Hamden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Laurie.Sweet@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Patricia",
    "lastName": "Dillon",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 92,
    "partyAffiliation": "Democrat",
    "residence": "New Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Patricia.Dillon@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Toni",
    "lastName": "Walker",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 93,
    "partyAffiliation": "Democrat",
    "residence": "New Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Toni.Walker@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Steven",
    "lastName": "Winter",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 94,
    "partyAffiliation": "Democrat",
    "residence": "New Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Steven.Winter@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Juan",
    "lastName": "Candelaria",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 95,
    "partyAffiliation": "Democrat",
    "residence": "New Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Juan.Candelaria@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Roland",
    "lastName": "Lemar",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 96,
    "partyAffiliation": "Democrat",
    "residence": "New Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Roland.Lemar@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Alphonse",
    "lastName": "Paolillo",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 97,
    "partyAffiliation": "Democrat",
    "residence": "New Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Alphonse.Paolillo@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Moira",
    "lastName": "Rader",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 98,
    "partyAffiliation": "Democrat",
    "residence": "Guilford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Moira.Rader@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Joseph",
    "lastName": "Zulio",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 99,
    "partyAffiliation": "Republican",
    "residence": "East Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Joseph.Zulio@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Kai",
    "lastName": "Belton",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 100,
    "partyAffiliation": "Democrat",
    "residence": "Middletown",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kai.Belton@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "John-Michael",
    "lastName": "Parker",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 101,
    "partyAffiliation": "Democrat",
    "residence": "Madison",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "John-Michael.Parker@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Robin",
    "lastName": "Corney",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 102,
    "partyAffiliation": "Democrat",
    "residence": "Branford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Robin.Corney@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Liz",
    "lastName": "Linehan",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 103,
    "partyAffiliation": "Democrat",
    "residence": "Cheshire",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Liz.Linehan@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Kara",
    "lastName": "Rochelle",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 104,
    "partyAffiliation": "Democrat",
    "residence": "Ansonia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kara.Rochelle@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Nicole",
    "lastName": "Klarides-Ditria",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 105,
    "partyAffiliation": "Republican",
    "residence": "Seymour",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Nicole.Klarides-Ditria@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Mitch",
    "lastName": "Bolinsky",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 106,
    "partyAffiliation": "Republican",
    "residence": "Newtown",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mitch.bolinsky@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Martin",
    "lastName": "Foncello",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 107,
    "partyAffiliation": "Republican",
    "residence": "Brookfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Patrick.Callahan@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Patrick",
    "lastName": "Callahan",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 108,
    "partyAffiliation": "Republican",
    "residence": "New Fairfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "patrick.callahan@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Farley",
    "lastName": "Santos",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 109,
    "partyAffiliation": "Democrat",
    "residence": "Danbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Farley.Santos@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Bob",
    "lastName": "Godfrey",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 110,
    "partyAffiliation": "Democrat",
    "residence": "Danbury",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Bob.Godfrey@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Aimee",
    "lastName": "Berger-Girvalo",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 111,
    "partyAffiliation": "Democrat",
    "residence": "Ridgefield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Aimee.Berger-Girvalo@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Tony",
    "lastName": "Scott",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 112,
    "partyAffiliation": "Republican",
    "residence": "Monroe",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Tony.Scott@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Amy",
    "lastName": "Romano",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 113,
    "partyAffiliation": "Republican",
    "residence": "Shelton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Amy.Romano@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Mary",
    "lastName": "Welander",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 114,
    "partyAffiliation": "Democrat",
    "residence": "Orange",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Mary.Welander@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "William",
    "lastName": "Heffernan",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 115,
    "partyAffiliation": "Democrat",
    "residence": "West Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "William.Heffernan@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Trenee",
    "lastName": "McGee",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 116,
    "partyAffiliation": "Democrat",
    "residence": "West Haven",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Trenee.McGee@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Michael",
    "lastName": "Shannon",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 117,
    "partyAffiliation": "Democrat",
    "residence": "Milford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Michael.Shannon@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Frank",
    "lastName": "Smith",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 118,
    "partyAffiliation": "Democrat",
    "residence": "Milford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Frank.Smith@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Kathy",
    "lastName": "Kennedy",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 119,
    "partyAffiliation": "Republican",
    "residence": "Milford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kathy.Kennedy@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Kaitlyn",
    "lastName": "Shake",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 120,
    "partyAffiliation": "Democrat",
    "residence": "Stratford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kaitlyn.Shake@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Joseph",
    "lastName": "Gresko",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 121,
    "partyAffiliation": "Democrat",
    "residence": "Stratford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Joseph.Gresko@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Ben",
    "lastName": "McGorty",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 122,
    "partyAffiliation": "Republican",
    "residence": "Shelton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Ben.McGorty@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "David",
    "lastName": "Rutigliano",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 123,
    "partyAffiliation": "Republican",
    "residence": "Trumbull",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "David.Rutigliano@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Andre",
    "lastName": "Baker",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 124,
    "partyAffiliation": "Democrat",
    "residence": "Bridgeport",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Andre.Baker@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Tom",
    "lastName": "O'Dea",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 125,
    "partyAffiliation": "Republican",
    "residence": "New Canaan",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Tom.O'Dea@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Fred",
    "lastName": "Gee",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 126,
    "partyAffiliation": "Democrat",
    "residence": "Bridgeport",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Fred.Gee@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Marcus",
    "lastName": "Brown",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 127,
    "partyAffiliation": "Democrat",
    "residence": "Bridgeport",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Marcus.Brown@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Christopher",
    "lastName": "Rosario",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 128,
    "partyAffiliation": "Democrat",
    "residence": "Bridgeport",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Christopher.Rosario@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Steven",
    "lastName": "Stafstrom",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 129,
    "partyAffiliation": "Democrat",
    "residence": "Bridgeport",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Steven.Stafstrom@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Antonio",
    "lastName": "Felipe",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 130,
    "partyAffiliation": "Democrat",
    "residence": "Bridgeport",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Antonio.Felipe@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Arnold",
    "lastName": "Jensen",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 131,
    "partyAffiliation": "Republican",
    "residence": "Oxford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Arnold.Jensen@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Jennifer",
    "lastName": "Leeper",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 132,
    "partyAffiliation": "Democrat",
    "residence": "Fairfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jennifer.Leeper@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Christin",
    "lastName": "McCarthy Vahey",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 133,
    "partyAffiliation": "Democrat",
    "residence": "Fairfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Christin.McCarthyVahey@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Sarah",
    "lastName": "Keitt",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 134,
    "partyAffiliation": "Democrat",
    "residence": "Fairfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Sarah.Keitt@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Anne",
    "lastName": "Hughes",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 135,
    "partyAffiliation": "Democrat",
    "residence": "Redding",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Anne.Hughes@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Jonathan",
    "lastName": "Steinberg",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 136,
    "partyAffiliation": "Democrat",
    "residence": "Westport",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jonathan.Steinberg@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Kadeem",
    "lastName": "Roberts",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 137,
    "partyAffiliation": "Democrat",
    "residence": "Norwalk",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kadeem.Roberts@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Kenneth",
    "lastName": "Gucker",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 138,
    "partyAffiliation": "Democrat",
    "residence": "Danbury",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kenneth.Gucker@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Kevin",
    "lastName": "Ryan",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 139,
    "partyAffiliation": "Democrat",
    "residence": "Montville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kevin.Ryan@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Travis",
    "lastName": "Simms",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 140,
    "partyAffiliation": "Democrat",
    "residence": "Norwalk",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Travis.Simms@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Tracy",
    "lastName": "Marra",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 141,
    "partyAffiliation": "Republican",
    "residence": "Darien",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Tracy.Marra@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Lucy",
    "lastName": "Dathan",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 142,
    "partyAffiliation": "Democrat",
    "residence": "New Canaan",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Lucy.Dathan@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Dominique",
    "lastName": "Johnson",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 143,
    "partyAffiliation": "Democrat",
    "residence": "Norwalk",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Dominique.Johnson@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Hubert",
    "lastName": "Delany",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 144,
    "partyAffiliation": "Democrat",
    "residence": "Stamford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Hubert.Delany@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Corey",
    "lastName": "Paris",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 145,
    "partyAffiliation": "Democrat",
    "residence": "Stamford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Corey.Paris@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Eilish",
    "lastName": "Collins Main",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 146,
    "partyAffiliation": "Democrat",
    "residence": "Stamford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Eilish.CollinsMain@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Matt",
    "lastName": "Blumenthal",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 147,
    "partyAffiliation": "Democrat",
    "residence": "Stamford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Matt.Blumenthal@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Jonathan",
    "lastName": "Jacobson",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 148,
    "partyAffiliation": "Democrat",
    "residence": "Stamford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jonathan.Jacobson@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Tina",
    "lastName": "Courpas",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 149,
    "partyAffiliation": "Republican",
    "residence": "Greenwich",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Tina.Courpas@housegop.ct.gov",
    "officePhone": "(860)240-8700"
  },
  {
    "firstName": "Stephen",
    "lastName": "Meskers",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 150,
    "partyAffiliation": "Democrat",
    "residence": "Greenwich",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Stephen.Meskers@cga.ct.gov",
    "officePhone": "(860)240-8585"
  },
  {
    "firstName": "Hector",
    "lastName": "Arzeno",
    "chamber": "House",
    "homeState": "Connecticut",
    "district": 151,
    "partyAffiliation": "Democrat",
    "residence": "Greenwich",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Hector.Arzeno@cga.ct.gov",
    "officePhone": "(860)240-8585"
  }
];
