// Delaware legislators mapped to legislatorSchema
export default [
  {
    "firstName": "Daniel",
    "lastName": "Cruce",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 1,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "daniel.cruce@delaware.gov",
    "officePhone": "(302)744-4147"
  },
  {
    "firstName": "Darius",
    "lastName": "Brown",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 2,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Darius.Brown@delaware.gov",
    "officePhone": "(302)744-4286"
  },
  {
    "firstName": "S. Elizabeth",
    "lastName": "Lockman",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 3,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "elizabeth.lockman@delaware.gov",
    "officePhone": "(302)744-4168"
  },
  {
    "firstName": "Laura",
    "lastName": "Sturgeon",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 4,
    "partyAffiliation": "Democrat",
    "residence": "Brandywine Hundren",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "laura.sturgeon@delaware.gov",
    "officePhone": "(302)744-4135"
  },
  {
    "firstName": "Ray",
    "lastName": "Seigfried",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 5,
    "partyAffiliation": "Democrat",
    "residence": "Arden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ray.seigfried@delaware.gov",
    "officePhone": "(302)744-4137"
  },
  {
    "firstName": "Russell",
    "lastName": "Huxtable",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 6,
    "partyAffiliation": "Democrat",
    "residence": "Lewes",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "russell.huxtable@delaware.gov",
    "officePhone": ""
  },
  {
    "firstName": "Spiros",
    "lastName": "Mantzavinos",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 7,
    "partyAffiliation": "Democrat",
    "residence": "Westgate Farms",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "spiros.manzavinos@delaware.gov",
    "officePhone": "(302)744-4133"
  },
  {
    "firstName": "David",
    "lastName": "Sokola",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "Newark",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "David.Sokola@delaware.gov",
    "officePhone": "(302)744-4139"
  },
  {
    "firstName": "John",
    "lastName": "Walsh",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 9,
    "partyAffiliation": "Democrat",
    "residence": "Newport",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "john.walsh@delaware.gov",
    "officePhone": "(302)744-4163"
  },
  {
    "firstName": "Stephanie",
    "lastName": "Hansen",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 10,
    "partyAffiliation": "Democrat",
    "residence": "Middletown",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Stephanie.Hansen@delaware.gov",
    "officePhone": "(302)744-4138"
  },
  {
    "firstName": "Bryan",
    "lastName": "Townsend",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 11,
    "partyAffiliation": "Democrat",
    "residence": "Westover Woods",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Bryan.Townsend@delaware.gov",
    "officePhone": "(302)744-4165"
  },
  {
    "firstName": "Nicole",
    "lastName": "Poore",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 12,
    "partyAffiliation": "Democrat",
    "residence": "Barbs Farm",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Nicole.Poore@delaware.gov",
    "officePhone": "(302)744-4164"
  },
  {
    "firstName": "Marie",
    "lastName": "Pinkney",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 13,
    "partyAffiliation": "Democrat",
    "residence": "New Castle County",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Marie.Pinkney@delaware.gov",
    "officePhone": "(302)744-4167"
  },
  {
    "firstName": "Kyra",
    "lastName": "Hoffner",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 14,
    "partyAffiliation": "Democrat",
    "residence": "Leipsic",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kyra.Hoffner@delaware.gov",
    "officePhone": ""
  },
  {
    "firstName": "Dave",
    "lastName": "Lawson",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 15,
    "partyAffiliation": "Republican",
    "residence": "Marydel",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Dave.Lawson@delaware.gov",
    "officePhone": "(302)744-4237"
  },
  {
    "firstName": "Eric",
    "lastName": "Buckson",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 16,
    "partyAffiliation": "Republican",
    "residence": "Camden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "eric.buckson@delaware.gov",
    "officePhone": ""
  },
  {
    "firstName": "Trey",
    "lastName": "Paradee",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 17,
    "partyAffiliation": "Democrat",
    "residence": "Dover",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Trey.Paradee@delaware.gov",
    "officePhone": "(302)744-4162"
  },
  {
    "firstName": "David",
    "lastName": "Wilson",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 18,
    "partyAffiliation": "Republican",
    "residence": "Lincoln",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "David.L.Wilson@delaware.gov",
    "officePhone": "(302)744-4048"
  },
  {
    "firstName": "Brian",
    "lastName": "Pettyjohn",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 19,
    "partyAffiliation": "Republican",
    "residence": "Georgetown",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Brian.Pettyjohn@delaware.gov",
    "officePhone": "(302)744-4117"
  },
  {
    "firstName": "Gerald",
    "lastName": "Hocker",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 20,
    "partyAffiliation": "Republican",
    "residence": "Ocean View",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Gerald.Hocker@delaware.gov",
    "officePhone": "(302)744-4144"
  },
  {
    "firstName": "Bryant",
    "lastName": "Richardson",
    "chamber": "Senate",
    "homeState": "Delaware",
    "district": 21,
    "partyAffiliation": "Republican",
    "residence": "Laurel",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Bryant.Richardson@delaware.gov",
    "officePhone": "(302)744-4298"
  },
  {
    "firstName": "Nnamdi",
    "lastName": "Chukwuocha",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 1,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Nnamdi.Chukwuocha@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Stephanie",
    "lastName": "Bolden",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 2,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "StephanieT.Bolden@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Josue",
    "lastName": "Ortega",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 3,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "josue.ortega@delaware.gov",
    "officePhone": "(302)744-4284"
  },
  {
    "firstName": "Jeff",
    "lastName": "Hilovsky",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "Long Neck",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Jeff.Hilovsky@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Kendra",
    "lastName": "Johnson",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 5,
    "partyAffiliation": "Democrat",
    "residence": "New Castle",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kendra.Johnson@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Debra",
    "lastName": "Heffernan",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 6,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Debra.Heffernan@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Larry",
    "lastName": "Lambert",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 7,
    "partyAffiliation": "Democrat",
    "residence": "Claymont",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Larry.Lambert@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Sherae'a",
    "lastName": "Moore",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "Middletown",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Rae.Moore@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Kevin",
    "lastName": "Hensley",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 9,
    "partyAffiliation": "Republican",
    "residence": "Townsend",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kevin.Hensley@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Melanie",
    "lastName": "Levin",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 10,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Melanie.RossLevin@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Jeffrey",
    "lastName": "Spiegelman",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 11,
    "partyAffiliation": "Republican",
    "residence": "Clayton",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jeff.spiegelman@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Krista",
    "lastName": "Griffith",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 12,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Krista.Griffith@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "DeShanna",
    "lastName": "Neal",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 13,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "deshanna.neal@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Claire",
    "lastName": "Snyder-Hall",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 14,
    "partyAffiliation": "Democrat",
    "residence": "Rehoboth Beach",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "claire.snyder-hall@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Kamela",
    "lastName": "Smith",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 15,
    "partyAffiliation": "Democrat",
    "residence": "Bear",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kamela.smith@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Franklin",
    "lastName": "Cooke",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 16,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "FranklinD.Cooke@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Melissa",
    "lastName": "Minor-Brown",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 17,
    "partyAffiliation": "Democrat",
    "residence": "New Castle",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Melissa.MinorBrown@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Sophie",
    "lastName": "Phillips",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 18,
    "partyAffiliation": "Democrat",
    "residence": "New Castle",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "sophie.phillips@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Kimberly",
    "lastName": "Williams",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 19,
    "partyAffiliation": "Democrat",
    "residence": "Wilmington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Kimberly.Williams@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Stell",
    "lastName": "Parker Selby",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 20,
    "partyAffiliation": "Democrat",
    "residence": "Milton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "stell.parkerselby@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Frank",
    "lastName": "Burns",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 21,
    "partyAffiliation": "Democrat",
    "residence": "Newark",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "frank.burns@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Michael",
    "lastName": "Smith",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 22,
    "partyAffiliation": "Republican",
    "residence": "Newark",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "michael.f.smith@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Mara",
    "lastName": "Gorman",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 23,
    "partyAffiliation": "Democrat",
    "residence": "Newark",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Mara.Gorman@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Edward",
    "lastName": "Osienski",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 24,
    "partyAffiliation": "Democrat",
    "residence": "Newark",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "edward.osienski@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Cyndie",
    "lastName": "Romer",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 25,
    "partyAffiliation": "Democrat",
    "residence": "Newark",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "cyndie.romer@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Madinah",
    "lastName": "Wilson-Anton",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 26,
    "partyAffiliation": "Democrat",
    "residence": "Newark",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Madinah.Wilson-Anton@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Eric",
    "lastName": "Morrison",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 27,
    "partyAffiliation": "Democrat",
    "residence": "Newark",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Eric.Morrison@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "William",
    "lastName": "Carson",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 28,
    "partyAffiliation": "Democrat",
    "residence": "Smyrna",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "William.Carson@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "William",
    "lastName": "Bush",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 29,
    "partyAffiliation": "Democrat",
    "residence": "Camden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "william.bush@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Shannon",
    "lastName": "Morris",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "Camden",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Shannon.Morris@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Sean",
    "lastName": "Lynn",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 31,
    "partyAffiliation": "Democrat",
    "residence": "Dover",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Sean.Lynn@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Kerri Evelyn",
    "lastName": "Harris",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 32,
    "partyAffiliation": "Democrat",
    "residence": "Dover",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kerrievelyn.harris@delaware.gov",
    "officePhone": "(302)744-4351"
  },
  {
    "firstName": "Charles",
    "lastName": "Postles",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 33,
    "partyAffiliation": "Republican",
    "residence": "Milford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Charles.Postles@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Lyndon",
    "lastName": "Yearick",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 34,
    "partyAffiliation": "Republican",
    "residence": "Magnolia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "lyndon.yearick@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Jesse",
    "lastName": "Vanderwende",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 35,
    "partyAffiliation": "Republican",
    "residence": "Bridgeville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jesse.vanderwende@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Bryan",
    "lastName": "Shupe",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 36,
    "partyAffiliation": "Republican",
    "residence": "Milford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Bryan.Shupe@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Valerie",
    "lastName": "Jones Giltner",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 37,
    "partyAffiliation": "Republican",
    "residence": "Georgetown",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Valerie.JonesGiltner@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Ronald",
    "lastName": "Gray",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 38,
    "partyAffiliation": "Republican",
    "residence": "Selbyville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Ronald.Gray@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Daniel",
    "lastName": "Short",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 39,
    "partyAffiliation": "Republican",
    "residence": "Seaford",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Daniel.Short@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Timothy",
    "lastName": "Dukes",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 40,
    "partyAffiliation": "Republican",
    "residence": "Laurel",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Timothy.Dukes@delaware.gov",
    "officePhone": "(302)744-4171"
  },
  {
    "firstName": "Richard",
    "lastName": "Collins",
    "chamber": "House",
    "homeState": "Delaware",
    "district": 41,
    "partyAffiliation": "Republican",
    "residence": "Millsboro",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Rich.Collins@delaware.gov",
    "officePhone": "(302)744-4171"
  }
];
