// Florida legislators mapped to legislatorSchema
export default [
  {
    "firstName": "Michelle",
    "lastName": "Salzman",
    "chamber": "House",
    "homeState": "Florida",
    "district": 1,
    "partyAffiliation": "Republican",
    "residence": "Cantonment",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5001"
  },
  {
    "firstName": "Alex",
    "lastName": "Andrade",
    "chamber": "House",
    "homeState": "Florida",
    "district": 2,
    "partyAffiliation": "Republican",
    "residence": "Pensacola",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5002"
  },
  {
    "firstName": "Vacant",
    "lastName": "Vacant",
    "chamber": "House",
    "homeState": "Florida",
    "district": 3,
    "partyAffiliation": "Vacant",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "Patt",
    "lastName": "Maney",
    "chamber": "House",
    "homeState": "Florida",
    "district": 4,
    "partyAffiliation": "Republican",
    "residence": "Destin",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5004"
  },
  {
    "firstName": "Shane",
    "lastName": "Abbott",
    "chamber": "House",
    "homeState": "Florida",
    "district": 5,
    "partyAffiliation": "Republican",
    "residence": "DeFuniak Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5005"
  },
  {
    "firstName": "Philip",
    "lastName": "Griffitts",
    "chamber": "House",
    "homeState": "Florida",
    "district": 6,
    "partyAffiliation": "Republican",
    "residence": "Panama City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5006"
  },
  {
    "firstName": "Jason",
    "lastName": "Shoaf",
    "chamber": "House",
    "homeState": "Florida",
    "district": 7,
    "partyAffiliation": "Republican",
    "residence": "Port St. Joe",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5007"
  },
  {
    "firstName": "Gallop",
    "lastName": "Franklin",
    "chamber": "House",
    "homeState": "Florida",
    "district": 8,
    "partyAffiliation": "Democrat",
    "residence": "Tallahassee",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5008"
  },
  {
    "firstName": "Allison",
    "lastName": "Tant",
    "chamber": "House",
    "homeState": "Florida",
    "district": 9,
    "partyAffiliation": "Democratic",
    "residence": "Tallahassee",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5009"
  },
  {
    "firstName": "Chuck",
    "lastName": "Brannan",
    "chamber": "House",
    "homeState": "Florida",
    "district": 10,
    "partyAffiliation": "Republican",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5010"
  },
  {
    "firstName": "Sam",
    "lastName": "Garrison",
    "chamber": "House",
    "homeState": "Florida",
    "district": 11,
    "partyAffiliation": "Republican",
    "residence": "Orange Park",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5011"
  },
  {
    "firstName": "Wyman",
    "lastName": "Duggan",
    "chamber": "House",
    "homeState": "Florida",
    "district": 12,
    "partyAffiliation": "Republican",
    "residence": "Jacksonville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5012"
  },
  {
    "firstName": "Angie",
    "lastName": "Nixon",
    "chamber": "House",
    "homeState": "Florida",
    "district": 13,
    "partyAffiliation": "Democrat",
    "residence": "Jacksonville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5013"
  },
  {
    "firstName": "Ashley",
    "lastName": "Aune",
    "chamber": "House",
    "homeState": "Florida",
    "district": 14,
    "partyAffiliation": "Democrat",
    "residence": "Kansas City",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-50"
  },
  {
    "firstName": "Ken",
    "lastName": "Jamison",
    "chamber": "House",
    "homeState": "Florida",
    "district": 15,
    "partyAffiliation": "Democrat",
    "residence": "Gladstone",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5015"
  },
  {
    "firstName": "Chris",
    "lastName": "Brown",
    "chamber": "House",
    "homeState": "Florida",
    "district": 16,
    "partyAffiliation": "Republican",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chris.brown@house.mo.gov",
    "officePhone": "(850)717-5016"
  },
  {
    "firstName": "Bill",
    "lastName": "Allen",
    "chamber": "House",
    "homeState": "Florida",
    "district": 17,
    "partyAffiliation": "Republican",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "bill.allen@house.mo.gov",
    "officePhone": "(850)717-5017"
  },
  {
    "firstName": "Eric",
    "lastName": "Woods",
    "chamber": "House",
    "homeState": "Florida",
    "district": 18,
    "partyAffiliation": "Democrat",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "eric.woods@house.mo.gov",
    "officePhone": "(850)717-5018"
  },
  {
    "firstName": "Wick",
    "lastName": "Thomas",
    "chamber": "House",
    "homeState": "Florida",
    "district": 19,
    "partyAffiliation": "Democrat",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "wick.thomas@house.mo.gov",
    "officePhone": "(850)717-5019"
  },
  {
    "firstName": "Mike",
    "lastName": "Steinmeyer",
    "chamber": "House",
    "homeState": "Florida",
    "district": 20,
    "partyAffiliation": "Republican",
    "residence": "Sugar Creek",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mike.steinmeyer@house.mo.gov",
    "officePhone": "(850)717-5020"
  },
  {
    "firstName": "Will",
    "lastName": "Jobe",
    "chamber": "House",
    "homeState": "Florida",
    "district": 21,
    "partyAffiliation": "Democrat",
    "residence": "Independence",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "will.jobe@house.mo.gov",
    "officePhone": "(850)717-5021"
  },
  {
    "firstName": "Yolanda",
    "lastName": "Young",
    "chamber": "House",
    "homeState": "Florida",
    "district": 22,
    "partyAffiliation": "Democrat",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "yolanda.young@house.mo.gov",
    "officePhone": "(850)717-5022"
  },
  {
    "firstName": "Michael",
    "lastName": "Johnson",
    "chamber": "House",
    "homeState": "Florida",
    "district": 23,
    "partyAffiliation": "Democrat",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "michael.johnson@house.mo.gov",
    "officePhone": "(850)717-5023"
  },
  {
    "firstName": "Emily",
    "lastName": "Weber",
    "chamber": "House",
    "homeState": "Florida",
    "district": 24,
    "partyAffiliation": "Democrat",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "emily.weber@house.mo.gov",
    "officePhone": "(850)717-5024"
  },
  {
    "firstName": "Pattie",
    "lastName": "Mansur",
    "chamber": "House",
    "homeState": "Florida",
    "district": 25,
    "partyAffiliation": "Democrat",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "pattie.mansur@house.mo.gov",
    "officePhone": "(850)717-5025"
  },
  {
    "firstName": "Tiffany",
    "lastName": "Price",
    "chamber": "House",
    "homeState": "Florida",
    "district": 26,
    "partyAffiliation": "Democrat",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tiffany.price@house.mo.gov",
    "officePhone": "(850)717-5026"
  },
  {
    "firstName": "Melissa",
    "lastName": "Douglas",
    "chamber": "House",
    "homeState": "Florida",
    "district": 27,
    "partyAffiliation": "Democrat",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "melissa.douglas@house.mo.gov",
    "officePhone": "(850)717-5027"
  },
  {
    "firstName": "Donna",
    "lastName": "Barnes",
    "chamber": "House",
    "homeState": "Florida",
    "district": 28,
    "partyAffiliation": "Democrat",
    "residence": "Raytown",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "donna.barnes@house.mo.gov",
    "officePhone": "(850)717-5028"
  },
  {
    "firstName": "Aaron",
    "lastName": "Crossley",
    "chamber": "House",
    "homeState": "Florida",
    "district": 29,
    "partyAffiliation": "Democrat",
    "residence": "Independence",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "aaron.crossley@house.mo.gov",
    "officePhone": "(850)717-5029"
  },
  {
    "firstName": "Jonathan",
    "lastName": "Patterson",
    "chamber": "House",
    "homeState": "Florida",
    "district": 30,
    "partyAffiliation": "Republican",
    "residence": "Lee's Summit",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jonathan.patterson@house.mo.gov",
    "officePhone": "(850)717-5030"
  },
  {
    "firstName": "Ron",
    "lastName": "Fowler",
    "chamber": "House",
    "homeState": "Florida",
    "district": 31,
    "partyAffiliation": "Republican",
    "residence": "Blue Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "ron.fowler@house.mo.gov",
    "officePhone": "(850)717-5031"
  },
  {
    "firstName": "Jeff",
    "lastName": "Coleman",
    "chamber": "House",
    "homeState": "Florida",
    "district": 32,
    "partyAffiliation": "Republican",
    "residence": "Grain Valley",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jeff.coleman@house.mo.gov",
    "officePhone": "(850)717-5032"
  },
  {
    "firstName": "Carolyn",
    "lastName": "Caton",
    "chamber": "House",
    "homeState": "Florida",
    "district": 33,
    "partyAffiliation": "Republican",
    "residence": "Blue Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "carolyn.caton@house.mo.gov",
    "officePhone": "(850)717-5033"
  },
  {
    "firstName": "Kemp",
    "lastName": "Strickler",
    "chamber": "House",
    "homeState": "Florida",
    "district": 34,
    "partyAffiliation": "Democrat",
    "residence": "Lee's Summit",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kemp.strickler@house.mo.gov",
    "officePhone": "(850)717-5034"
  },
  {
    "firstName": "Keri",
    "lastName": "Ingle",
    "chamber": "House",
    "homeState": "Florida",
    "district": 35,
    "partyAffiliation": "Democrat",
    "residence": "Lee's Summit",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "keri.ingle@house.mo.gov",
    "officePhone": "(850)717-5035"
  },
  {
    "firstName": "Anthony",
    "lastName": "Ealy",
    "chamber": "House",
    "homeState": "Florida",
    "district": 36,
    "partyAffiliation": "Democrat",
    "residence": "Grandview",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "anthony.ealy@house.mo.gov",
    "officePhone": "(850)717-5036"
  },
  {
    "firstName": "Mark",
    "lastName": "Sharp",
    "chamber": "House",
    "homeState": "Florida",
    "district": 37,
    "partyAffiliation": "Democrat",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mark.sharp@house.mo.gov",
    "officePhone": "(850)717-5037"
  },
  {
    "firstName": "Martin",
    "lastName": "Jacobs",
    "chamber": "House",
    "homeState": "Florida",
    "district": 38,
    "partyAffiliation": "Democrat",
    "residence": "Liberty",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "martin.jacobs@house.mo.gov",
    "officePhone": "(850)717-5038"
  },
  {
    "firstName": "Mark",
    "lastName": "Meirath",
    "chamber": "House",
    "homeState": "Florida",
    "district": 39,
    "partyAffiliation": "Republican",
    "residence": "Excelsior Springs",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "mark.meirath@house.mo.gov",
    "officePhone": "(850)717-5039"
  },
  {
    "firstName": "Chad",
    "lastName": "Perkins",
    "chamber": "House",
    "homeState": "Florida",
    "district": 40,
    "partyAffiliation": "Republican",
    "residence": "Bowling Green",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "chad.perkins@house.mo.gov",
    "officePhone": "(850)717-5040"
  },
  {
    "firstName": "Doyle",
    "lastName": "Justus",
    "chamber": "House",
    "homeState": "Florida",
    "district": 41,
    "partyAffiliation": "Republican",
    "residence": "Troy",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "doyle.justus@house.mo.gov",
    "officePhone": "(850)717-5041"
  },
  {
    "firstName": "Jeff",
    "lastName": "Myers",
    "chamber": "House",
    "homeState": "Florida",
    "district": 42,
    "partyAffiliation": "Republican",
    "residence": "Warrenton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jeff.myers@house.mo.gov",
    "officePhone": "(850)717-5042"
  },
  {
    "firstName": "Kent",
    "lastName": "Haden",
    "chamber": "House",
    "homeState": "Florida",
    "district": 43,
    "partyAffiliation": "Republican",
    "residence": "Mexico",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kent.haden@house.mo.gov",
    "officePhone": "(850)717-5043"
  },
  {
    "firstName": "John",
    "lastName": "Martin",
    "chamber": "Columbia",
    "homeState": "Florida",
    "district": 44,
    "partyAffiliation": "Republican",
    "residence": "Columbia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "john.martin@house.mo.gov",
    "officePhone": "(850)717-5044"
  },
  {
    "firstName": "Kathy",
    "lastName": "Steinhoff",
    "chamber": "House",
    "homeState": "Florida",
    "district": 45,
    "partyAffiliation": "Democrat",
    "residence": "Columbia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "kathy.steinhoff@house.mo.gov",
    "officePhone": "(850)717-5045"
  },
  {
    "firstName": "David Tyson",
    "lastName": "Smith",
    "chamber": "House",
    "homeState": "Florida",
    "district": 46,
    "partyAffiliation": "Democrat",
    "residence": "Columbia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "David.smith@house.mo.gov",
    "officePhone": "(850)717-5046"
  },
  {
    "firstName": "Adrian",
    "lastName": "Plank",
    "chamber": "House",
    "homeState": "Florida",
    "district": 47,
    "partyAffiliation": "Democrat",
    "residence": "Columbia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "adrian.plank@house.mo.gov",
    "officePhone": "(850)717-5047"
  },
  {
    "firstName": "Tim",
    "lastName": "Taylor",
    "chamber": "House",
    "homeState": "Florida",
    "district": 48,
    "partyAffiliation": "Republican",
    "residence": "Bunceton",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "tim.taylor@house.mo.gov",
    "officePhone": "(850)717-5048"
  },
  {
    "firstName": "Jim",
    "lastName": "Schulte",
    "chamber": "House",
    "homeState": "Florida",
    "district": 49,
    "partyAffiliation": "Republican",
    "residence": "New Bloomfield",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "jim.schulte@house.mo.gov",
    "officePhone": "(850)717-5049"
  },
  {
    "firstName": "Gregg",
    "lastName": "Bush",
    "chamber": "House",
    "homeState": "Florida",
    "district": 50,
    "partyAffiliation": "Democrat",
    "residence": "Columbia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Gregg.Bush@house.mo.gov",
    "officePhone": "(850)717-5050"
  },
  {
    "firstName": "Mark",
    "lastName": "Nolte",
    "chamber": "House",
    "homeState": "Florida",
    "district": 51,
    "partyAffiliation": "Republican",
    "residence": "Higginsville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "Mark.Nolte@house.mo.gov",
    "officePhone": "(850)717-5051"
  },
  {
    "firstName": "Brad",
    "lastName": "Pollitt",
    "chamber": "House",
    "homeState": "Florida",
    "district": 52,
    "partyAffiliation": "Republican",
    "residence": "Sedalia",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "brad.pollitt@house.mo.gov",
    "officePhone": "(850)717-5052"
  },
  {
    "firstName": "Terry",
    "lastName": "Thompson",
    "chamber": "House",
    "homeState": "Florida",
    "district": 53,
    "partyAffiliation": "Republican",
    "residence": "Lexington",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "terry.thompson@house.mo.gov",
    "officePhone": "(850)717-5053"
  },
  {
    "firstName": "Brandon",
    "lastName": "Phelps",
    "chamber": "House",
    "homeState": "Florida",
    "district": 54,
    "partyAffiliation": "Republican",
    "residence": "Warrensburg",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "brandon.phelps@house.mo.gov",
    "officePhone": "(850)717-5054"
  },
  {
    "firstName": "Bill",
    "lastName": "Irwin",
    "chamber": "House",
    "homeState": "Florida",
    "district": 55,
    "partyAffiliation": "Republican",
    "residence": "Lee's Summit",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "bill.irwin@house.mo.gov",
    "officePhone": "(850)717-5055"
  },
  {
    "firstName": "Michael",
    "lastName": "Davis",
    "chamber": "House",
    "homeState": "Florida",
    "district": 56,
    "partyAffiliation": "Republican",
    "residence": "Kansas City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "michael.davis@house.mo.gov",
    "officePhone": "(850)717-5056"
  },
  {
    "firstName": "Rodger",
    "lastName": "Reedy",
    "chamber": "House",
    "homeState": "Florida",
    "district": 57,
    "partyAffiliation": "Republican",
    "residence": "Windsor",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rodger.reedy@house.mo.gov",
    "officePhone": "(850)717-5057"
  },
  {
    "firstName": "Willard",
    "lastName": "Haley",
    "chamber": "House",
    "homeState": "Florida",
    "district": 58,
    "partyAffiliation": "Republican",
    "residence": "Eldon",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "willard.haley@house.mo.gov",
    "officePhone": "(850)717-5058"
  },
  {
    "firstName": "Rudy",
    "lastName": "Veit",
    "chamber": "House",
    "homeState": "Florida",
    "district": 59,
    "partyAffiliation": "Republican",
    "residence": "Wardsville",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "rudy.veit@house.mo.gov",
    "officePhone": "(850)717-5059"
  },
  {
    "firstName": "Dave",
    "lastName": "Griffith",
    "chamber": "House",
    "homeState": "Florida",
    "district": 60,
    "partyAffiliation": "Republican",
    "residence": "Jefferson City",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": "(850)717-5060"
  },
  {
    "firstName": "Bruce",
    "lastName": "Sassman",
    "chamber": "House",
    "homeState": "Florida",
    "district": 61,
    "partyAffiliation": "Republican",
    "residence": "Bland",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 62,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 63,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 64,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 65,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 66,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 67,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 68,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 69,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 70,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 71,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 72,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 73,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 74,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 75,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 76,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 77,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 78,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 79,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 80,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 81,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 82,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 83,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 84,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 85,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 86,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "v",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 87,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 88,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 89,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 90,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 91,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 92,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 93,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 94,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 95,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 96,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 97,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 98,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 99,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 100,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 101,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 102,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 103,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 104,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 105,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 106,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 107,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 108,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 109,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 110,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 111,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 112,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 113,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 114,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 115,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 116,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 117,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 118,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 119,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "House",
    "homeState": "Florida",
    "district": 120,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 1,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 2,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 3,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 4,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 5,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 6,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 7,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 8,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 9,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 10,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 11,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 12,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 13,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 14,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 15,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 16,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 17,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 18,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 19,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 20,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 21,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 22,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 23,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 24,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 25,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 26,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 27,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 28,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 29,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "v",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 30,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 31,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 32,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 33,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 34,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": true,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 35,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 36,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 37,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 38,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "v",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 39,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  },
  {
    "firstName": "",
    "lastName": "",
    "chamber": "Senate",
    "homeState": "Florida",
    "district": 40,
    "partyAffiliation": "",
    "residence": "",
    "isLeadership": false,
    "isChair": false,
    "isViceChair": false,
    "isRankingMember": false,
    "email": "",
    "officePhone": ""
  }
];
